"""Render audited stored observations. Never runs a fight."""
import pathlib,json,time,sys,re,statistics
HERE=pathlib.Path(__file__).resolve().parent;CPP=HERE.parent;REPO=CPP.parents[2];sys.path.insert(0,str(CPP));from build_admission import sha
write=lambda p,v:p.write_text(json.dumps(v,indent=2,allow_nan=False)+'\n')
def main():
 s=json.loads((HERE/'SUMMARY.json').read_text());d=json.loads((HERE/'DECLARATION.json').read_text());sanity=json.loads((HERE/'P5_SANITY.json').read_text())
 for n,h in d['protected'].items():assert sha(REPO/n)==h,n
 for n,h in json.loads((HERE/'RUN_START.json').read_text())['code'].items():assert sha(REPO/n)==h,n
 def fmt(v):return 'n/a' if v is None else f'{v:.2f}'
 text='''DONE

160/160 fights: 10 fresh development clusters ×2 orientations ×P5/P7/P8/P9 ×regular/novice. Controlled team0, unchanged S4 world and v6 attempt-2 knobs; descriptive scripted probe of DESIGN_0G §19.4. No RRG-controller, tuning, registration, judging or status change. [Design review](../../../docs/reviews/tactical_0g_s194_probe_review_codex.md): APPROVE_WITH_NOTES.

Before fights, [POLICY.md](s4_collective_probe_v1/POLICY.md) and [DECLARATION.json](s4_collective_probe_v1/DECLARATION.json) pin all conventions: unique outer staging-ray solve; full-sight timer from first prepare; target retained until death; P9 outward axis acquired per target, live target position and per-tick angular assignment; mathematical post arrival; native inclusive artillery bands/direct surface gap; pooled exposure; censored simultaneity and PCA modulo pi. The original P5 controller is reused unchanged. P7 bundles target sharing, staging, early gun-target suppression and a wave; P8 adds both direct movement and targeting; P9 adds target selection and end-on arc geometry. They do not isolate those mechanisms causally.

'''
 text+=f"P5 sanity was reported before other-arm outcomes: **{sanity['status']}**, regular mean guns destroyed {sanity['regular_mean_enemy_guns_destroyed']:.2f}/10 and own guns lost {sanity['regular_mean_own_gun_losses']:.2f}/10. Declared bounds are [1,6] and [7,10], respectively.\n\n"
 text+='|Arm|Head|Eliminations|Timeouts|Mean S|Enemy guns killed|Own guns lost|Own losses|Exposure/gun-tick|First gun kill s|Shell hits/launches at guns|\n|---|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|\n'
 for r in s['rows']:text+=f"|{r['arm']}|{r['head']}|{r['elimination_wins']}/20|{r['timeouts']}/20|{r['mean_S']:+.2f}|{r['mean_enemy_guns_destroyed']:.2f}|{r['mean_own_gun_losses']:.2f}|{r['mean_own_losses']:.2f}|{fmt(r['mean_realized_exposure'])}|{fmt(r['mean_first_enemy_gun_kill_s'])} ({r['first_gun_kill_fights']}/20)|{r['shell_hits_on_enemy_guns']}/{r['shells_fired_at_enemy_guns']}|\n"
 text+='\n|Arm|Head|Waves/reasons|Engagement latency s (observed)|Line-angle change deg (observed)|Fights reaching posts|Fights escort arrival|Escort focus unit-ticks|\n|---|---|---|---|---|---:|---:|---:|\n'
 for r in s['rows']:text+=f"|{r['arm']}|{r['head']}|{r['waves_started']}/20 {r['wave_reasons']}|{fmt(r['mean_simultaneity_s'])} ({r['simultaneity_observed_fights']}/20)|{fmt(r['mean_enemy_line_angle_change_degrees'])} ({r['line_angle_observed_fights']}/20)|{r['fights_reaching_posts']}/20|{r['fights_escorts_reaching_points']}/20|{r['escort_focus_eligible_unit_ticks']}|\n"
 text+='\nElimination timing audit (before-wave / after-wave): '+', '.join(f"{r['arm']} {r['head']} {r['elimination_before_wave']}/{r['elimination_after_wave']}" for r in s['rows'] if r['arm']!='P5')+'.\n'
 text+='\nOwn gun killers, totals across20 fights per cell:\n\n|Arm|Head|Team/role/deaths|\n|---|---|---|\n'
 for r in s['rows']:text+=f"|{r['arm']}|{r['head']}|"+', '.join(f"team {k['team']} {k['role']} {k['kills']}" for k in r['own_gun_killers'])+'|\n'
 text+=f"\n**§19.4 outcome reading:** {s['outcome_reading']}. This is a descriptive pattern at one declared setting, not causal proof or a resonator result. Novice is a sanity check only; an observed elimination does not establish the above50% plus positiveS development criterion.\n\n"
 for head in ('regular','novice'):
  q=next(r for r in s['rows'] if r['arm']=='P9' and r['head']==head)
  fights=[r for r in s['fights'] if r['arm']=='P9' and r['head']==head];wave_living=statistics.mean(r['wave']['living'] for r in fights);end_living=statistics.mean(r['simultaneity_counts']['living'] for r in fights);arrived=statistics.mean(r['post_arrival_guns'] for r in fights)
  text+=f"P9 {head} realization: all{q['waves_started']}/20 waves used the20s fallback; no readiness trigger. Mathematical staging was outside the arena for{q['staging_outside_gun_ticks']} pre-wave gun-ticks; committed posts were outside for{q['post_outside_gun_ticks']} command gun-ticks. Some gun reached a post in{q['fights_reaching_posts']}/20 fights, which does not establish simultaneous whole-battery arrival. Some escort reached its point in{q['fights_escorts_reaching_points']}/20 fights. Mean living guns at wave={wave_living:.2f}/10, at80% engagement endpoint={end_living:.2f}/10; mean guns ever reaching a post={arrived:.2f}/10. The short latency therefore describes an already depleted battery.\n\n"
 text+='Exposure averages use different policy-defined commitment intervals: P5 includes its full approach from the first tick, while P7–P9 exclude staging. Zero-exposure approach ticks can lower the P5 average; these pooled values are not exposure at a common distance/time. The static1-versus3–4 geometry estimate was not assumed as a realized measurement.\n\n'
 text+='''Elimination requires enemy0, own>=1 and t<150; timeout is never a win. S is survivor difference. Casualties are means per fight; shell counts are summed. Shell-hit numerator counts distinct damaging targeted launches, once across splash victims; incidental gun splash from nongun targets is excluded. Launch denominator includes misses and shells airborne at termination. First kill is conditional; no-kill cases stay censored. Exposure pools committed gun-ticks, excludes staging, uses actual post-step living positions and each enemy's native band. P5 has no wave, so simultaneity and line response are not applicable. Other censored cases are null, never assigned zero/150. The JSON retains denominators, killer unit IDs, per-fight timing, initial-wave cohort and attrition, target changes, post/escort arrival counts, and out-of-arena theoretical goals.

Realization/confounds: native collisions, clipping, reflexes and blockers can prevent theoretical arrivals or shots. The P9 acquired axis is fixed per target; line rotation can defeat it. Dynamic angular reassignment can change approach goals. Wave readiness and engagement use surviving-gun denominators, so attrition can manufacture80% arrival; cohort audits disclose that. The screen is a movement/targeting bundle and can obstruct own fire; escort arrival alone does not establish protection. PCA angle changes can reflect deformation or casualty/cohort changes, rather than line turning. First gun kills before wave, insufficient geometry and nonidentifiable PCA are unavailable. A named favorable pattern with missing waves/posts/escorts is inconclusive for that intervention; an elimination during staging cannot demonstrate collective commitment. Partial realization limits interpretation even when aggregate outcome thresholds match. No failed intervention is interpreted as rejection of all collective commitment. Auto barrage/slow stay off with sandboxAbilities=false.

'''
 used=sum(json.loads(p.read_text())['awake_seconds'] for p in HERE.glob('STAGE_*.json'))
 text+=f"Measured completed probe stages before this render: awake time {used:.3f}s. All compute uses caffeinate; two combat workers,1200s stage caps and a total3600s measured/projection guard with900s analysis/recheck reserve during combat. Build/check/analysis logs retain elapsed/awake times. No code edits during fights or recount. Bootstrap/hash work and review bookkeeping receive a conservative additional60s reserve; final review timings are adjacent.\n\n"
 if (HERE/'REVIEW_TIMING.json').exists():
  review=json.loads((HERE/'REVIEW_TIMING.json').read_text());review_time=review.get('cumulative_awake_seconds',review.get('conservative_total_seconds',review.get('awake_seconds',0)))
  text+=f"Independent stored-data review compute (including failed diagnostic attempts/reservation): {review_time:.3f}s; completed probe stages plus review plus60s reserve = {used+review_time+60:.3f}s, below3600s. Subsequent render/delivery timing stays in the ledger/transport sidecars.\n\n"
 text+=f"Protected {len(d['protected'])} tracked engine/controller, accepted, source and historical evidence files retain SHA256 identity. Historical attribution/v6 contract outputs and engineering P5 observer/action/metric streams are byte-identical to previous binaries. All160 raw/request hashes, deaths, shell attribution and failure/search/fork/rollout counters reconcile. No historical output was rewritten.\n\n"
 text+='''Evidence: [COMPACT.json](s4_collective_probe_v1/COMPACT.json), [SUMMARY.json](s4_collective_probe_v1/SUMMARY.json), [FIGHTS.json](s4_collective_probe_v1/FIGHTS.json), [ANALYSIS_VERIFICATION.json](s4_collective_probe_v1/ANALYSIS_VERIFICATION.json), [P5_SANITY.json](s4_collective_probe_v1/P5_SANITY.json), [P5_PARITY.json](s4_collective_probe_v1/P5_PARITY.json), [HISTORICAL_FIXTURES.json](s4_collective_probe_v1/HISTORICAL_FIXTURES.json). Raw compressed30Hz observer streams and requests stay local by SHA256/byte count in [RAW_FILES_LOCAL.json](s4_collective_probe_v1/RAW_FILES_LOCAL.json). No committed file exceeds45MB. Reproduce using build.py, check.py, run.py (single-use refuses existing raw), recount_final.py and render.py; bootstrap.py is the historical declaration helper; analyze.py/report.py are retained pre-fight drafts; recount.py is the preserved incorrect post-combat audit draft. stage_final.py selects recount_final.py/render.py. These are not rerun generators.

Stored audit correction: the original pre-fight1400×800 post-outside check was correct. A post-combat audit draft incorrectly used the1200×700 struct defaults; independent review caught that rules factories set the actual arena to1400×800. boundary_audit.py recounts all120 intervention streams using the native factory/codec/request chain, changing only post_outside_gun_ticks in37 fights. Every other measured field, aggregate and outcome is asserted identical. Drafts and before-fix summaries remain preserved. Original fight code pins stay byte-identical; no intervention, seed, threshold or fight changed. Final reproduction uses recount_final.py. [AUDIT_CORRECTION.json](s4_collective_probe_v1/AUDIT_CORRECTION.json) and [BOUNDARY_VERIFICATION.json](s4_collective_probe_v1/BOUNDARY_VERIFICATION.json) retain provenance.

Final independent results recheck: APPROVE_WITH_NOTES, no blocking findings; [RESULTS_RECHECK.md](s4_collective_probe_v1/RESULTS_RECHECK.md) records sampled scope and corrected counter verification.

Owner rechecks: [OWNER_RECHECK.md](s4_collective_probe_v1/OWNER_RECHECK.md), verbatim request and dispositions. Claude CLI loggedIn=false; separate Codex reviewer is the disclosed same-family fallback. PLAN_CURRENT remains unedited by this task. Delivery uses own explicit pathspecs with normal hooks, or an independently fetched verified bundle if .git is unwritable; adjacent DELIVERY_TRANSPORT.json records identity.
'''
 text=re.sub(r'\b(all|All|above|for|in|the|with|additional|static|used|derives|manufacture|exceeds|compressed|across|at)(?=\d)',r'\1 ',text)
 (CPP/'S4_COLLECTIVE_PROBE.md').write_text(text);write(HERE/'PRESERVATION.json',dict(status='PASS',protected_files=len(d['protected']),all_protected_hashes_match=True));print(json.dumps(dict(report_sha256=sha(CPP/'S4_COLLECTIVE_PROBE.md'),measured_awake_s=used)))
if __name__=='__main__':main()
