from pathlib import Path
p=Path('evidence/tactical_composition_demo/astelia_cpp/s4_development.py');s=p.read_text()
s=s.replace('    n = len(values)\n    if n < 2', '    values = list(values.values()) if isinstance(values,dict) else list(values)\n    n = len(values)\n    if n < 2')
s=s.replace("        return [self.cache[key] for key in keys]", "        return {json.dumps(b):self.cache[key] for b,key in zip(bs,keys)}")
s=s.replace("    if len(a)!=len(b):raise ValueError('pair length mismatch')\n    return [x-y for x,y in zip(a,b)]", "    if set(a)!=set(b):raise ValueError('pair keys mismatch')\n    return {key:a[key]-b[key] for key in sorted(a)}")
s=s.replace("values={i:[] for i in active}","values={i:{} for i in active}")
s=s.replace("values[i]+=bench.evaluate(arm,candidates[i],bs[previous:n],tuning=True)","values[i].update(bench.evaluate(arm,candidates[i],bs[previous:n],tuning=True))")
s=s.replace("paired(values[i],incumbent[:n])", "paired(values[i],{json.dumps(b):incumbent[json.dumps(b)] for b in bs[:n]})")
s=s.replace('statistics.mean(values[i])', 'stats(values[i])["mean"]')
s=s.replace("vals=[score for score,b in zip(scores,bs) if b[0]==opp and b[2]==setting]", "vals={json.dumps(b):scores[json.dumps(b)] for b in bs if b[0]==opp and b[2]==setting}")
s=s.replace("    spec=dict(spec,trace=True)", "    output.mkdir(parents=True,exist_ok=True)\n    spec=dict(spec,trace=True)")
s=s.replace("    n=len(values)\n    ds=sorted", "    values=list(values.values()) if isinstance(values,dict) else list(values)\n    n=len(values)\n    ds=sorted")
s=s.replace("allvals=[x for xs in strata for x in xs]", "allvals=[x for xs in strata for x in xs.values()]")
p.write_text(s)
