"""Render only stored descriptive summaries, without running combat."""
import json
from common import *
def num(x):return 'n/a' if x is None else f'{x:.2f}'
def main():
 s=json.loads((HERE/'SUMMARY.json').read_text());timing=json.loads((HERE/'RUN_TIMING.json').read_text());analysis=json.loads((HERE/'ANALYSIS_VERIFICATION.json').read_text());parity=json.loads((HERE/'PARITY.json').read_text())
 lines=['DONE — observer-only telemetry and 120 fresh development fights completed.','',
 'Descriptive 0g Track B4f diagnostic under decision 0031 and DESIGN_0G §19. Three selected stage-B arms: v6 attempt-2 resonator and morale, and v5 resonator. Ten independently declared common development seed clusters × two orientations × two heads × three arms; controlled team 0 throughout. No tuning, judging, registration, v7 design or milestone status change.', '',
 'An elimination win requires enemy survivors = 0, own survivors ≥ 1 and end time <150 s. A timeout is never a win. S is secondary. Orientations are paired within each seed cluster; the small sample is descriptive and receives no inferential or readiness verdict.','',
 '| Arm | Head | Elimination wins | Timeouts | Mean S | Guns destroyed | Own losses | Win time |',
 '|---|---|---:|---:|---:|---:|---:|---:|']
 for key,v in s.items():
  arm,head=key.split('|');lines.append(f"| {arm} | {head} | {v['elimination_wins']}/20 ({100*v['elimination_win_rate']:.0f}%) | {v['timeouts']}/20 | {v['mean_S']:+.2f} | {v['mean_guns_destroyed']:.2f}/10 | {v['mean_own_losses']:.2f}/50 | {num(v['elimination_time']['mean'])} s |")
 lines+=['','Who kills our units, by phase. Killer distances are centre-to-centre at damage application in native pixels, including moved or dead projectile sources. Friendly kills remain separate (team 0); they are never attributed to the enemy. Early = [0,20), middle = [20,60), late = [60,end]. The separate gun-only phase starts only when no enemy non-gun is alive in the preceding tick; it overlaps these time bins.','',
 '| Arm / head | Phase | Killer team:role | Own kills | Mean / median distance (px) |', '|---|---|---|---:|---:|']
 for key,v in s.items():
  for phase,b in v['own_deaths_by_phase_killer'].items():
   for role,x in b.items():lines.append(f"| {key.replace('|',' / ')} | {phase} | {role} | {x['kills']} | {num(x['distance']['mean'])} / {num(x['distance']['median'])} |")
 lines+=['','Enemy gun killers against novice. Maximum attackers within reach is the maximum number of distinct living own units simultaneously able to reach that gun in the preceding 3 s of tick snapshots, augmented by an exact lethal-application snapshot (retained separately). It includes own artillery and is range legality, not a count of units firing. Shelling elsewhere means that the gun launched a non-slow shell during that window while its current target ID differed from the killer; this identifies intended target at launch, not the recipient of splash.','',
 '| Arm | Killer team:role | Guns killed | Mean kill distance | Mean max in reach | Shelling other target | Mean killer angle |', '|---|---|---:|---:|---:|---:|---:|']
 for key,v in s.items():
  if not key.endswith('|novice'):continue
  for role,x in v['gun_killers'].items():lines.append(f"| {key.split('|')[0]} | {role} | {x['kills']} | {num(x['distance']['mean'])} px | {num(x['max_simultaneous']['mean'])} | {x['shelling_other']}/{x['kills']} | {num(x['killer_angle']['mean'])}° |")
 lines+=['','Approach angle is measured at the gun, relative to the axis toward the centroid of its other living guns: 0° is from the support side and 180° from the opposite side. It is null without a nonzero support axis. Per-gun rows include all reach-count samples/IDs, concurrent in-band counts, support cover, approach-angle distributions, launch records and recent damage sources. These observations do not establish a coordinated assault or that distraction caused the kill.','',
 'Every regular-head directed approach is recorded at the native movement boundary, including entering and dying in the same tick. An attempt crosses from outside the gun’s maximum centre range into its inclusive legal band with displacement toward the gun. Each unit/gun pair counts separately; an entry into overlapping bands is multiple pair attempts. Collision-only pushes and motion of the gun toward a stationary unit are outside this directed-movement definition. Each entry includes exact simultaneous in-band/in-reach IDs. The approach-start count uses distinct unit IDs starting toward the same gun in the previous 3 s, including dying entrants; maximum tracked approacher counts use surviving end-of-tick episodes. End-of-tick episodes distinguish death, gun death, leaving the band and termination censoring; later projectile kills are not automatically credited to a closed episode.','',
 '| Arm | Entries | Outcomes | Reached own range | Dealt gun damage during episode | Mean other-gun cover at entry | Mean max surviving tracked approachers / in reach; starts in 3s |', '|---|---:|---|---:|---:|---:|---:|']
 for key,v in s.items():
  if not key.endswith('|regular'):continue
  a=v['approaches'];lines.append(f"| {key.split('|')[0]} | {a['count']} | {json.dumps(a['outcomes'],sort_keys=True)} | {a['ever_reached_own_range']} | {a['ever_dealt_damage']} | {num(a['entry_cover']['mean'])} | {num(a['simultaneous_approachers']['mean'])} / {num(a['simultaneous_in_reach']['mean'])}; {num(a['approach_starts_previous_3s']['mean'])} |")
 lines+=['','Regular dodge and line observations. Dodge rows are actual successful returns from the unchanged shell/field `dodgeGoal` routine, not calls inferred from trajectory. Motion alignment compares the chosen dodge goal with the unit’s displacement during that same tick; collision and ability motion can contribute. Slot offsets and inter-gun spacing measure realized line geometry. Overlap counts measure geometric band overlap, not whether another gun fired or had a clear lane. These profile components are bundled: no ablation was run, so causal benefits of dodge, line, lead or abilities cannot be isolated.','',
 '| Arm / head | Enemy dodge decisions | Same-tick motion toward goal | Enemy slot fraction | Mean slot offset | Mean nearest-gun spacing | Mean overlapping other bands |', '|---|---:|---:|---:|---:|---:|---:|']
 for key,v in s.items():
  g=v['geometry'];lines.append(f"| {key.replace('|',' / ')} | {v['dodge_calls']} | {v['dodge_same_tick_motion_toward_goal']} | {num(g['enemy_has_slot']['mean'])} | {num(g['enemy_slot_offset']['mean'])} px | {num(g['gun_nearest_spacing']['mean'])} px | {num(g['gun_band_overlap_count']['mean'])} |")
 lines+=['','Telemetry proof and evidence. New `host_observer_v1`, versioned world/combat-rules/abilities copies, wrapper for the unchanged dodge function, and a separate build/dispatch preserve all historical v0–v6 source paths. Damage amount is the mitigated HP decrement; `dealt` caps it at remaining HP. Valid zero-amount damage calls are recorded. Killer is the source of the unique lethal application, including friendly fire. No observer calls RNG or policy code. The versioned copies are mechanically checked as the original files with only observation hooks added.','',
 f"Six full fights (all three arms, both heads) compare the historical v6 binary, observer off and observer on: {sum(c['bytes_compared'] for c in parity['cases']):,} legacy output bytes are identical, including both armies’ per-tick actions, states, terminal summaries and work metrics. The 18 engineering executions use separately declared engineering entropy, not the diagnostic clusters. Both original historical/attribution and v6 controller fixture outputs are byte-identical. All 120 diagnostic fights have zero controller failures and no forks, search or rollouts. Every tick is analyzed, raw hashes match, deaths and gun removals reconcile with terminal counts, and cross-team/friendly damage totals reconcile with native accounting.",'',
 f"Combat elapsed / awake: {timing['elapsed_seconds']:.3f} / {timing['awake_seconds']:.3f} s. Stored-only analysis elapsed / awake: {analysis['elapsed_seconds']:.3f} / {analysis['awake_seconds']:.3f} s. Build/test timings are in `s4_gun_assault_20261007/CHECK_TIMING.json`. Runs use `/usr/bin/caffeinate -i -s`. Pre-run compute projection was 15–30 minutes; the combat cap is 20 minutes and a >1-hour projection stops work. No code was edited during runs.",'',
 'Evidence: [summary](s4_gun_assault_20261007/SUMMARY.json), [allocation and native outcomes](s4_gun_assault_20261007/FIGHTS.json), [inputs and exact knobs](s4_gun_assault_20261007/INPUT_IDENTITY.json), [parity](s4_gun_assault_20261007/PARITY.json), [historical contracts](s4_gun_assault_20261007/HISTORICAL_CONTRACTS.json), [all-tick verification](s4_gun_assault_20261007/ANALYSIS_VERIFICATION.json). Each `*_summary.json` contains every own death, enemy gun death and regular directed approach with timestamps and geometry. Scripts are adjacent. Raw traces and entropy remain local, identified by size and SHA256 in [raw inventory](s4_gun_assault_20261007/RAW_FILES_LOCAL.json); raw files are excluded from delivery regardless of size, including any over 45 MB.','',
 'Owner recheck request, verbatim:','',
 "> Recheck what you did please, check if it is the best we can do, we want 10 out of 10 or above 9 - it's fine to break the things or fully rework. Check for issues, conflicts, gaps.",'',
 'Recheck/disposition: see [source recheck](s4_gun_assault_20261007/SOURCE_RECHECK.md), [owner report recheck](s4_gun_assault_20261007/OWNER_RECHECK.md) and [local plan/disposition](s4_gun_assault_20261007/PLAN_AND_REVIEW.md). Available independent Codex reviewer is an explicitly disclosed same-family fallback, not cross-family acceptance. `docs/PLAN_CURRENT.md` is not edited, as requested. Delivery uses normal hooks and an independently verified scoped bundle if main `.git` is read-only; [transport sidecar](s4_gun_assault_20261007/DELIVERY_TRANSPORT.json) records identities.']
 (CPP/'S4_GUN_ASSAULT_DIAGNOSTIC.md').write_text('\n'.join(lines)+'\n')
if __name__=='__main__':main()
