#include "native/api.h"
#include <iostream>
using namespace astelia;
void require(bool b,const char* message){if(!b)throw std::runtime_error(message);}
int main(){try{auto config=gameConfig();config.army={2,4,2};config.width=650;config.duration=.2;
  auto w=create(config);require(monsters(w).size()==8&&hunters(w).size()==8,"public team API incorrect");
  auto branch=fork(w);branch.world().dt=.1;branch.world().duration=.3;run(branch.world());require(w.time==0&&done(branch.world()),"public fork/run aliases parent");
  const auto result=run(w);require(done(w)&&result.t==w.time&&result.total==result.melee+result.ranged+result.artillery,"public run/summary incorrect");
  const auto profile=buildProfile(config,0);require(profile.brain==config.brains[0],"profile API changed brain");
  auto abilityConfig=sandboxConfig();abilityConfig.army={0,0,0};abilityConfig.abilities=true;auto aw=create(abilityConfig);const auto fighter=aw.add(0,Role::Melee,{100,100}),archer=aw.add(1,Role::Ranged,{250,100});require(triggerAbility(aw,fighter.slot,Ability::Shield),"shield trigger failed");aw.damage(archer,fighter,20);require(aw.stats.abilities[0][size_t(Ability::Shield)].uses==1&&aw.stats.abilities[0][size_t(Ability::Shield)].blocked==16,"ability telemetry omitted");aw.note("controller event");require(aw.events.back().text=="controller event","event API omitted");auto ac=fork(aw);require(ac.world().events.empty()&&ac.world().stats.abilities[0][size_t(Ability::Shield)].uses==0,"branch did not reset observation telemetry");
  aw.abilities[aw.state[fighter.slot].ability].manual=true;aw.abilities[aw.state[fighter.slot].ability].lock=0;require(ready(aw,fighter,Ability::Charge)&&!triggerAbility(aw,fighter.slot,Ability::Charge,archer)&&triggerAbility(aw,fighter,Ability::Charge,archer),"public manual ability control lost by-hand policy");
  require(enemyOf("storm").brain==Brain::Storm&&enemyOf("gamepack").brain==Brain::Gamepack&&enemyOf("column").formation.shape==Shape::Column,"enemy resolution wrong");
  auto names=drawOpponents(20261005,100,true);require(names.size()==opponentPool().size(),"draw exhausted wrong pool");for(size_t i=0;i<names.size();++i)for(size_t j=0;j<i;++j)require(names[i]!=names[j],"pool draw repeats");
  auto geometryConfig=sandboxConfig();geometryConfig.army={0,0,0};auto gw=create(geometryConfig);const auto from=gw.add(0,Role::Ranged,{100,100}),near=gw.add(1,Role::Ranged,{110,100}),other=gw.add(1,Role::Ranged,{115,100});require(nearest(gw,from.slot)==near,"live geometry wrong initial nearest");gw.move(near.slot,{119,100},.2);require(nearest(gw,from.slot)==other,"same-cell movement left nearest query stale");gw.damage(from,near,50);require(nearest(gw,from.slot,false,false,INFINITY,80)==other,"live geometry ignored authoritative HP filter");gw.damage(from,other,1000);require(nearest(gw,from.slot)==near,"live geometry retained dead candidate");gw.reclaim();const auto replacement=gw.add(1,Role::Ranged,{114,100});require(replacement.slot==other.slot&&replacement.generation!=other.generation&&nearest(gw,from.slot)==replacement,"live geometry retained reclaimed generation");
  config.lookahead[0].plans={Plan::Hold};auto net=std::make_shared<Network>();net->inputs=34;net->hidden=1;net->outputs=1;net->w1.assign(34,0);net->b1={0};net->w2={0};net->b2={0};config.lookahead[1].plans={Plan::Hold};setNet(config,net);require(config.lookahead[0].network==net,"setNet discarded weights");setNet(config,nullptr);require(!config.lookahead[0].network&&config.lookahead[0].netPrune==0,"network disable kept pruning");
  std::cout<<"native API contracts passed\n";return 0;
}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
