"""Synthetic-only economy verification: no native steps, pilot entropy, assays or process enumeration."""
import ast
from collections import Counter, deque
import copy
import hashlib
from functools import lru_cache
import io
import json
import math
from pathlib import Path
import re
import sys
import subprocess
import tempfile
from types import SimpleNamespace as NS, ModuleType
import unittest
from unittest.mock import patch

import economy_kernel as K
import economy_telemetry as T
import execute_economy_plan as S
import write_economy_report as R
from service_graph import classify

HERE=Path(__file__).resolve().parent
SITES=[(4*math.cos(s*math.pi/4),4*math.sin(s*math.pi/4)) for s in range(8)]
PREFIX='evidence.tactical_composition_demo.growing_shapes.medium.'


@lru_cache(maxsize=1)
def rd3_source():
    # Read committed source, without requiring an unbundled local RD3 worktree.
    source=subprocess.check_output(['git','show','fd21826:evidence/tactical_composition_demo/growing_shapes/medium/rev7_design.py'],cwd=S.ROOT,text=True)
    source=K.replace_once(source,"            e=min(eligible,key=lambda e:(measured[e.id] or 0.,e.id));self.remove(e.id,'D3',lock=measured[e.id])\n",
                          (HERE/'kernel_builder/ranked_d3_body.txt').read_text())
    source+='\n# Scratch-only service geometry, independent of the observer.\nfrom service_graph import service_snapshot, ranked_choice\n'
    expected=json.loads((HERE/'kernel_builder/RD3_BUILD.json').read_text())['design_sha256']
    if hashlib.sha256(source.encode()).hexdigest()!=expected:raise AssertionError('committed RD3 reconstruction mismatch')
    return source


def tree(variant):
    return ast.parse(rd3_source() if variant=='RD3' else (HERE/f'kernel_builder/_worktrees/{variant}/evidence/tactical_composition_demo/growing_shapes/medium/rev7_design.py').read_text())


def method(variant,name):
    cls=next(n for n in tree(variant).body if isinstance(n,ast.ClassDef) and n.name=='Rev7Medium')
    fn=next(n for n in cls.body if isinstance(n,ast.FunctionDef) and n.name==name)
    scope=dict(math=math,deque=deque,deepcopy=copy.deepcopy,retract_fronts=K.retract_fronts,
               update_stall=K.update_stall,thin_redundant=K.thin_redundant)
    exec(compile(ast.Module(body=[fn],type_ignores=[]),'actual-economy-method','exec'),scope)
    return scope[name]


def pure_graph_module():
    names={'reach','Influence','geometric_graph','geometry'}
    nodes=[n for n in tree('RD3').body if isinstance(n,(ast.ClassDef,ast.FunctionDef)) and n.name in names]
    # Remove dataclass decorator; geometry and graph need no native constructor.
    for n in nodes:
        if isinstance(n,ast.ClassDef): n.decorator_list=[]
    scope=dict(math=math,PHASE_SCALE=32.,STRONG_LINK_RATE=.5)
    # Influence is a record; retain the actual reach/graph/path logic with a
    # dataclass generated by applying the decorator after AST compilation.
    for n in nodes:
        if isinstance(n,ast.ClassDef):
            n.decorator_list=[ast.Name(id='dataclass',ctx=ast.Load())]
    from dataclasses import dataclass
    scope['dataclass']=dataclass
    module=ModuleType(PREFIX+'rev7_design');module.__dict__.update(scope)
    exec(compile(ast.fix_missing_locations(ast.Module(body=nodes,type_ignores=[])),'actual-pure-geometry','exec'),module.__dict__)
    return module


def snapshot(ids=(0,1,2,3,4),incoming=None,roots=None,positions=None):
    ids=list(ids);incoming=incoming or {i:set() for i in ids}
    roots=roots or {s:{1} if s==0 and 1 in ids else set() for s in range(8)}
    out,routes,lost,classes=classify(ids,incoming,roots,{0} if 0 in ids else set())
    return dict(ids=ids,incoming=incoming,outgoing=out,roots=roots,outputs={0} if 0 in ids else set(),
                routes=routes,lost=lost,classes=classes,positions=positions or {i:(float(i),0.) for i in ids},
                served={s for s,p in routes.items() if p},eligible=[i for i in ids if i!=0],
                held={i:list(incoming[i]) for i in ids},scale=32.,fragment=dict(rooted=True,screened=False))


def medium():
    return NS(economy_stall=dict.fromkeys(range(8),0.),economy_deficit=dict.fromkeys(range(8),math.inf),
              step_index=1000,birth_steps=dict.fromkeys(range(20),0),emit=lambda *a,**k:None)


def sample_row(variant='ECOF',start='i',key=0):
    points=[dict(t=t,cost=0.,classes={c:dict(elements=0,pair_cost=0.,cost=0.) for c in R.CLASSES}) for t in range(5,801,5)]
    return dict(variant=variant,start=start,keyset=key,observer='on',summary=dict(assay=dict(A=.3,B=.3,E=[.5]*8)),
                telemetry=dict(sites={str(s):dict(active_steps=100,active_served_steps=20,served_fraction_active=.2) for s in range(8)},
                    outage_count=0,break_causes={},d3_removals_by_class={},forced_service_cuts=[],outages=[],non_repair_causes={},
                    economy_removals=[],prospective_checks=[],prospective_trials=[],mass_samples=points,
                    initial_cost_refusals=[],stall_samples=[],no_front=[]))


def fixture_observer(outages=()):
    o=object.__new__(T.Observer);o.live=NS(step_index=8000);o.stream=io.StringIO()
    o.previous=dict(served=set(),routes={});o.outages=list(outages);o.open={x['site']:x for x in outages}
    for name in ('removals','decisions','forced','requests','terminals','growth_checks','recycles','initial_cost_refusals','prospective_checks','prospective_trials','stall_samples','no_front'):
        setattr(o,name,[])
    o.mass_samples={};o.steps=0;o.active=Counter();o.active_served=Counter();o.served=Counter();o.degree=Counter()
    return o


def outage(site=0):
    return dict(site=site,start=0.,end=None,duration=None,censored=False,break_cause='X',
                break_candidates=[],break_detail=[],previous_route=[1,0],restored_route=None,route_reuse=None,
                initial_gap=3.,samples=[dict(t=0.,gap=3.,rootless_screened=False)],requests=[],terminals=[],internal_route_events=[])


class KernelChecks(unittest.TestCase):
    def test_directed_deficit_uses_all_site_front_back_not_spring_gap(self):
        s=snapshot(incoming={0:{4},1:set(),2:{1},3:{2},4:set()})
        s['positions']={0:(7.,0.),1:(0.,0.),2:(2.,0.),3:(4.,0.),4:(5.,0.)}
        s['gaps']={0:0.} # Deliberately incompatible spring-gap observer value.
        self.assertEqual(K.deficit(s,0),1.)
        self.assertTrue(math.isinf(K.deficit(s,7)))
        s['outputs']=set();self.assertTrue(math.isinf(K.deficit(s,0)))

    def test_stall_initial_progress_tolerance_rootloss_idle_and_served(self):
        m=medium();s=snapshot()
        values=[3.,3.,3.-.5e-9,3.-2e-9,math.inf,math.inf,4.,4.]
        expected=[0.,20.,40.,0.,0.,0.,0.,20.]
        for now,want in zip(values,expected):
            with patch.object(K,'service_snapshot',return_value=s),patch.object(K,'deficit',return_value=now):
                K.update_stall(m)
            self.assertEqual(m.economy_stall[0],want)
        # Nonzero rootless clocks pause (no repeated-infinity reset); idle sites evolve.
        m.economy_stall[0]=40.;m.economy_deficit[0]=math.inf
        with patch.object(K,'service_snapshot',return_value=s),patch.object(K,'deficit',return_value=math.inf):K.update_stall(m)
        self.assertEqual(m.economy_stall[0],40.)
        s['served']={7}
        with patch.object(K,'service_snapshot',return_value=s),patch.object(K,'deficit',return_value=4.):K.update_stall(m)
        self.assertEqual(m.economy_stall[7],0.)

    def test_front_excludes_every_sites_routes_and_preserves_all_roots_and_entire_tip(self):
        incoming={0:{5},1:set(),2:{1},3:{1},4:{1},5:{6},6:set()}
        roots={s:{1} if s==0 else {6} if s==7 else set() for s in range(8)}
        s=snapshot(ids=range(7),incoming=incoming,roots=roots,
                   positions={0:(0.,0.),1:(.1,0.),2:(3.,0.),3:(2.,0.),4:(4.,0.),5:(.5,0.),6:(1.,0.)})
        self.assertEqual(K.front_ids(s,0),{1,2,3,4});self.assertNotIn(5,K.front_ids(s,0))
        m=medium();m.economy_stall[0]=60.;removed=[]
        m.remove=lambda i,r,**kw:removed.append((i,r,kw))
        # Root1 is entire-front tip. Do not recompute tip after excluding roots,
        # which would incorrectly protect donor3. Rank must select donor3.
        with patch.object(K,'service_snapshot',return_value=s):K.retract_fronts(m,{i:.1 if i==3 else .9 for i in s['ids']})
        self.assertEqual(removed[0][:2],(3,'D5f'));self.assertEqual(removed[0][2]['tip'],1)
        self.assertEqual(m.economy_stall[0],0.)

    def test_age200_lock_tie_tip_tie_shared_front_recomputed_and_no_donor_reset(self):
        m=medium();m.step_index=300;m.birth_steps[2]=100;m.birth_steps[3]=101;m.birth_steps[4]=101
        s=snapshot(incoming={0:set(),1:set(),2:{1},3:{1},4:{1}},
                   positions={0:(0.,0.),1:(5.,0.),2:(4.,0.),3:(3.,0.),4:(3.,0.)})
        s['roots'][1]={1};s['outgoing'][1]={2,3,4}
        m.economy_stall[0]=m.economy_stall[1]=60.;removed=[];events=[]
        m.emit=lambda *a,**k:events.append((a,k))
        def remove(i,r,**kw):
            removed.append(i);s['outgoing'][1].remove(i);s['ids'].remove(i)
        m.remove=remove
        with patch.object(K,'service_snapshot',return_value=s) as call:
            K.retract_fronts(m,{1:0.,2:0.,3:0.,4:.9})
        self.assertEqual(removed,[2]);self.assertEqual(call.call_count,2)
        self.assertEqual(m.economy_stall[1],0.)
        self.assertTrue(any(a==('D5f_none',) for a,k in events))
        s['outputs']=set();m.economy_stall[0]=60.
        with patch.object(K,'service_snapshot',return_value=s):K.retract_fronts(m,{})
        self.assertEqual(removed,[2]);self.assertEqual(m.economy_stall[0],60.)

    def test_actual_growth_order_single_change_and_end_clock(self):
        for variant in S.ARMS:
            order=[];m=medium();m.frozen=False;m.native=NS(elements=[],__len__=lambda:0)
            class Native:
                elements=[]
                def __len__(self):return 0
                def cut_off(self,i):return 0.
            m.native=Native();m.lock=lambda i:0.;m.cost=lambda:0.;m.death={};m.pointer=0
            m.b_out=lambda blocked:order.append('B-out') or []
            m.b_path=lambda blocked:order.append('B-path') or []
            m.b1=lambda blocked:order.append('B1') or []
            m.emit=lambda *a,**k:order.append(a[0])
            fn=method(variant,'growth')
            fn.__globals__.update(retract_fronts=lambda m,locks:order.append('D5f'),
                                  update_stall=lambda m:order.append('clock'),
                                  thin_redundant=lambda m,locks:order.append('D5r'))
            fn(m)
            self.assertEqual(order,['D5f','B-out','B-path','B1','clock','growth_check'] if variant=='ECOF' else ['D5r','B-out','B-path','B1','growth_check'])
        # A removal reset does not suppress the same-check growth-end accumulation.
        m=medium();m.economy_stall[0]=0.;m.economy_deficit[0]=3.
        with patch.object(K,'service_snapshot',return_value=snapshot()),patch.object(K,'deficit',return_value=3.):K.update_stall(m)
        self.assertEqual(m.economy_stall[0],20.)

    def test_actual_clone_deep_copies_kernel_history(self):
        for variant in S.ARMS:
            m=type('FakeMedium',(),{})();m.__dict__.update(medium().__dict__);m.native=NS(clone=lambda:NS());m.events=[];m.frames=deque([],maxlen=601);m.diagnostics=[]
            c=method(variant,'clone')(m);c.economy_stall[0]=99.;c.economy_deficit[0]=0.
            self.assertEqual(m.economy_stall[0],0.);self.assertTrue(math.isinf(m.economy_deficit[0]))

    def test_patches_match_built_rd3_and_unmodified_dispatcher(self):
        rd3=rd3_source()
        for variant in S.ARMS:
            built=(HERE/f'kernel_builder/_worktrees/{variant}/evidence/tactical_composition_demo/growing_shapes/medium/rev7_design.py').read_text()
            self.assertEqual(built,K.apply_variant(rd3,variant))
            receipt=json.loads((HERE/f'kernel_builder/{variant}_BUILD.json').read_text())
            self.assertEqual(receipt['rd3_parent_design_sha256'],hashlib.sha256(rd3.encode()).hexdigest())
            for name in ('b_path','_b_path_attempt','b1','timers','output_first','feasible'):
                self.assertEqual(ast.dump(next(n for n in next(c for c in tree(variant).body if isinstance(c,ast.ClassDef) and c.name=='Rev7Medium').body if isinstance(n,ast.FunctionDef) and n.name==name)),
                                 ast.dump(next(n for n in next(c for c in tree('RD3').body if isinstance(c,ast.ClassDef) and c.name=='Rev7Medium').body if isinstance(n,ast.FunctionDef) and n.name==name)))
        with self.assertRaises(ValueError):K.apply_variant('wrong','ECOF')

    def test_builder_reproduction_rejects_identity_drift(self):
        from kernel_builder.build_economy_kernels import compare_reproduction
        expected=json.loads((HERE/'kernel_builder/ECOF_BUILD.json').read_text())
        compare_reproduction(expected,copy.deepcopy(expected))
        for field in ('economy_kernel_sha256','design_sha256','spec_sha256','rd3_parent_design_sha256'):
            actual=copy.deepcopy(expected);actual[field]='changed'
            with self.assertRaises(RuntimeError):compare_reproduction(expected,actual)
        for section in ('build','world_build'):
            actual=copy.deepcopy(expected);actual[section]['binary_sha256']='changed'
            with self.assertRaises(RuntimeError):compare_reproduction(expected,actual)

    def test_prospective_pure_graph_reads_all_sites_rewires_and_preserves_order(self):
        D=pure_graph_module();physical=ModuleType(PREFIX+'design_0h');physical.SITES=SITES
        es=[NS(id=0,x=0.,y=0.,silent=False),NS(id=9,x=1.1,y=0.,silent=False),NS(id=1,x=-1.1,y=0.,silent=False),NS(id=2,x=0.,y=1.,silent=False)]
        m=NS(native=NS(elements=es,role=lambda i:'output' if i==0 else 'element',gain=lambda i:1.,
                       params=NS(k=2,radius=3.,K=1.),policy=lambda:(32.,False,True)),drives=[])
        before=copy.deepcopy(m.native.elements);calls=[]
        actual=D.geometric_graph
        D.geometric_graph=lambda *a,**k:calls.append((a,k)) or actual(*a,**k)
        with patch.dict(sys.modules,{PREFIX+'rev7_design':D,PREFIX+'design_0h':physical}):
            served=K.prospective_service(m,2)
        self.assertEqual([(e.id,e.x,e.y) for e in es],[(e.id,e.x,e.y) for e in before])
        self.assertEqual([r[0] for r in calls[0][0][0]],[0,9,1])
        self.assertEqual([d[0] for d in calls[0][0][1]],list(range(8)))
        self.assertTrue(all(d[3:]==(1.,3.) for d in calls[0][0][1]))
        self.assertEqual(served,{0,4})
        # Full held degree, not only the strong subset, controls edge strength.
        elements=[(0,0.,0.,'output',1.,False),(1,1.,0.,'element',1.,False),(2,0.,2.9,'element',1.,False)]
        g=actual(elements,[],2,3.,strong=True,phase_scale=2.,K=1.)
        self.assertNotIn(1,g.incoming[0])
        g=actual(elements[:-1],[],2,3.,strong=True,phase_scale=2.,K=1.)
        self.assertIn(1,g.incoming[0])

    def test_ecor_rank_all_idle_service_first_pass_denominators_and_56(self):
        m=medium();m.cost=lambda:56.1;records=[];removed=[]
        m.emit=lambda rule,ids=(),**kw:records.append(dict(rule=rule,ids=ids,**kw))
        m.remove=lambda i,r,**kw:removed.append((i,r,kw))
        s=snapshot();s.update(classes={0:'redundant',1:'critical',2:'redundant',3:'redundant',4:'non-service'},served={0,7})
        with patch.object(K,'service_snapshot',return_value=s),patch.object(K,'prospective_service',side_effect=[{0},{0,7}]):
            K.thin_redundant(m,{0:0,1:0,2:.1,3:.2,4:0})
        self.assertEqual([x[0] for x in removed],[3])
        check=records[-1];self.assertEqual((check['trials'],check['failures'],check['result']),(2,1,'removed'))
        self.assertEqual(records[0]['lost_sites'],[7])
        m.cost=lambda:56.
        with patch.object(K,'service_snapshot',side_effect=AssertionError('no trigger')):K.thin_redundant(m,{})
        self.assertEqual(records[-1]['result'],'below_trigger')
        s['eligible']=[];m.cost=lambda:60.
        with patch.object(K,'service_snapshot',return_value=s):K.thin_redundant(m,{})
        self.assertEqual(records[-1]['result'],'no_candidate')
        s['eligible']=[2]
        with patch.object(K,'service_snapshot',return_value=s),patch.object(K,'prospective_service',return_value=set()):K.thin_redundant(m,{2:0})
        self.assertEqual(records[-1]['result'],'no_passing_candidate');self.assertEqual(len(removed),1)


class ObserverChecks(unittest.TestCase):
    def birth(self):return dict(rule='birth_terminal',cost=1.,values=dict(request=0,birth_rule='B1',site=0,outcome='accepted'))

    def test_wrappers_exclude_clones_from_observer_digest_and_first_refusal(self):
        s=snapshot()
        s.update(active={0},active_served=set(),degree={i:0 for i in s['ids']},
                 selected={i:[] for i in s['ids']},pairs=set(),gaps=dict.fromkeys(range(8),None),
                 fragment=dict(ids=[0],size=1,rooted=False,screened=False))
        digests=[]
        for enabled in (True,False):
            class FakeMedium:
                def integrate(self,drives):self.step_index+=1;return {}
                def remove(self,id,rule,**values):pass
                def growth(self,**kwargs):pass
                def emit(self,rule,ids=(),**values):self.events.append(dict(rule=rule,ids=ids,values=values,cost=4.))
                def feasible(self,point,phase):return 'cost'
            def make():
                m=FakeMedium();m.__dict__.update(medium().__dict__)
                m.events=[];m.step_index=0;m.cost=lambda:4.;m.death={};m.novelty={};m.pointer=0;m.request_counter=0;m.growth_rng=None
                m.native=NS(save=lambda:b'fake-state',elements=[NS(as_dict=lambda i=i:dict(id=i,x=float(i),y=0.)) for i in s['ids']])
                return m
            live=make();clone=make();P=NS(LIVE=[live])
            class FakeRun:
                def __init__(self,m):self.medium=m
                def step_boundary(self):return self.medium.integrate([])
            D=ModuleType(PREFIX+'rev7_design');D.Rev7Medium=FakeMedium
            with tempfile.TemporaryDirectory(dir=HERE/'_local') as tmp,patch.dict(sys.modules,{PREFIX+'rev7_design':D}),patch.object(T,'service_snapshot',return_value=s),patch.object(T,'candidate_cost',return_value=66.):
                digest=hashlib.sha256()
                holder=T.install_observer(P,FakeRun,'ECOF',Path(tmp)/'trace.gz',digest,enabled)
                FakeRun(live).step_boundary();before=digest.hexdigest()
                obs_before=holder[0].steps if holder[0] else 0
                FakeRun(clone).step_boundary();clone.feasible((1.,2.),0.)
                self.assertEqual(digest.hexdigest(),before)
                self.assertEqual(holder[0].steps if holder[0] else 0,obs_before)
                live.feasible((1.,2.),0.)
                if holder[0]:
                    self.assertEqual(holder[0].initial_cost_refusals,[dict(t=.1,cost=4.,candidate_cost=66.,point=[1.,2.],outcome='cost',source='candidate_feasibility')])
                    holder[0].finish()
                digests.append(digest.hexdigest())
        self.assertEqual(digests[0],digests[1])

    def test_restoring_B_excluded_and_nonrepair_B_gap_decrease(self):
        for gap,want in ((3.,True),(2.,False)):
            o=fixture_observer([outage()]);s=dict(served=set(),routes={},gaps={0:gap},fragment=dict(rooted=True,screened=False))
            with patch.object(T,'service_snapshot',return_value=s):o.event(self.birth())
            s.update(served={0},routes={0:[1,0]},gaps={0:0.})
            with patch.object(T,'service_snapshot',return_value=s):o.event(self.birth())
            r=o.finish();self.assertEqual('B' in r['outages'][0]['non_repair_labels'],want)
            self.assertEqual(r['outages'][0]['restoration_evidence'][0]['weight'],0)
        o=fixture_observer([outage()])
        with patch.object(T,'service_snapshot',return_value=s):o.event(self.birth())
        self.assertNotIn('B',o.finish()['outages'][0]['non_repair_labels'])

    def test_D5_rewiring_loss_has_removal_candidate_even_if_fixed_graph_redundant(self):
        before=snapshot(incoming={0:{2,3},1:set(),2:{1},3:{1},4:set()})
        self.assertEqual(before['lost'][2],[])
        after=copy.deepcopy(before);after['served']=set();after['positions'].pop(2)
        after['incoming'][0]=set();after['held'][0]=[3,4]
        label,candidates,detail=T.break_labels(before,after,0,dict(id=2,rule='D5r'))
        self.assertIn('D5r',candidates)

    def test_mass_allocation_pairs_O_free_splits_front_and_orphan(self):
        s=snapshot(incoming={0:{2},1:set(),2:{1},3:{1},4:set()})
        s['held']={0:[2],1:[2,3],2:[0,1],3:[1,4],4:[3]}
        row=T.mass_allocation(s,20.)
        self.assertEqual(row['cost'],4.3)
        self.assertEqual(row['classes']['front']['elements'],1)
        self.assertEqual(row['classes']['orphan']['elements'],1)
        self.assertAlmostEqual(row['classes']['orphan']['pair_cost'],.05)
        self.assertAlmostEqual(sum(x['cost'] for x in row['classes'].values()),row['cost'])

    def test_economy_event_denominators_and_no_front_are_retained(self):
        o=fixture_observer();o.event(dict(rule='economy_prospective_check',ids=[],cost=60.,values=dict(trials=2,failures=1)))
        o.event(dict(rule='D5f_none',ids=[],cost=60.,values=dict(site=7,reason='no_eligible_front')))
        self.assertEqual(o.prospective_checks[0]['failures'],1);self.assertEqual(o.no_front[0]['site'],7)


class SchedulerChecks(unittest.TestCase):
    def test_anchored_repository_only_pgrep_exclusion(self):
        root=str(S.ROOT)
        for command,want in [('/usr/bin/python3 '+root+'/evidence/tactical_composition_demo/astelia_cpp/s4_spacing_probe_v1/run.py',True),
             (root+'/.venv/bin/python -u '+root+'/evidence/tactical_composition_demo/astelia_cpp/s4_escort_probe_v1/execute.py',True),
             (root+'/evidence/tactical_composition_demo/astelia_cpp/build/astelia_native --jsonl',True),
             ('/other/ai_RPG_test/evidence/astelia_native',False),
             ('/usr/bin/python3 /other/ai_RPG_test/evidence/tactical_composition_demo/astelia_cpp/s4_spacing_probe_v1/run.py',False),
             ('/usr/bin/pgrep -fl '+S.PATTERN,False),('pgrep -fl '+S.PATTERN,False),
             ('/usr/bin/python3 '+root+'/unrelated/run.py',False)]:
            self.assertEqual(bool(re.search(S.PATTERN,command)),want,command)

    def test_process_failure_no_real_listing(self):
        with patch.object(S.subprocess,'run',return_value=NS(returncode=3,stderr='denied',stdout='')):self.assertEqual(S.process_check()['status'],'PROCESS_ACCESS_BLOCKED')
        with patch.object(S.subprocess,'run',side_effect=OSError('denied')):self.assertEqual(S.process_check()['status'],'PROCESS_ACCESS_BLOCKED')
        with patch.object(S.subprocess,'run',return_value=NS(returncode=1,stderr='',stdout='')):self.assertEqual(S.process_check()['status'],'CLEAR')

    def test_plan_projection_pairs_and_identity(self):
        self.assertEqual(S.CAP,3600);self.assertEqual(S.MAX_WORKERS,10)
        self.assertEqual(len(S.JOBS),22);self.assertEqual(len(set(S.JOBS)),22)
        self.assertGreater(S.projection(22,10,S.estimate_seconds([])),3600)
        rows=[dict(variant=v,start='i',keyset=0,observer=o,summary={'x':1},state_trajectory_sha256='a'*64,clone_isolation='PASS') for v in S.ARMS for o in ('on','off')]
        self.assertEqual(S.integrity(rows),dict.fromkeys(S.ARMS,'PASS'))
        rows[-1]['summary']={'x':2};self.assertEqual(S.integrity(rows)['ECOR'],'FAIL')

    def test_build_identity_all_dependencies_pinned_exclusions_and_preservation(self):
        for v in S.ARMS:S.validate_build(v)
        pins=S.code_hashes();S.check_frozen(pins)
        self.assertTrue(any(p.endswith('/runner/rev7_run.py') for p in pins))
        self.assertIn(str(HERE/'write_economy_report.py'),pins)
        self.assertFalse(any(Path(p).name in ('PLAN_CURRENT.md','DESIGN_0G.md','DESIGN_0H_REV7.md') for p in pins))
        baseline=json.loads((HERE/'ECONOMY_PRESERVATION.json').read_text())
        for p,digest in baseline['files'].items():self.assertEqual(S.sha(S.ROOT/p),digest,p)

    def test_resume_raw_corruption_code_drift_incomplete_never_relaunch(self):
        with tempfile.TemporaryDirectory(dir=HERE/'_local') as tmp:
            out=Path(tmp);job=('ECOF','i',0,'on');name=S.job_name(job);raw=out/(name+'.legacy.json.gz');raw.write_bytes(b'fixture')
            (out/'kernel_builder').mkdir();(out/'kernel_builder/ECOF_BUILD.json').write_text(json.dumps(dict(build=dict(binary_sha256='b'*64))))
            row=dict(variant='ECOF',start='i',keyset=0,observer='on',summary=dict(steps=8000,last_t=800.),
                     code_hashes={'fixture':'hash'},clone_isolation='PASS',cpu_seconds=1.,elapsed_seconds=2.,state_trajectory_sha256='a'*64,
                     binary_sha256='b'*64,telemetry=dict(steps=8000,label_revision='AMENDMENT_1_ECONOMY'),
                     raw_traces=[dict(path=raw.name,bytes=7,sha256=S.sha(raw))])
            path=out/(name+'.summary.json');path.write_text(json.dumps(row))
            with patch.object(S,'OUT',out):
                self.assertEqual(S.load_completed(job,row['code_hashes'],out),row)
                with self.assertRaises(RuntimeError):S.load_completed(job,{'drift':'x'},out)
                raw.write_bytes(b'corrupt')
                with self.assertRaises(RuntimeError):S.load_completed(job,row['code_hashes'],out)
                path.unlink();(out/(name+'.started')).write_text('started')
                with self.assertRaises(RuntimeError):S.load_completed(job,row['code_hashes'],out)

    def test_main_projection_stop_before_any_worker_and_process_access_denied(self):
        for status in ('CLEAR','PROCESS_ACCESS_BLOCKED'):
            with tempfile.TemporaryDirectory(dir=HERE/'_local') as tmp:
                out=Path(tmp);local=out/'local';local.mkdir()
                with patch.object(S,'OUT',out),patch.object(S,'LOCAL',local),patch.object(S,'process_check',return_value=dict(status=status)),patch.object(S,'code_hashes',return_value={}),patch.object(S,'load_completed',return_value=None),patch.object(S,'estimate_seconds',return_value=2000.),patch.object(S,'worker',side_effect=AssertionError('must not launch')),patch.object(S.subprocess,'Popen',side_effect=AssertionError('must not launch')):
                    self.assertEqual(S.main(),2)
                d=json.loads((out/'ECONOMY_RUN_SUMMARIES.json').read_text())
                self.assertEqual(d['status'],'NOT_RUN');self.assertEqual(d['runs'],[])
                self.assertIn('stop_reason',d['timing']);self.assertFalse((local/'SCHEDULER.lock').exists())

    def test_main_reuses_all_completed_slots_without_worker_or_rerun(self):
        rows={j:dict(variant=j[0],start=j[1],keyset=j[2],observer=j[3],summary={'same':1},
                     state_trajectory_sha256='a'*64,clone_isolation='PASS',cpu_seconds=1.,elapsed_seconds=1.) for j in S.JOBS}
        awake=NS(terminate=lambda:None,wait=lambda:None)
        with tempfile.TemporaryDirectory(dir=HERE/'_local') as tmp:
            out=Path(tmp);local=out/'local';local.mkdir()
            with patch.object(S,'OUT',out),patch.object(S,'LOCAL',local),patch.object(S,'process_check',return_value=dict(status='CLEAR')),patch.object(S,'code_hashes',return_value={}),patch.object(S,'load_completed',side_effect=lambda j,b:rows[j]),patch.object(S,'estimate_seconds',return_value=100.),patch.object(S,'worker',side_effect=AssertionError('completed jobs never rerun')),patch.object(S.subprocess,'Popen',return_value=awake):
                self.assertEqual(S.main(),0)
            result=json.loads((out/'ECONOMY_RUN_SUMMARIES.json').read_text())
            self.assertEqual(result['status'],'DONE');self.assertEqual(len(result['runs']),22)
            self.assertEqual(len(result['timing']['reused']),22)
            self.assertEqual(result['integrity'],dict.fromkeys(S.ARMS,'PASS'))


class ReportChecks(unittest.TestCase):
    def test_crashed_attempt_without_receipt_is_partial_and_local_error_only(self):
        names=('SERVICE_RUN_SUMMARIES.json','COVERAGE_COMPACT_SUMMARIES.json','MASS_BUDGET_DIAGNOSTIC.json','ECONOMY_PILOT_SPEC.md')
        with tempfile.TemporaryDirectory(dir=HERE/'_local') as tmp:
            out=Path(tmp);local=out/'local';local.mkdir()
            for n in names:(out/n).write_bytes((HERE/n).read_bytes())
            (local/'ECOR_i_k0_on.started').write_text('interrupted')
            with patch.object(R,'OUT',out),patch.object(R,'LOCAL',local),patch.object(R,'code_hashes',return_value={}),patch.object(R,'load_completed',side_effect=lambda j,b:(_ for _ in ()).throw(RuntimeError('incomplete ECOR')) if j[0]=='ECOR' else None):
                self.assertEqual(R.main(),2)
            data=json.loads((out/'ECONOMY_COMPACT_SUMMARIES.json').read_text())
            self.assertEqual(data['status'],'PARTIAL');self.assertTrue(data['arm_errors']['ECOR'])
            self.assertFalse(data['arm_errors']['ECOF']);self.assertFalse(data['common_errors'])

    def test_complete_good_arm_keeps_its_reading_when_other_arm_is_incomplete(self):
        names=('SERVICE_RUN_SUMMARIES.json','COVERAGE_COMPACT_SUMMARIES.json','MASS_BUDGET_DIAGNOSTIC.json','ECONOMY_PILOT_SPEC.md')
        rows=[sample_row(start=start,key=key) for start in ('i','ii') for key in range(5)]
        for r in rows:r.update(state_trajectory_sha256='a'*64,clone_isolation='PASS')
        off=copy.deepcopy(rows[0]);off['observer']='off';rows.append(off)
        supplied={(r['variant'],r['start'],r['keyset'],r['observer']):r for r in rows}
        def completed(job,baseline):
            if job==('ECOR','i',0,'on'):raise RuntimeError('incomplete ECOR')
            return supplied.get(job)
        with tempfile.TemporaryDirectory(dir=HERE/'_local') as tmp:
            out=Path(tmp)
            for n in names:(out/n).write_bytes((HERE/n).read_bytes())
            (out/'ECONOMY_RUN_SUMMARIES.json').write_text(json.dumps(dict(status='PARTIAL',runs=rows)))
            with patch.object(R,'OUT',out),patch.object(R,'LOCAL',out/'local'),patch.object(R,'code_hashes',return_value={}),patch.object(R,'load_completed',side_effect=completed):
                self.assertEqual(R.main(),2)
            data=json.loads((out/'ECONOMY_COMPACT_SUMMARIES.json').read_text())
            self.assertEqual(data['status'],'PARTIAL')
            self.assertEqual(data['arms']['ECOF']['reading'],'COVERAGE_IMPROVES')
            self.assertEqual(data['arms']['ECOR']['reading'],'INCOMPLETE')

    def test_exact_boundary_complete_integrity_missing_and_regression(self):
        arm=dict(status='DONE',pooled_3_6=R.TARGET,gate_shape={'i':dict(passes=4)})
        self.assertEqual(R.reading(arm,True),'COVERAGE_IMPROVES')
        arm['pooled_3_6']=math.nextafter(R.TARGET,0);self.assertEqual(R.reading(arm,True),'DESCRIPTIVE')
        arm['gate_shape']['i']['passes']=3;self.assertEqual(R.reading(arm,True),'REGRESSION')
        self.assertEqual(R.reading(arm,False),'INCOMPLETE');arm['status']='INCOMPLETE';self.assertEqual(R.reading(arm,True),'INCOMPLETE')

    def test_mass_metric_time_first_cost_and_trial_denominator(self):
        row=sample_row();row['telemetry']['initial_cost_refusals']=[dict(t=400.,cost=63.,candidate_cost=64.5)]
        row['telemetry']['prospective_checks']=[dict(triggered=True,trials=2,failures=1,result='removed',prospective_elapsed_seconds=.1,prospective_cpu_seconds=.05)]
        row['telemetry']['prospective_trials']=[dict(passed=False),dict(passed=True)]
        result=R.economy_metrics([row]);self.assertEqual(result['prospective']['failure_fraction'],.5)
        self.assertEqual(result['first_candidate_cost_refusal_per_run'][0]['refusal']['cost'],63.)
        row['telemetry']['prospective_trials'].pop()
        with self.assertRaises(ValueError):R.economy_metrics([row])

    def test_writer_NOT_RUN_and_PARTIAL_retains_completions_no_historical_writes(self):
        names=('SERVICE_RUN_SUMMARIES.json','COVERAGE_COMPACT_SUMMARIES.json','MASS_BUDGET_DIAGNOSTIC.json','ECONOMY_PILOT_SPEC.md')
        before={n:(HERE/n).read_bytes() for n in names}
        for partial in (False,True):
            row=sample_row()
            with tempfile.TemporaryDirectory(dir=HERE/'_local') as tmp:
                out=Path(tmp)
                for n,raw in before.items():(out/n).write_bytes(raw)
                if partial:(out/'ECONOMY_RUN_SUMMARIES.json').write_text(json.dumps(dict(status='PARTIAL',runs=[row])))
                with patch.object(R,'OUT',out),patch.object(R,'LOCAL',out/'local'),patch.object(R,'code_hashes',return_value={}),patch.object(R,'load_completed',side_effect=lambda j,b:row if j==('ECOF','i',0,'on') else None):
                    self.assertEqual(R.main(),0)
                d=json.loads((out/'ECONOMY_COMPACT_SUMMARIES.json').read_text())
                self.assertEqual(d['status'],'PARTIAL' if partial else 'NOT_RUN')
                self.assertEqual(d['arms']['ECOF']['reading'],'INCOMPLETE')
                self.assertEqual(len(d['arms']['ECOF']['runs']),int(partial))
                self.assertIn('legacy_B',d['control']['non_repair_causes']);self.assertNotIn('B',d['control']['non_repair_causes'])
                for n,raw in before.items():self.assertEqual((out/n).read_bytes(),raw)
                self.assertTrue((out/'ECONOMY_PILOT_REPORT.md').read_text().startswith(d['status']+'\n'))


if __name__=='__main__':unittest.main()
