"""Render stored results without rerunning a fight or changing an outcome."""
import pathlib,json,sys,re
HERE=pathlib.Path(__file__).resolve().parent;CPP=HERE.parent;REPO=CPP.parents[2];sys.path.insert(0,str(CPP))
from build_admission import sha

def main():
 s=json.loads((HERE/'SUMMARY.json').read_text());d=json.loads((HERE/'DECLARATION.json').read_text());run=json.loads((HERE/'RUN_TIMING.json').read_text());audit=json.loads((HERE/'ANALYSIS_VERIFICATION.json').read_text());tests=json.loads((HERE/'CHECK_TIMING.json').read_text());build=json.loads((HERE/'BUILD_TIMING.json').read_text())
 for n,h in d['protected'].items():assert sha(REPO/n)==h,n
 assert len(s['fights'])==160 and run['status']=='DONE' and audit['status']=='PASS' and tests['returncode']==0
 realization=json.loads((HERE/'P6_REALIZATION.json').read_text())
 compact=dict(status='DONE',p6_realization=realization['aggregates'],p6_novice_plain_byte_identical_fights=realization['novice_plain_byte_identical_fights'],scope=s['scope'],declaration_sha256=sha(HERE/'DECLARATION.json'),summary_sha256=sha(HERE/'SUMMARY.json'),definitions=s['definitions'],rows=s['rows']);(HERE/'COMPACT.json').write_text(json.dumps(compact,separators=(',',':'),allow_nan=False)+'\n')
 text='''DONE

All160/160 fights completed: 10 fresh development seed clusters × 2 orientations × P0/P4/P5/P6 × regular/novice, controlled team0. Single declared setting; descriptive scripted probe of DESIGN_0G19.2, not an RRG controller or a scientific/readiness verdict. No tuning, registration, judging entropy or status change.

Parameters and full head request templates were declared before any engineering/development fight in [POLICY.md](s4_focus_probe_v1/POLICY.md), [DECLARATION.json](s4_focus_probe_v1/DECLARATION.json) and the new [development ledger](s4_focus_probe_v1/DEVELOPMENT_SEED_LEDGER.json). Every arm uses the exact v6 attempt-2 stage-B knobs. P4 guns select lowest-HP reachable enemy gun, ties by id, and keep the full v6 target otherwise. No target suppression or fire-holding occurs. P5 also replaces gun movement with radial commitment at own reach minus12px (bounded below by own minRange). P6 direct/ranged units also target the shared focus within native direct reach; their movement and all melee commands remain v6. All enemy guns gone restores complete v6 actions.

Shared focus is the weakest gun reachable by any own gun; if none is reachable, weakest living gun overall. P4/P5 still select individually within each gun's reach. Different reach sets can split the battery across targets. P5 replaces the entire gun movement command, including neighbour forces, so it tests a scripted commitment policy rather than isolating one term in the v6 equations. P6 uses edge-to-edge direct reach; line-of-fire blockers remain native and may prevent a shot. Enemy motion, collisions, clipping and reflexes can obstruct commitment. Base v6 internal target memory remains the baseline computation, while actual action targets change observed combat. These are declared limitations, not post-outcome changes.

| Arm | Head | Elimination wins | Timeouts | Mean S | Enemy guns destroyed /10 | Own gun losses /10 | Own losses /50 | Shell hits / fired at enemy guns | First gun kill mean s (fights with a kill) |
|---|---|---:|---:|---:|---:|---:|---:|---:|---:|
'''
 for r in s['rows']:
  first=f"{r['mean_first_enemy_gun_kill_s']:.2f} ({r['first_gun_kill_fights']}/20)" if r['first_gun_kill_fights'] else 'none (0/20)'
  text+=f"| {r['arm']} | {r['head']} | {r['elimination_wins']}/20 | {r['timeouts']}/20 | {r['mean_S']:+.2f} | {r['mean_enemy_guns_destroyed']:.2f} | {r['mean_own_gun_losses']:.2f} | {r['mean_own_losses']:.2f} | {r['shell_hits_on_enemy_guns']} / {r['shells_fired_at_enemy_guns']} | {first} |\n"
 text+='\nWho kills our guns (total deaths across20 fights per cell; source team0 is friendly, team1 enemy):\n\n| Arm | Head | Own gun killers by team / role |\n|---|---|---|\n'
 for r in s['rows']:
  killers=', '.join(f"team{k['team']} {k['role']}: {k['kills']}" for k in r['own_gun_killers']) or 'none'
  text+=f"| {r['arm']} | {r['head']} | {killers} |\n"
 text+='''
Elimination requires enemy0, own>=1 and t<150s. Timeout never counts as a win. S is own survivors minus enemy survivors. Gun/own casualties are means per fight; launch/hit totals sum20 fights. Hit numerator counts distinct damaging own shell launches aimed at enemy guns that damage at least one enemy gun; multiple splash victims count once. Soft-target launches incidentally hitting guns are excluded from both targeted counts. Denominator includes misses and shells still airborne at termination. First kill times are conditional on at least one enemy gun dying; no-kill fights are not assigned150s or zero. Medians, per-fight times, killer unit ids/roles/teams, elimination times and losses per enemy kill are in JSON. Orientations are paired within clusters; no confidence/acceptance claim or general mechanism rejection follows from this one setting. Auto barrage/slow remain inactive on both sides because sandboxAbilities=false; regular formation and shell dodge remain active.

'''
 regular=[r for r in s['rows'] if r['head']=='regular'];novice=[r for r in s['rows'] if r['head']=='novice']
 text+=f"P6 realization audit: {realization['aggregates']['regular']['focus_actions']} direct-unit focus ticks in {realization['aggregates']['regular']['fights_with_opportunity']}/20 regular fights; zero eligible direct-unit ticks in all20 novice fights. All20 P5/P6 novice observer streams, actions and terminal metrics are byte-identical after decompression. Thus P6 adds no realized intervention against novice in this set; its20/20 does not establish an incremental direct-unit benefit. [P6_REALIZATION.json](s4_focus_probe_v1/P6_REALIZATION.json) preserves counts and stream SHA256 values. This stored-only audit did not change policy or outcomes.\n\n"
 text+='Regular elimination wins: '+', '.join(f"{r['arm']} {r['elimination_wins']}/20" for r in regular)+'. Novice: '+', '.join(f"{r['arm']} {r['elimination_wins']}/20" for r in novice)+'. These are observed outcomes for the declared policies; no setting was changed after outcomes.\n\n'
 failed=json.loads((HERE/'FAILED_FIRST_CHECK_TIMING.json').read_text());total=sum(x['awake_seconds'] for x in (build,failed,tests,run,audit,realization))
 text+=f"Build elapsed/awake {build['elapsed_seconds']:.3f}/{build['awake_seconds']:.3f}s; final focused checks {tests['elapsed_seconds']:.3f}/{tests['awake_seconds']:.3f}s; combat {run['elapsed_seconds']:.3f}/{run['awake_seconds']:.3f}s; stored-only all-tick recount {audit['elapsed_seconds']:.3f}/{audit['awake_seconds']:.3f}s. P6 stored-only realization audit {realization['elapsed_seconds']:.3f}/{realization['awake_seconds']:.3f}s. Total measured probe-stage awake time {total:.3f}s, below3600s. Each compute stage used caffeinate; combat/recount caps1200s and a remaining1h projection guard. No code edits occurred during fights or recount.\n\n"
 review=json.loads((HERE/'REVIEW_TIMING.json').read_text());text+=f"Independent stored-data review reads: {review['captured_total_seconds']:.3f}s captured; an initial repeat read lacked a retained terminal session/timing and has a conservative60s budget reservation. No fights or tests were repeated by the reviewer. Probe stages plus this conservative review accounting total {total+review['conservative_total_seconds']:.3f}s, below3600s.\n\n"
 text+=f"Historical attribution/v6 contract stdout and stderr remain byte-identical across historical v6, observer, volley and new focus binaries. P0 also matches observer states, actions, telemetry and metrics byte-for-byte in both two-second engineering comparisons. All{len(d['protected'])} protected tracked inputs retain SHA256 identity. The initial test stopped on unrelated roadmap commit74c8b77 by another session; the original declaration and failed check are retained, and CONCURRENT_WORK.json records its exclusion from the overbroad protection snapshot. No policy, engine input, parameter or seed changed. All160 raw hashes, requests, casualties, first kill times, killer totals and targeted shell identities reconcile. No controller failures, forks, search, rollouts or branch steps occurred.\n\n"
 text+='''Owner rechecks and dispositions: [OWNER_RECHECK.md](s4_focus_probe_v1/OWNER_RECHECK.md). The verbatim request was sent to separate reviewers. Claude CLI is not logged in; separate Codex review is the disclosed same-family fallback. The owner explicitly forbids PLAN_CURRENT edits, so tracking stays adjacent. No numeric scores or cross-family acceptance claim.

Evidence: [compact aggregate JSON](s4_focus_probe_v1/COMPACT.json), [full per-fight summary](s4_focus_probe_v1/SUMMARY.json), [native outcomes](s4_focus_probe_v1/FIGHTS.json), [all-tick verification](s4_focus_probe_v1/ANALYSIS_VERIFICATION.json), [historical fixtures](s4_focus_probe_v1/HISTORICAL_FIXTURES.json), [P0 parity](s4_focus_probe_v1/P0_PARITY.json). Raw30Hz traces, requests, stderr and ledger claim stay local, identified by SHA256 and byte count in [RAW_FILES_LOCAL.json](s4_focus_probe_v1/RAW_FILES_LOCAL.json). Files over45MB are never delivered. Reproducible final scripts are run.py, analyze.py, report.py, check.py, build.py and deliver.py plus the new native sources; create_focus_probe_v1.py and make_analysis.py are historical bootstrap helpers, not final script generators. Delivery commit/bundle identity and fetched-blob verification are recorded in adjacent DELIVERY_TRANSPORT.json.
'''
 text=re.sub(r'\b(All|all|team|its|minus|below|caps|over|reserve)(?=\d)',r'\1 ',text).replace('DESIGN_0G19.2','DESIGN_0G §19.2').replace('sum20','sum 20').replace('Raw30Hz','Raw 30 Hz').replace('conservative60s','conservative 60 s')
 (CPP/'S4_FOCUS_PROBE.md').write_text(text)
 (HERE/'PRESERVATION.json').write_text(json.dumps(dict(status='PASS',tracked_protected_files=len(d['protected']),all_protected_hashes_match=True,plan_current_unchanged=True),indent=2)+'\n')
 print(json.dumps(dict(status='DONE',compute_awake_seconds=total,report_sha256=sha(CPP/'S4_FOCUS_PROBE.md'))))
if __name__=='__main__':main()
