"""Render the owned diagnostic from COMPACT.json; does not read raw or run combat."""
import collections
import json
import pathlib

HERE = pathlib.Path(__file__).resolve().parent


def pct(n, d):
    return f"{n}/{d} ({100*n/d:.1f}%)" if d else f"{n}/0 (unavailable)"


def main():
    data = json.loads((HERE / "COMPACT.json").read_text())
    rows = data["aggregates"]
    text = ["PARTIAL", "", "Stored-data fire-efficiency diagnostic, DESIGN_0G §19.5 (f169a42). All 20 fights each of P5 regular, P7 regular and P5 novice: 60/60, ten paired clusters × two orientations, team 0 controlled. All selected raw/request SHA256 and byte counts match RAW_FILES_LOCAL.json before analysis; contiguous 30 Hz frames, shell attribution and historical launch/hit/casualty counts reconcile. No fights, simulations, tuning, registration or status changes. PARTIAL refers to unavailable readiness, exact nearest-at-death positions and causal switch losses, not missing fights.", "",
            "Definitions and normalization", "",
            "Observer `units` indices: 0 id, 1 team, 2 role (0 melee, 1 ranged, 2 artillery), 3–4 centre x/y, 5 HP, 6 radius, 7 native range, 8 minimum range, 9–11 formation slot, 12 prep (windup progress), 13 actual target. `actions`: 0 id, 1 team, 2 target, 3–4 goal, 5 multiplier, 6 stop distance, 7 release kind, 8 move, 9 keep, 10 post, 11 bound, 12 decision inReach. `launches`: 0 source, 1 target, 2 team, 3–4 fixed shell aim point, 5 born, 6 scheduled impact, 7 splash, 8 barrage, 9 slow. Damage uses source/target IDs, team/role, dealt HP, t, died/killer and exact source/target coordinates. Schema and semantics sources match original declaration pins.", "",
            "Living gun-time sums guns alive at each interval's start ×1/30 s, including the death interval; this is a discrete exposure denominator, not an assumption about survival within the tick. Range opportunity samples that same start snapshot: any living opposing target with inclusive centre distance in [minRange,range]; no guessed line-of-fire or readiness requirement. Moving means >1e-6 px centre displacement across adjacent snapshots, including collisions/separation/reflexes; death intervals lack end positions and are excluded from its known denominator. Movement-command proxy: move=true, multiplier>0 and goal farther than stop+1e-9 from the preceding position. It is an intent proxy, not native movement execution; enemy formation may issue it while physically stationary. Windup means start-snapshot prep>0. Firing means a damaging shell launch in the interval, with each launch interval contributing 1/30 s; it is not sustained fire time. These indicators overlap and do not sum to 100%.", "",
            "Ready but not firing: **unavailable for both sides**, since observer frames omit cooldown, energy, castOk and cast target. Windup is reported separately and is not readiness. A reset without a launch is a surviving gun's decreasing prep; it is observable consumption/reset, not automatically an interrupted windup or a movement cause. Switch losses are unavailable as a causal/counterfactual count.", "",
            "Gun-time and firing (pooled; rates in launches/gun-second)", "",
            "|Arm/head|Side|Launches / living gun-s|Moving / known ticks|Move-command / living ticks|Any target range / living ticks|Enemy gun range / living ticks|Windup / living ticks|Launch intervals / living ticks|",
            "|---|---|---|---|---|---|---|---|---|"]
    for a in rows:
        for side, m in enumerate(a["sides"]):
            c = collections.Counter(m["counts"]); n=c["living_ticks"]
            text.append(f"|{a['arm']} {a['head']}|{side}|{c['launches']}/{m['living_gun_seconds']:.2f} = {m['launches_per_living_gun_second']:.3f}|{pct(c['moving_ticks'],c['movement_known_ticks'])}|{pct(c['move_command_ticks'],n)}|{pct(c['any_target_range_ticks'],n)}|{pct(c['gun_target_range_ticks'],n)}|{pct(c['windup_ticks'],n)}|{pct(c['launch_ticks'],n)}|")
    text += ["", "Moving excludes 200 death intervals per regular own battery, 63/49 per regular enemy battery, and 25/200 for novice own/enemy. All other samples are included. Long enemy survival after our battery dies dilutes whole-fight rates; compare matched clock windows below rather than reading that dilution as inefficient enemy fire.", "",
             "Movement, windup and target changes", "",
             "|Arm/head|Side|Launches while displaced / launches with known displacement|Resets without launch (at command start / at displacement start / with target change)|Launch-to-launch gap median, observed n|Command starts: observed / next-start censored / death censored / end censored|In-range command-start→launch mean, observed n|",
             "|---|---|---|---|---|---|---|"]
    for a in rows:
        for side, m in enumerate(a["sides"]):
            c=collections.Counter(m["counts"]); statuses=collections.Counter(m["move_gap_status_counts"])
            g=m['in_range_move_start_to_launch_s']; il=m['interlaunch_gaps_s']
            gm=f"{g['mean']:.3f}s, {g['n']}" if g['n'] else "unavailable, 0"
            text.append(f"|{a['arm']} {a['head']}|{side}|{pct(c['moving_launch_ticks'],c['moving_launch_ticks']+c['stationary_launch_ticks'])}|{m['windup_resets_without_launch']} ({m['resets_at_move_start']}/{m['resets_at_displacement_start']}/{m['resets_with_target_switch']})|{il['median']:.3f}s, {il['n']}|{statuses['observed']}/{statuses['censored_by_next_move_start']}/{statuses['censored_by_death']}/{statuses['censored_by_end']} (all {m['move_starts']})|{gm}|")
    text += ["", "Command-start gaps run from the stored decision tick to the first launch before another start, death or fight end. Censored cases remain null; observed means do not represent all starts. In-range conditions use the preceding snapshot. Physical displacement-start gap distributions and every start/reset/switch record are also in JSON, with their censor counts; they include collision motion. Enemy regular has no in-range command starts: its proxy stays active from initial approach. Its unavailable cell is not zero delay.", "",
             "|Arm/head|Side|In-range command launch rate / exposure|In-range hold launch rate / exposure|Displacement starts: observed / censored|In-range displacement-start→launch mean, observed n|Windup target changes / all changes; launching same tick|",
             "|---|---|---|---|---|---|"]
    for a in rows:
        for side,m in enumerate(a['sides']):
            c=collections.Counter(m['counts']); dg=m['in_range_displacement_start_to_launch_s']; st=m['displacement_gap_status_counts']
            command=f"{c['command_launch_range_ticks']}/{c['command_range_ticks']/30:.2f}s = {m['command_range_launches_per_gun_second']:.3f}" if c['command_range_ticks'] else 'unavailable'
            hold=f"{c['hold_launch_range_ticks']}/{c['hold_range_ticks']/30:.2f}s = {m['hold_range_launches_per_gun_second']:.3f}" if c['hold_range_ticks'] else 'unavailable (0s)'
            dg_text=f"{dg['mean']:.3f}s, {dg['n']}" if dg['n'] else 'unavailable, 0'
            text.append(f"|{a['arm']} {a['head']}|{side}|{command}|{hold}|{st.get('observed',0)}/{m['displacement_starts']-st.get('observed',0)} (all {m['displacement_starts']})|{dg_text}|{m['switches_during_windup']}/{c['target_switches']}; {m['switches_during_windup_with_launch']}|")
    text += ["", "Pinned gamePrep keeps increasing prep while moving or changing targets. The measured 1.2s typical cadence and launches during displacement do not support movement-cancelled windup as the main loss. Hold exposure for our guns is tiny and selected, so the rates cannot identify a stop-moving benefit. Resets may be releases consumed without a shell because the current target is absent/outside the release band; no cast-target/energy log identifies their exact cause. Target changes during prep usually do not reset prep.", "",
             "Target allocation and hits over time", "",
             "|Arm/head|Side|Launch-time window s|All launches / living gun-s (rate)|Aimed at guns / all launches|Gun-targeted shells hitting any gun / aimed at guns|Hitting intended gun / aimed at guns|Nongun-targeted shells damaging guns / aimed elsewhere|Gun victim hits from gun / other targeting|",
             "|---|---|---|---|---|---|---|---|---|"]
    for a in rows:
        for side,m in enumerate(a['sides']):
            for b in m['time_bins']:
                c=collections.Counter(b['counts'])
                if not c['living_ticks'] and not c['launches']:continue
                rate=b['launches_per_living_gun_second']
                text.append(f"|{a['arm']} {a['head']}|{side}|[{b['from_s']},{b['to_s']})|{c['launches']}/{b['living_gun_seconds']:.2f} ({rate:.3f})|{pct(c['gun_launches'],c['launches'])}|{pct(c['gun_launches_hit_any_gun'],c['gun_launches'])}|{pct(c['gun_launches_hit_intended_gun'],c['gun_launches'])}|{pct(c['other_launches_hit_gun'],c['other_launches'])}|{c['gun_target_shell_gun_victims']}/{c['other_target_shell_gun_victims']}|")
    text += ["", "Bins use launch time, not damage time; eventual hits can cross a bin boundary. Living exposure uses interval-start time. Last bin includes any floating-point endpoint at 150s. Hit means positive dealt damage, not a projectile near miss. Any-gun success counts a shell once; intended-gun success requires its release target. Gun-victim hits count all distinct opposing guns damaged by that shell. Shell attribution uses source and unique scheduled-impact interval; all launches including airborne end shells remain denominators. Incidental gun splash from other targeting is reported separately.", "",
             "|Arm/head|Side|Gun targeting / all launches|Any-gun successful targeted shells|Gun victims / successful targeted shell|Gun damage from gun / other targeting (HP)|Already dead before scheduled impact / gun launches; no gun hit|Airborne target switches / all launches; gun-targeted hit / switched gun launches|",
             "|---|---|---|---|---|---|---|"]
    for a in rows:
        for side,m in enumerate(a['sides']):
            c=collections.Counter(m['counts']); hits=c['gun_launches_hit_any_gun']
            text.append(f"|{a['arm']} {a['head']}|{side}|{pct(c['gun_launches'],c['launches'])}|{pct(hits,c['gun_launches'])}|{c['gun_target_shell_gun_victims']}/{hits} = {c['gun_target_shell_gun_victims']/hits:.2f}|{c['gun_target_shell_gun_damage']:.0f}/{c['other_target_shell_gun_damage']:.0f}|{c['gun_launches_target_dead_before_scheduled_impact']}/{c['gun_launches']}; {c['gun_launches_no_gun_hit_target_dead_before_scheduled_impact']}|{c['launches_with_airborne_target_switch']}/{c['launches']}; {c['gun_launches_with_airborne_target_switch_hit']}/{c['gun_launches_with_airborne_target_switch']}|")
    text += ["", "Launches lost **because of** target switches: unavailable. Released shells retain a fixed aim point; a later target switch does not cancel them. Observed switches, resets and misses do not identify a counterfactual loss. Already-dead-target counts compare exact logged death time strictly before scheduled impact, exclude same-time ties, and may include splash on survivors. These support examining redundant commitments to doomed targets, not attributing losses to switching itself. Every gun-targeted launch here resolved before fight end; airborne end counts remain explicit in JSON.", "",
             "Own gun deaths", "",
             "Exact killer and death x/y are retained for every own gun death in JSON (`fights[].deaths[]`, 425 rows). Exact distance to the killer is `killer_distance_exact`. Exact nearest living enemy gun/ranged distance at death is **unavailable**: other units' coordinates and within-step alive ordering are absent at that instant. The following are centre-distance estimates from the exact victim death point to enemy centres alive in the preceding snapshot, 1/30s old. A nearest enemy may move or die in that step; no invented error bound is applied. Ranged reach estimates use surface gap (distance minus both radii); gun bands use centre distance.", "",
             "|Arm/head|Deaths|Nearest enemy gun previous-snapshot mean / median px (available n)|Nearest enemy ranged previous-snapshot mean / median px (available n)|Within gun band / available; within ranged reach / available|Killers (team_role: count)|",
             "|---|---|---|---|---|---|"]
    for a in rows:
        d=a['death_summary']; g=d['gun_distance_previous_snapshot']; r=d['ranged_distance_previous_snapshot']
        text.append(f"|{a['arm']} {a['head']}|{d['n']}|{g['mean']:.1f}/{g['median']:.1f} ({g['n']})|{r['mean']:.1f}/{r['median']:.1f} ({r['n']})|{d['gun_in_native_band_previous_snapshot']}/{g['n']}; {d['ranged_in_native_band_previous_snapshot']}/{r['n']}|{', '.join(k+': '+str(v) for k,v in d['killers'].items())}|")
    text += ["", "What explains the exchange in these traces", "",
             "**Splash multiplicity and exposure explain the recorded HP exchange.** P5 regular's 953/1120 gun-targeted hits (47.65 successful shells/fight) delivered 1056 gun-victim hits and 14958 HP. Enemy gun-targeted hits were fewer, 455/511 (22.75/fight), but each successful shell damaged 3.85 guns against our 1.11: 1752 victim hits and 25238 HP. A further 132/1738 shells aimed at other units splashed 425 gun victims for 6366 HP. Total enemy artillery damage to our guns was 31604 HP (1580.2/fight), **2.11×** our 14958 HP (747.9/fight). It accounts for 87.3% of the 36200 HP lost by all 200 own guns; enemy ranged adds 4240 HP (11.7%), enemy melee 148 and friendly ranged 208. Killer counts (142 artillery, 55 ranged, 1 melee, 2 friendly) record last hits and differ from damage shares. Our shells damaged mostly one or two enemy guns; theirs damaged up to nine of ours per shell. Equal reach and equal successful-shell counts would still not imply equal damage.", "",
             "P7 repeats and worsens the same exchange: our 683/818 hits yield 758 victim hits, 10698 HP; their 410/470 yield 1689 victim hits, 24180 HP, plus 500 incidental victims/7486 HP. Artillery total 31666 HP is **2.96×** our shell damage. Enemy ranged adds 3961 HP. All 200 own guns die; only 49 enemy guns die, versus 63 in P5. The bundles do not isolate why clustering/exposure changes.", "",
             "**Enemy firing uptime or stronger counter-battery priority is not demonstrated.** Own gun-target shares are 66.8% P5 /52.8% P7 versus enemy 22.7%/22.9%. Own normalized whole-fight firing rates are higher; in [10,20)s they are about 0.815/0.814 versus enemy 0.757/0.751 launches/gun-second. Range-conditioned command rates are own 0.822/0.823 versus enemy 0.832/0.822 for P5/P7. Own interlaunch medians are 1.2s despite motion. The enemy's advantage is damage per successful shell and supported exposure, not more launches per living gun-second. P5 and P7 spend only 37.1%/33.5% of own gun-time in enemy-gun range; early shells go to other units. P7 sends 302 fewer shells at guns than P5 (818 vs1120), delivering 4260 less HP to enemy guns. Staging/targeting/movement remain a combined intervention.", "",
             "**The novice contrast reverses splash effectiveness.** Our 794/1039 successful gun-targeted shells hit 2598 gun victims (3.27 per success) and deal 36198 HP plus 2 incidental HP: the full 200 enemy guns' HP. All 200 enemy guns die while only 25 own guns die. Our hit rate is lower than against regular (76.4% vs85.1%) yet the gun exchange is vastly better. The regular line's dispersed gun geometry is consistent with the lower victim multiplicity; this stored comparison does not isolate formation or dodge as a causal treatment. Already-dead targets account for 164/167 P5 regular and 128/135 P7 regular gun-targeted no-gun-hit launches. Avoidable overcommitment is plausible; changing targets itself is not proven to cause those misses.", "",
             "Smallest scripted hypotheses supported; **not run**", "",
             "1. Preserve P5 target/movement rules and add only a battery spacing rule sized to avoid shared splash footprints. The 3.85-versus1.11 victim multiplicity supports a spacing/exposure hypothesis. Native clipping, arena space and maintaining focus/range must be checked in any separately authorized probe; no setting is selected here.",
             "2. Preserve P5 and add only an estimated-in-flight-damage cap on further shells committed to a gun, retargeting once outstanding damage covers its HP. The 164/167 and128/135 no-gun-hit shells whose target died before scheduled impact support redundant-shell allocation as a candidate. Current controllers lack shell observations; a scripted probe would need explicitly authorized launch bookkeeping, not hidden observer input.",
             "3. Preserve gun actions and change only ranged screen targeting toward enemy ranged threatening our guns. Enemy ranged contributes 4240/3961 HP and55/56 gun last hits; nearby ranged exposure supports a screen hypothesis, but a screen may obstruct own fire or cluster with guns.",
             "4. A range-hold rule could test reduced approach/exposure or better spacing, but these traces do not support windup cancellation as its mechanism. Blanket counter-battery priority is also weakly supported: P5 already assigns two-thirds of shells to guns. Neither is the leading fire-efficiency fix from these numbers.", "",
             "Reproduce with `python3 evidence/tactical_composition_demo/astelia_cpp/s4_fire_efficiency_v1/analyze.py` then `python3 evidence/tactical_composition_demo/astelia_cpp/s4_fire_efficiency_v1/render.py`. [COMPACT.json](s4_fire_efficiency_v1/COMPACT.json) retains pooled counts, time bins and every fight's denominators/deaths/gaps/resets/switches; [VERIFICATION.json](s4_fire_efficiency_v1/VERIFICATION.json) pins inputs and script. [OWNER_RECHECK.md](s4_fire_efficiency_v1/OWNER_RECHECK.md) records the verbatim request, independent findings and disposition. Per user instruction PLAN_CURRENT and DESIGN_0G remain untouched. Raw stays local; no delivered file exceeds45 MB."]
    (HERE.parent / "S4_FIRE_EFFICIENCY_DIAGNOSTIC.md").write_text("\n".join(text)+"\n")


if __name__ == '__main__':
    main()
