// Isolated seams plus bounded scripted coreStep lifecycle fixtures; no fights.
#include "host.h"
#include "integration.h"
#include "teacher.h"
#include "controller_bridge.h"
#include <iostream>
using namespace astelia;using namespace net_slice;
namespace {
unsigned checks=0;
void check(bool x,const char* why){++checks;if(!x)throw std::runtime_error(why);}
void near(double a,double b,const char* why){check(std::abs(a-b)<1e-8,why);}
void transitions(){Intent c;c.target=101;c.hasAim=true;c.aim={650,400};c.start=true;c.release=true;c.startOpportunity=true;c.releaseOpportunity=true;Cast cast;CastInput in{1,true,false,true,true,true,0,100,6,0,.1};check(cast.project(in,c).start,"start-ready");in.cooldown=1;check(cast.project(in,c).state=="idle/cooldown","cooldown");in.cooldown=0;in.energy=0;check(!cast.project(in,c).start,"energy");in.energy=100;in.body=true;check(cast.project(in,c).reason=="body","body gate");in.body=false;in.prep=.01;check(cast.project(in,c).state=="winding","winding");c.start=c.release=false;check(cast.project(in,c).state=="winding","hold progresses");in.prep=.1;in.tick=2;check(cast.project(in,c).state=="prepared","prepared hold");in.tick=7;check(!cast.project(in,c).release,"six-tick expiry not early");in.tick=8;check(cast.project(in,c).release,"auto release hold bound");in.target=false;check(cast.project(in,c).cancel&&!cast.project(in,c).release,"target-death bound cancels not launches");in.target=true;in.aimReach=false;check(cast.project(in,c).cancel&&!cast.project(in,c).release,"aim bound before expiry");in.aimReach=true;in.targetReach=false;check(cast.project(in,c).reason=="target_range","min max target range");cast.startedAck(1,c);check(cast.lockedTarget==101&&!cast.aimLocked,"start lock target only when release hold");cast.consumedAck();check(!cast.pending,"consumed reset");in.alive=false;check(cast.project(in,c).state=="consumed-without-launch","dead");}
World world(const Weights& weights,bool shadow){auto cfg=std::make_shared<Config>(gameConfig());cfg->abilities=false;cfg->skills[0]=CombatSkills{};cfg->skills[1]=CombatSkills{};cfg->width=1400;cfg->height=800;World w(cfg);w.dt=1./30;auto a=w.add(0,Role::Artillery,{400,400});auto b=w.add(1,Role::Artillery,{650,400});w.units[a.slot].range=320;w.units[a.slot].speed=80;w.state[a.slot].minRange=30;w.state[a.slot].windup=.3;w.state[a.slot].energy=100;w.state[a.slot].cost=6;w.state[a.slot].cooldownMax=.4;w.units[b.slot].range=320;w.rebuildTeams();w.liveGrid.build(w.units,w.active,1400,800,40);auto h=std::make_unique<Host>(0,std::make_shared<const Weights>(weights));h->shadow=shadow;w.controllers[0]=std::move(h);return w;}
std::string bytes(const World& w){js::Args units,states,shells,shots,fields,authority;auto ref=[](UnitRef r){return js::arr({double(r.slot),double(r.generation)});};
 for(const auto& u:w.units)units.push_back(js::arr({double(u.id),double(u.generation),double(u.team),double(uint8_t(u.role)),u.alive,u.occupied,u.pos.x,u.pos.y,u.velocity.x,u.velocity.y,u.smoothVelocity.x,u.smoothVelocity.y,u.hp,u.maxhp,u.radius,u.speed,u.range,u.damage,u.cooldown,ref(u.target)}));
 for(const auto& s:w.state){const auto& d=s.decision;js::Args rolled;for(auto q:s.rolledShots)rolled.push_back(double(q));states.push_back(js::arr({s.previous.x,s.previous.y,s.slot.x,s.slot.y,s.longVelocity.x,s.longVelocity.y,s.cooldownMax,s.prep,s.windup,s.baseSpeed,s.energy,s.energyMax,s.energyRegen,s.cost,s.protection,s.minRange,s.shotSpeed,s.lobSpeed,s.splash,s.launch,s.timeRate,s.longSpeed,s.stepTime,s.dealt,s.meleeAt,s.damageDealt,s.damageTaken,s.dealtToEnemy,s.takenFromEnemy,s.friendlyDealt,s.friendlyTaken,ref(s.meleeAttacker),double(s.strafe),double(s.kind),double(s.ability),double(s.player),s.castTime,s.standoff,s.dashReady,s.guardUntil,s.blockReady,s.guardDirection,s.lastShotHit,double(uint8_t(s.dodge)),s.hasSlot,s.inReach,s.castOk,s.block,js::arr(std::move(rolled)),d.goal.x,d.goal.y,d.stop,d.multiplier,double(uint8_t(d.release)),d.move,d.keep,d.post,d.bound}));}
 for(const auto& s:w.shells)shells.push_back(js::arr({double(uint8_t(s.family)),double(s.variant),s.finisher,s.pos.x,s.pos.y,ref(s.source),s.at,s.born,s.damage,s.splash,s.prediction,s.slow,s.lob,s.barrage,s.hasPrediction,s.done}));
 for(const auto& s:w.shots){js::Args hit;for(auto r:s.hitSet)hit.push_back(ref(r));shots.push_back(js::arr({s.pos.x,s.pos.y,s.direction.x,s.direction.y,ref(s.source),ref(s.target),s.speed,s.damage,s.pending,s.left,s.born,double(s.ordinal),double(s.pierce),s.aimed,s.dodgeable,s.done,s.manual,js::arr(std::move(hit))}));}
 for(const auto& f:w.fields)fields.push_back(js::arr({f.pos.x,f.pos.y,f.radius,f.from,f.until,double(f.team)}));
 if(auto* h=dynamic_cast<const Host*>(w.controllers[0].get())){authority.push_back(double(h->tick));for(auto p:h->cache)authority.push_back(js::arr({double(p.first),json(p.second)}));for(auto p:h->raw)authority.push_back(js::arr({double(p.first),json(p.second)}));for(auto p:h->decisionTicks)authority.push_back(js::arr({double(p.first),double(p.second)}));for(auto p:h->phases)authority.push_back(js::arr({double(p.first),p.second}));for(auto p:h->lastLaunch)authority.push_back(js::arr({double(p.first),p.second}));for(auto p:h->heldForce)authority.push_back(js::arr({double(p.first),p.second}));for(auto p:h->assignments)authority.push_back(js::arr({double(p.first),double(p.second)}));for(auto p:h->memory){js::Args a;for(auto q:p.second)a.push_back(q);authority.push_back(js::arr({double(p.first),js::arr(std::move(a))}));}for(auto p:h->heldFeatures){js::Args a;for(auto q:p.second)a.push_back(q);authority.push_back(js::arr({double(p.first),js::arr(std::move(a))}));}for(auto p:h->casts){const auto& c=p.second;authority.push_back(js::arr({double(p.first),c.pending,c.aimLocked,double(c.lockedTarget),c.lockedAim.x,c.lockedAim.y,double(c.readySince),double(c.started),double(c.originDecision),double(c.originVolley),json(c.last)}));}for(auto p:h->projected)authority.push_back(js::arr({double(p.first),p.second.state,p.second.reason,p.second.start,p.second.release,p.second.cancel}));for(auto id:h->consumed)authority.push_back(double(id));for(auto s:h->views)authority.push_back(s);}
 check(w.dots.empty()&&w.abilities.empty()&&w.players.empty()&&w.meleeHits.empty()&&w.spawnQueue.empty(),"fixture serialization scope has no omitted active actors");
 return js::stringify(js::obj({{"time",w.time},{"rng",double(w.random.state)},{"spawn_rng",double(w.spawnRandom.state)},{"next_id",double(w.nextId)},{"next_shot",double(w.nextShot)},{"units",js::arr(std::move(units))},{"state",js::arr(std::move(states))},{"shells",js::arr(std::move(shells))},{"shots",js::arr(std::move(shots))},{"fields",js::arr(std::move(fields))},{"authority",js::arr(std::move(authority))},{"launch_count",double(w.stats.shellOut[0].shells)},{"controller_failures",double(w.stats.controllerFailures[0])}}));}
js::V seams(const Weights& weights){auto a=world(weights,false),b=world(weights,true);js::Args traces;Collector all;for(unsigned tick=1;tick<=18;++tick){for(World* p:{&a,&b}){auto& w=*p;w.time=tick*w.dt;if(w.units[0].cooldown>0)w.units[0].cooldown-=w.dt;bind(w);prepareControllers(w);net_slice::decide(w,0);prePrep(w);gamePrep(w,0,w.dt);postPrep(w);if(w.state[0].decision.release==Release::Artillery&&prepared(w,0)&&aimReach(w,0)){released(w,0);fireShellAt(w,0,aimPoint(w,0,{}));}finishTick(w);}
 check(bytes(a)==bytes(b),"shadow-on/off byte identity isolated native seams");auto* h=dynamic_cast<Host*>(a.controllers[0].get());auto rows=h->collector.drain();for(auto e:rows.p->items)all.events.push_back(e);check(a.random.state==b.random.state,"shadow RNG isolation");traces.push_back(js::obj({{"tick",double(tick)},{"state_bytes",bytes(a)},{"target",double(a.resolve(a.units[0].target)?a.resolve(a.units[0].target)->id:0)}}));}
 check(a.shells.size()>=1,"neutral host launches without script policy");near(a.shells[0].pos.x,650,"locked absolute aim");near(a.shells[0].pos.y,400,"locked absolute aim y");check(a.shells[0].born>=.1,"native windup respected");return js::obj({{"events",all.drain()},{"traces",js::arr(std::move(traces))},{"shells",double(a.shells.size())}});}
void planner(js::V states){for(auto row:states.p->items){slice_teacher::PlannerInput input;input.units.t=js::num(js::get(row,"t"));input.units.width=1400;input.units.height=800;for(auto g:js::get(row,"guns").p->items){ObservedUnit u;u.id=UnitId(js::num(js::get(g,"id")));u.team=0;u.role=ObservedRole::Artillery;u.x=js::num(js::get(g,"x"));u.y=js::num(js::get(g,"y"));u.hp=u.maxhp=181;u.radius=10;u.range=320;u.speed=100;u.dmg=18;u.cdMax=1.4;u.target=UnitId(js::num(js::get(g,"target")));input.units.units.push_back(u);input.guns.push_back({u.id,u.target,js::num(js::get(g,"windup")),js::num(js::get(g,"lob")),js::num(js::get(g,"splash")),js::truth(js::get(g,"ready"))});}for(auto e:js::get(row,"enemies").p->items){ObservedUnit u;u.id=UnitId(js::num(js::get(e,"id")));u.team=1;u.role=ObservedRole::Ranged;u.x=js::num(js::get(e,"x"));u.y=js::num(js::get(e,"y"));u.hp=js::num(js::get(e,"hp"));u.maxhp=90;u.radius=9;u.range=280;u.speed=100;u.dmg=18;u.cdMax=1.4;u.vx=js::num(js::get(e,"vx"));u.vy=js::num(js::get(e,"vy"));input.units.units.push_back(u);}auto native=slice_teacher::project(input);auto copy=slice_teacher::project(input);artilleryVolley(native,0);slice_teacher::copiedPlanner(copy,0);auto qs=copy.packs[0].artilleryQueue;check(!qs.empty()&&qs.size()==native.shells.size(),"recorded native planner parity");for(size_t i=0;i<qs.size();++i){auto q=qs[i];auto sh=native.shells[i];check(copy.units[q.gun.slot].id==native.units[sh.source.slot].id,"gun assignment parity");near(q.point.x,sh.pos.x,"native aim x");near(q.point.y,sh.pos.y,"native aim y");near(q.prediction,sh.prediction,"native prediction");check(q.family==sh.family&&q.variant==sh.variant,"native family");near(q.at,input.units.t,"no coming/delayed schedule");}check(!copy.config->skills[0].rollout.enabled&&!copy.config->skills[0].artyFollow,"public options");}}
}
int main(){try{std::string line;std::getline(std::cin,line);auto req=js::parse(line);transitions();planner(js::get(req,"planner_states"));auto out=seams(Weights(js::get(req,"weights")));js::set(out,"integration",integratedFixtures(Weights(js::get(req,"weights"))));js::set(out,"checks",double(checks));js::set(out,"fights",0.);js::set(out,"scope","isolated seams + scripted coreStep lifecycle fixtures; not a fight or lab run");std::cout<<js::stringify(out)<<'\n';}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
