#include "host.h"
#include "teacher.h"
#include "controller_bridge.h"
#include "public_mechanics.h"
#include "artillery.h"
#include <algorithm>
#include <cmath>
namespace net_slice {
namespace {
Host* host(astelia::World& w,uint8_t team){return dynamic_cast<Host*>(w.controllers[team].get());}
const Host* host(const astelia::World& w,uint8_t team){return dynamic_cast<const Host*>(w.controllers[team].get());}
double n(js::V v,const char* k){return js::num(js::get(v,k));}
}
Host::Host(uint8_t side,std::shared_ptr<const Weights> w,bool teach):astelia::control::Controller(1,side),weights(std::move(w)),teacher(teach){if(!teacher&&!weights)throw std::invalid_argument("weights required");}
std::unique_ptr<astelia::control::Controller> Host::clone()const{auto h=std::make_unique<Host>(*this);h->views.clear();h->collector.events.clear();h->shadowLabels.clear();return h;}
void builtinDecision(astelia::World& w,uint32_t i){if((host(w,0)||host(w,1))&&w.units[i].role!=astelia::Role::Artillery){auto& u=w.units[i];astelia::applyControllerDecision(w,i,{u.pos.x,u.pos.y,0,0,0});w.state[i].decision.release=astelia::Release::None;}else astelia::decideUnit(w,i);}
void bind(astelia::World& w){for(uint8_t team=0;team<2;++team)if(auto* h=host(w,team)){++h->tick;h->views.clear();for(auto i:w.active)if(w.units[i].alive&&w.units[i].team==team&&w.units[i].role==astelia::Role::Artillery)h->views.push_back(snapshot(w,team,w.units[i].id,h->tick,h->fight,h->lastLaunch,h->consumed));h->consumed.clear();}}
void Host::prepare(const astelia::control::Observation&){std::vector<UnitId> ids;std::vector<astelia::Vec2> pos;std::vector<double> speeds,theta;std::map<UnitId,js::V> wires;for(auto s:views){UnitId id=UnitId(n(s,"self"));ids.push_back(id);wires[id]=s;for(auto u:js::get(s,"units").p->items)if(n(u,"id")==id){pos.push_back({n(u,"x"),n(u,"y")});speeds.push_back(n(u,"speed"));}if(!phases.count(id))phases[id]=double(id%16)*std::acos(-1)/8;if(!memory.count(id))memory[id]=std::vector<double>(8,0);theta.push_back(phases[id]);}
 // Prune dead identities; no physical-slot recurrence or resurrected state.
 for(auto it=phases.begin();it!=phases.end();)if(!wires.count(it->first)){memory.erase(it->first);heldFeatures.erase(it->first);heldForce.erase(it->first);assignments.erase(it->first);cache.erase(it->first);casts.erase(it->first);it=phases.erase(it);}else ++it;
 const bool decision=(tick-1)%6==0;std::vector<double> forcing;for(auto id:ids){if(decision||!heldFeatures.count(id))heldFeatures[id]=encode(wires.at(id)).x;if(weights&&weights->kind=="N2"){if((decision&&ablation!="no_geometry_to_mode")||!heldForce.count(id))heldForce[id]=std::tanh(weights->linear("force",heldFeatures.at(id))[0]);forcing.push_back(heldForce.at(id));}}
 auto ns=graph(pos,ids);if(fixedIds.empty()){fixedIds=ids;fixed=ns;}Graph frozen(ids.size());for(size_t i=0;i<ids.size();++i){auto found=std::find(fixedIds.begin(),fixedIds.end(),ids[i]);if(found!=fixedIds.end())for(auto j:fixed[size_t(found-fixedIds.begin())]){auto peer=std::find(ids.begin(),ids.end(),fixedIds.at(j));if(peer!=ids.end())frozen[i].push_back(size_t(peer-ids.begin()));}}
 std::vector<astelia::Vec2> drift(ids.size());if(weights&&weights->kind=="N2"&&!ids.empty()){theta=phaseStep(theta,pos,ids,weights->law(),forcing,n(views[0],"dt"),ablation,&frozen);drift=motion(theta,pos,ids,weights->law(),speeds,ablation);for(size_t i=0;i<ids.size();++i)phases[ids[i]]=theta[i];}
 std::map<UnitId,std::vector<double>> nextMemory;std::map<UnitId,Intent> next;
 for(size_t i=0;i<ids.size();++i){auto id=ids[i];if(teacher)continue;std::vector<double> state,message;auto enc=encode(wires.at(id));if(weights->kind=="N2"){state={std::sin(theta[i]),std::cos(theta[i]),0,0};for(auto j:ns[i]){state[2]+=std::sin(theta[j])/ns[i].size();state[3]+=std::cos(theta[j])/ns[i].size();}message.resize(12);for(size_t k=0;k<enc.enemies.size();++k){double sx=0,sy=0,count=0;for(auto j:ns[i])if(assignments[ids[j]]==enc.enemies[k]){sx+=std::sin(theta[j]);sy+=std::cos(theta[j]);++count;}double length=count?std::hypot(sx/count,sy/count):0;if(length>=1e-6)message[k]=(std::sin(theta[i])*sx+std::cos(theta[i])*sy)/(count*length);}}
  if(weights->kind=="N1r"){state=memory.at(id);message.resize(8);for(auto j:ns[i])for(size_t k=0;k<8;++k)message[k]+=memory.at(ids[j])[k]/ns[i].size();for(size_t c=0;c<enc.enemies.size();++c){std::vector<double> group(8);unsigned count=0;for(auto j:ns[i])if(assignments[ids[j]]==enc.enemies[c]){++count;for(size_t k=0;k<8;++k)group[k]+=memory.at(ids[j])[k];}if(count)for(size_t k=0;k<8;++k)message[(k+c)%8]+=group[k]/count/12;}for(auto& q:message)q/=2;}
  auto f=forward(*weights,heldFeatures.at(id),state,message);if(weights->kind=="N1r")nextMemory[id]=f.memory;if(!decision)continue;if(weights->kind=="N2"&&ablation=="no_mode_to_geometry"){auto blind=forward(*weights,heldFeatures.at(id),std::vector<double>(4,0),std::vector<double>(12,0));std::copy(blind.logits.begin(),blind.logits.begin()+33,f.logits.begin());}if(casts[id].pending){auto target=casts[id].lockedTarget;std::fill(f.logits.begin()+33,f.logits.begin()+46,-1e6);auto found=std::find(enc.enemies.begin(),enc.enemies.end(),target);f.logits[found==enc.enemies.end()?33:34+size_t(found-enc.enemies.begin())]=1e6;}
  auto c=intent(decode(wires.at(id),f.logits));if(weights->kind=="N2"){c.goal=c.goal+drift[i];if(std::hypot(drift[i].x,drift[i].y)>1e-12)c.multiplier=1;auto me=pos[i];auto delta=c.goal-me;double len=std::hypot(delta.x,delta.y);if(len>speeds[i]&&len>0)c.goal=me+delta*(speeds[i]/len);c.goal.x=astelia::clamp(c.goal.x,0,n(wires.at(id),"width"));c.goal.y=astelia::clamp(c.goal.y,0,n(wires.at(id),"height"));}next[id]=c;}
 for(auto m:nextMemory)memory[m.first]=m.second;
 if(teacher&&decision){auto labels=slice_teacher::query(views);next=labels.actions;for(auto e:labels.diagnostics)collector.record(tick,UnitId(n(e,"unit")),js::str(js::get(e,"stage")),js::get(e,"value"),tick,tick);}
 if(shadow&&decision)shadowLabels=slice_teacher::query(views).actions;
 if(decision){for(auto p:next){raw[p.first]=p.second;cache[p.first]=p.second;decisionTicks[p.first]=tick;collector.record(tick,p.first,"snapshot",wires.at(p.first));collector.record(tick,p.first,"intent",json(p.second),p.second.volley,tick);}}
 // Commit assignments simultaneously after readouts. Slot churn cannot remap IDs.
 for(auto p:next)assignments[p.first]=p.second.target;
}
astelia::UnitDecision Host::decide(const astelia::control::Observation& o,UnitId id){auto it=cache.find(id);if(it!=cache.end())return {it->second.goal.x,it->second.goal.y,it->second.multiplier,it->second.stop,it->second.target};for(auto u:o.units)if(u.id==id)return {u.x,u.y,0,0,0};throw std::invalid_argument("unit absent");}
void decide(astelia::World& w,uint32_t i){auto* h=host(w,w.units[i].team);if(!h){astelia::controllerDecision(w,i);return;}auto& u=w.units[i];if(u.role!=astelia::Role::Artillery){astelia::applyControllerDecision(w,i,{u.pos.x,u.pos.y,0,0,0});w.state[i].decision.release=astelia::Release::None;return;}auto c=h->cache.at(u.id);auto& cast=h->casts[u.id];if(cast.pending){c.target=cast.lockedTarget;if(!cast.aimLocked&&c.hasAim&&(c.release||(cast.readySince&&h->tick-cast.readySince>=6))){cast.lockedAim=c.aim;cast.aimLocked=true;}c.aim=cast.lockedAim;c.hasAim=true;}auto d=astelia::UnitDecision{c.goal.x,c.goal.y,c.multiplier,c.stop,c.target};auto legal=net_public::participate(w.observations[u.team],u.id,d);auto delta=astelia::Vec2{legal.x,legal.y}-u.pos;double travel=std::hypot(delta.x,delta.y);if(travel>u.speed&&travel>0){auto p=u.pos+delta*(u.speed/travel);legal.x=p.x;legal.y=p.y;}d=legal;c.goal={d.x,d.y};c.multiplier=d.multiplier;astelia::applyControllerDecision(w,i,d);auto& st=w.state[i];auto* target=w.resolve(u.target);double dist=target?std::hypot(target->pos.x-u.pos.x,target->pos.y-u.pos.y):INFINITY;double ad=c.hasAim?std::hypot(c.aim.x-u.pos.x,c.aim.y-u.pos.y):INFINITY;
 CastInput input{h->tick,u.alive,st.guardUntil>w.time||astelia::busyUnit(w,i),target&&target->alive,dist>=st.minRange&&dist<=u.range,ad>=st.minRange&&ad<=u.range&&c.aim.x>=0&&c.aim.y>=0&&c.aim.x<=w.config->width&&c.aim.y<=w.config->height,u.cooldown,st.energy,st.cost,st.prep,astelia::windup(w,i)};auto projected=cast.project(input,c);h->projected[u.id]=projected;if(!projected.release)st.decision.release=astelia::Release::None;
 if(projected.cancel){h->collector.record(h->tick,u.id,"cancel",js::obj({{"reason",projected.reason}}),cast.originVolley,cast.originDecision,cast.started);st.prep=0;h->consumed.insert(u.id);cast.consumedAck();}
 h->collector.record(h->tick,u.id,"projection",js::obj({{"raw",json(h->raw.at(u.id))},{"effective",json(c)},{"state",projected.state},{"reason",projected.reason},{"start",projected.start},{"release",projected.release}}),c.volley,h->decisionTicks.at(u.id),cast.started);
}
void prePrep(astelia::World& w){for(auto i:w.active)if(auto* h=host(w,w.units[i].team))if(w.units[i].role==astelia::Role::Artillery)w.state[i].castOk=h->projected.at(w.units[i].id).start;}
void postPrep(astelia::World& w){for(auto i:w.active)if(auto* h=host(w,w.units[i].team))if(w.units[i].role==astelia::Role::Artillery){auto id=w.units[i].id;auto& cast=h->casts[id];if(w.state[i].prep>0&&!cast.pending){cast.startedAck(h->tick,h->cache.at(id),h->decisionTicks.at(id));h->collector.record(h->tick,id,"cast_start",json(h->cache.at(id)),h->cache.at(id).volley,h->decisionTicks.at(id),cast.started);}if(w.state[i].prep>=astelia::windup(w,i)-1e-9&&w.state[i].prep>0&&!cast.readySince)cast.readySince=h->tick;}}
void consumedAck(astelia::World& w,uint32_t i){if(auto* h=host(w,w.units[i].team))if(w.units[i].role==astelia::Role::Artillery){auto id=w.units[i].id;h->consumed.insert(id);auto& cast=h->casts[id];h->collector.record(h->tick,id,"consume",js::obj({{"prep",w.state[i].prep}}),cast.originVolley,cast.originDecision,cast.started);/* retain lock through following fireShellAt hook */}}
void launchedAck(astelia::World& w,uint32_t i,const astelia::Shell& sh){if(auto* h=host(w,w.units[i].team))if(w.units[i].role==astelia::Role::Artillery){auto id=w.units[i].id;h->collector.record(h->tick,id,"launch",js::obj({{"aim",js::arr({sh.pos.x,sh.pos.y})},{"born",sh.born},{"landing_at",sh.at}}),h->casts[id].originVolley,h->casts[id].originDecision,h->casts[id].started);h->lastLaunch[id]=w.time;h->phases[id]=0;h->casts[id].consumedAck();}}
void finishTick(astelia::World& w){for(uint8_t team=0;team<2;++team)if(auto* h=host(w,team))for(auto id:h->consumed)if(h->casts[id].pending){h->collector.record(h->tick,id,"consumed_without_launch",js::obj({{"reason","native_target_range_at_act"}}),h->casts[id].originVolley,h->casts[id].originDecision,h->casts[id].started);h->casts[id].consumedAck();}}
bool aimReach(const astelia::World& w,uint32_t i){if(auto* h=host(w,w.units[i].team)){auto id=w.units[i].id;auto c=h->cache.at(id);const auto& cast=h->casts.at(id);auto p=cast.pending?cast.lockedAim:c.aim;double d=std::hypot(p.x-w.units[i].pos.x,p.y-w.units[i].pos.y);return c.hasAim&&d>=w.state[i].minRange&&d<=w.units[i].range;}return true;}
astelia::Vec2 aimPoint(const astelia::World& w,uint32_t i,astelia::Vec2 fallback){if(auto* h=host(w,w.units[i].team)){auto id=w.units[i].id;const auto& cast=h->casts.at(id);return cast.pending?cast.lockedAim:h->cache.at(id).aim;}return fallback;}
}
