#include "models.h"
#include <algorithm>
#include <cmath>
#include <set>
namespace net_slice {
using astelia::Vec2;using astelia::UnitId;
namespace {void finite(double x){if(!std::isfinite(x))throw std::runtime_error("nonfinite model");}double norm(Vec2 p){return std::hypot(p.x,p.y);}void lawCheck(const Law& p){for(double x:{p.A,p.B,p.J,p.K,p.omega,p.share})finite(x);if(p.A<0||p.A>1||p.B<0||p.B>1||p.J<0||p.J>1||p.K<0||p.K>2||std::abs(p.omega)>2||p.share<0||p.share>.25)throw std::invalid_argument("law envelope");}}
Graph graph(const std::vector<Vec2>& pos,const std::vector<UnitId>& ids){if(pos.size()!=ids.size()||std::set<UnitId>(ids.begin(),ids.end()).size()!=ids.size())throw std::invalid_argument("joint identity");Graph g(pos.size());for(size_t i=0;i<pos.size();++i){finite(pos[i].x);finite(pos[i].y);std::vector<std::pair<double,size_t>> ns;for(size_t j=0;j<pos.size();++j)if(i!=j)ns.push_back({norm(pos[j]-pos[i])/100,j});std::sort(ns.begin(),ns.end(),[&](auto a,auto b){return a.first<b.first||(a.first==b.first&&ids[a.second]<ids[b.second]);});for(size_t k=0;k<std::min(size_t(8),ns.size());++k)if(ns[k].first<3)g[i].push_back(ns[k].second);}return g;}
std::vector<double> phaseStep(const std::vector<double>& start,const std::vector<Vec2>& pos,const std::vector<UnitId>& ids,const Law& p,const std::vector<double>& f,double dt,const std::string& ab,const Graph* fixed){lawCheck(p);finite(dt);if(!(dt>0&&dt<=.2)||start.size()!=pos.size()||f.size()!=pos.size())throw std::invalid_argument("phase dimensions");const std::set<std::string> names={"intact","K0","frozen_phase","topology_only","no_geometry_to_mode","no_mode_to_geometry","no_reset"};if(!names.count(ab))throw std::invalid_argument("ablation");for(size_t i=0;i<start.size();++i){finite(start[i]);finite(f[i]);if(std::abs(f[i])>1)throw std::invalid_argument("forcing envelope");}auto ns=graph(pos,ids);if(ab=="frozen_phase")return start;if(ab=="topology_only"||ab=="no_geometry_to_mode"){if(!fixed||fixed->size()!=start.size())throw std::invalid_argument("fixed topology");ns=*fixed;}
 auto rhs=[&](const std::vector<double>& th){std::vector<double> d(th.size());for(size_t i=0;i<th.size();++i){double sum=0;for(auto j:ns[i]){if(j>=th.size()||j==i)throw std::invalid_argument("topology index");double r=norm(pos[j]-pos[i])/100;sum+=(ab=="no_geometry_to_mode"?1:std::exp(-r*r))*std::sin(th[j]-th[i]);}d[i]=p.omega+f[i]+(ab=="K0"?0:p.K)*(ns[i].empty()?0:sum/ns[i].size());finite(d[i]);if(std::abs(d[i])>5+1e-9)throw std::runtime_error("rate bound");}return d;};
 unsigned steps=unsigned(std::max(1.,std::ceil(dt*4/.25)));if(steps>4)throw std::runtime_error("substep cap");double h=dt/steps;auto a=start;auto shifted=[&](const std::vector<double>& k,double scale){auto b=a;for(size_t i=0;i<b.size();++i){b[i]+=scale*k[i];finite(b[i]);if(std::abs(b[i]-start[i])>5*dt+1e-9)throw std::runtime_error("stage bound");}return b;};for(unsigned s=0;s<steps;++s){auto k1=rhs(a),k2=rhs(shifted(k1,h/2)),k3=rhs(shifted(k2,h/2)),k4=rhs(shifted(k3,h));auto trial=a;for(size_t i=0;i<a.size();++i){trial[i]+=h*(k1[i]+2*k2[i]+2*k3[i]+k4[i])/6;finite(trial[i]);if(std::abs(trial[i]-start[i])>5*dt+1e-9)throw std::runtime_error("phase bound");}a=std::move(trial);}return a;
}
std::vector<Vec2> motion(const std::vector<double>& th,const std::vector<Vec2>& pos,const std::vector<UnitId>& ids,const Law& p,const std::vector<double>& speeds,const std::string& ab){lawCheck(p);if(th.size()!=pos.size()||speeds.size()!=pos.size())throw std::invalid_argument("motion dimensions");auto ns=graph(pos,ids);std::vector<Vec2> out(pos.size());for(size_t i=0;i<pos.size();++i){Vec2 sum;finite(th[i]);finite(speeds[i]);if(speeds[i]<0)throw std::invalid_argument("negative speed");for(auto j:ns[i]){Vec2 delta=(pos[j]-pos[i])*.01;double r=std::max(.1,norm(delta));sum=sum+delta*(1/r)*(p.A*(1+(ab=="no_mode_to_geometry"?0:p.J)*std::cos(th[j]-th[i]))-p.B/r);}if(!ns[i].empty())sum=sum*(1./ns[i].size());out[i]=sum*(p.share*speeds[i]/(1+norm(sum)));}return out;}
Weights::Weights(js::V v){if(js::str(js::get(v,"version"))!="NS1"||js::str(js::get(v,"dtype"))!="float64")throw std::invalid_argument("weight schema");kind=js::str(js::get(v,"kind"));if(kind!="N1"&&kind!="N1r"&&kind!="N2")throw std::invalid_argument("model kind");auto ps=js::get(v,"parameters");std::map<std::string,std::vector<size_t>> shapes={{"hidden.weight",{64,width+(kind=="N1"?0:kind=="N1r"?28:16)}},{"hidden.bias",{64}},{"readout.weight",{81,64}},{"readout.bias",{81}}};if(kind=="N1r"){shapes["recurrence.weight"]={8,64};shapes["recurrence.bias"]={8};}if(kind=="N2"){shapes["force.weight"]={1,width};shapes["force.bias"]={1};shapes["law"]={6};}if(js::keys(ps).size()!=shapes.size())throw std::invalid_argument("weight keys");for(auto entry:shapes){auto p=js::get(ps,entry.first);auto sh=js::get(p,"shape"),data=js::get(p,"values");if(sh.tag!=js::V::Heap||sh.p->items.size()!=entry.second.size()||data.tag!=js::V::Heap)throw std::invalid_argument("weight shape");size_t count=1;for(size_t i=0;i<entry.second.size();++i){if(js::num(sh.p->items[i])!=entry.second[i])throw std::invalid_argument("weight dimensions");count*=entry.second[i];}if(data.p->items.size()!=count)throw std::invalid_argument("weight count");for(auto x:data.p->items){double q=js::num(x);finite(q);values[entry.first].push_back(q);}}}
std::vector<double> Weights::linear(const std::string& name,const std::vector<double>& x)const{const auto& w=values.at(name+".weight");auto y=values.at(name+".bias");if(w.size()!=y.size()*x.size())throw std::invalid_argument("linear dimensions");for(double q:x)finite(q);for(size_t i=0;i<y.size();++i){for(size_t j=0;j<x.size();++j)y[i]+=w[i*x.size()+j]*x[j];finite(y[i]);}return y;}
Law Weights::law()const{const auto& a=values.at("law");auto sig=[](double x){return (1+std::tanh(x/2))/2;};return {sig(a[0]),sig(a[1]),sig(a[2]),2*sig(a[3]),2*std::tanh(a[4]),.25*sig(a[5])};}
Forward forward(const Weights& w,const std::vector<double>& x,const std::vector<double>& state,const std::vector<double>& message){if(x.size()!=width||(w.kind!="N1"&&state.size()+message.size()!=(w.kind=="N1r"?28:16)))throw std::invalid_argument("forward dimensions");auto input=x;if(w.kind!="N1"){input.insert(input.end(),state.begin(),state.end());input.insert(input.end(),message.begin(),message.end());}auto h=w.linear("hidden",input);for(auto& q:h)q=std::tanh(q);Forward out;out.logits=w.linear("readout",h);if(w.kind=="N1r"){out.memory=w.linear("recurrence",h);for(auto& q:out.memory)q=std::tanh(q);}if(w.kind=="N2"){if(state.size()!=4||message.size()!=12)throw std::invalid_argument("phase readout");for(unsigned i=46;i<48;++i)out.logits[i]=6*std::tanh(out.logits[i]/6)+2*state[1];}return out;}
}
