// Fixture RPC by default; physical collection can only be invoked explicitly.
#include "host.h"
#include "teacher.h"
#include "controller_bridge.h"
#include <fstream>
#include <iostream>
#include <sstream>
namespace {
using namespace net_slice;using js::V;
std::vector<double> array(V v){std::vector<double> out;for(auto x:v.p->items)out.push_back(js::num(x));return out;}
V arr(const std::vector<double>& xs){js::Args a;for(auto x:xs)a.push_back(x);return js::arr(std::move(a));}
V read(const std::string& path){std::ifstream f(path);if(!f)throw std::runtime_error("input file absent");std::stringstream s;s<<f.rdbuf();return js::parse(s.str());}
V rpc(V req){auto op=js::str(js::get(req,"operation"));if(op=="encode"){auto e=encode(js::get(req,"snapshot"));js::Args ids;for(auto id:e.enemies)ids.push_back(double(id));return js::obj({{"features",arr(e.x)},{"enemy_ids",js::arr(std::move(ids))},{"friend_overflow",bool(e.friendsOverflow)},{"enemy_overflow",bool(e.enemiesOverflow)},{"threat_overflow",double(e.threatOverflow)}});}if(op=="decode")return decode(js::get(req,"snapshot"),array(js::get(req,"logits")));
 if(op=="forward"){Weights w(js::get(req,"weights"));auto state=js::get(req,"state"),message=js::get(req,"message");auto out=forward(w,array(js::get(req,"features")),state.tag==V::Undefined?std::vector<double>{}:array(state),message.tag==V::Undefined?std::vector<double>{}:array(message));return js::obj({{"logits",arr(out.logits)},{"memory",arr(out.memory)}});}
 if(op=="dynamics"){std::vector<astelia::Vec2> pos;for(auto p:js::get(req,"positions").p->items)pos.push_back({js::num(p.p->items[0]),js::num(p.p->items[1])});std::vector<astelia::UnitId> ids;for(auto x:js::get(req,"ids").p->items)ids.push_back(astelia::UnitId(js::num(x)));auto ps=array(js::get(req,"law"));if(ps.size()!=6)throw std::invalid_argument("law count");Law law{ps[0],ps[1],ps[2],ps[3],ps[4],ps[5]};auto ab=js::str(js::get(req,"ablation"));auto fixed=graph(pos,ids);auto original=js::get(req,"fixed_positions");if(original.tag!=V::Undefined){std::vector<astelia::Vec2> p;for(auto x:original.p->items)p.push_back({js::num(x.p->items[0]),js::num(x.p->items[1])});fixed=graph(p,ids);}auto th=phaseStep(array(js::get(req,"phases")),pos,ids,law,array(js::get(req,"forcing")),js::num(js::get(req,"dt")),ab,&fixed);auto drift=motion(th,pos,ids,law,array(js::get(req,"speeds")),ab);js::Args ds;for(auto d:drift)ds.push_back(js::arr({d.x,d.y}));return js::obj({{"phases",arr(th)},{"motion",js::arr(std::move(ds))}});}
 if(op=="teacher"){auto out=slice_teacher::query(js::get(req,"snapshots").p->items);js::Args a;for(auto p:out.actions)a.push_back(js::obj({{"id",double(p.first)},{"action",json(p.second)}}));return js::obj({{"actions",js::arr(std::move(a))},{"aim_support_snaps",double(out.aimSupportSnaps)}});}
 if(op=="sequence"){Weights weights(js::get(req,"weights"));Host h(0,std::make_shared<const Weights>(weights));h.ablation=js::str(js::get(req,"ablation"));js::Args rows;for(auto frame:js::get(req,"frames").p->items){++h.tick;h.views=frame.p->items;h.prepare({});js::Args states,actions;for(auto p:h.phases)states.push_back(js::arr({double(p.first),p.second}));for(auto p:h.cache)actions.push_back(js::obj({{"id",double(p.first)},{"action",json(p.second)}}));rows.push_back(js::obj({{"phases",js::arr(std::move(states))},{"actions",js::arr(std::move(actions))}}));}return js::arr(std::move(rows));}
 throw std::invalid_argument("fixture operation only");}
void collect(V req){auto arm=js::str(js::get(req,"arm"));bool teacher=arm=="teacher";if(!teacher&&arm!="N1"&&arm!="N1r"&&arm!="N2")throw std::invalid_argument("collection arm");auto config=std::make_shared<astelia::Config>(astelia::gameConfig());config->seed=js::num(js::get(req,"seed"));config->abilities=false;config->duration=150;config->dt=1./30;config->width=1400;config->height=800;config->skills[0]=astelia::CombatSkills{};config->skills[1]=astelia::CombatSkills{};config->skills[1].dodgeShells=true;astelia::World w(config);bool mirror=js::truth(js::get(req,"orientation"));unsigned counts[2]={};
 for(auto u:js::get(req,"roster").p->items){auto side=uint8_t(js::num(js::get(u,"team")));auto role=int(js::num(js::get(u,"role")));if(side>1||role<0||role>2||++counts[side]>12)throw std::invalid_argument("slice roster");auto p=js::get(u,"position");double x=js::num(p.p->items[0]),y=js::num(p.p->items[1]);if(mirror)x=1400-x;w.add(side,astelia::Role(role),{x,y});}w.rebuildTeams();w.liveGrid.build(w.units,w.active,1400,800,40);
 std::shared_ptr<const Weights> weights;if(!teacher){weights=std::make_shared<const Weights>(read(js::str(js::get(req,"weights"))));if(weights->kind!=arm)throw std::invalid_argument("arm weights mismatch");}auto h=std::make_unique<Host>(0,weights,teacher);h->fight=js::str(js::get(req,"fight"));h->collector.fight=h->fight;h->shadow=js::truth(js::get(req,"shadow"));w.controllers[0]=std::move(h);
 while(!w.done()){astelia::coreStep(w);auto* host=dynamic_cast<Host*>(w.controllers[0].get());js::Args ids;for(auto s:host->views)ids.push_back(js::get(s,"self"));auto joint=host->views.empty()?V(nullptr):host->views[0];auto events=host->collector.drain();for(auto e:events.p->items)if(js::str(js::get(e,"stage"))=="snapshot")js::set(e,"value",js::obj({{"self",js::get(e,"unit")}}));if(joint.tag!=V::Null&&(js::get(joint,"units").p->items.size()>24||js::get(joint,"threats").p->items.size()>64))throw std::runtime_error("joint resource cap");js::Args shadow;for(auto p:host->shadowLabels)shadow.push_back(js::obj({{"id",double(p.first)},{"action",json(p.second)}}));auto row=js::stringify(js::obj({{"fight",host->fight},{"tick",double(host->tick)},{"joint",joint},{"gun_ids",js::arr(std::move(ids))},{"events",events},{"shadow",js::arr(std::move(shadow))}}));if(row.size()>65536)throw std::runtime_error("JSON record resource cap");std::cout<<row<<'\n';}
 std::cout<<js::stringify(js::obj({{"terminal",true},{"time",w.time},{"own_alive",double(w.survivors(0))},{"enemy_alive",double(w.survivors(1))},{"strict_win",w.survivors(0)>0&&w.survivors(1)==0&&w.time<150}}))<<'\n';}
}
int main(int argc,char** argv){try{bool collection=argc==2&&std::string(argv[1])=="--collect";if(argc>1&&!collection)throw std::invalid_argument("unknown flag");std::string line;while(std::getline(std::cin,line)){auto req=js::parse(line);if(collection)collect(req);else std::cout<<js::stringify(rpc(req))<<'\n';}}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
