#include "schema.h"
#include "artillery.h"
#include <set>
#include <algorithm>
#include <cmath>
namespace net_slice {
using namespace astelia;using js::V;
namespace {
const std::set<std::string> common={"id","team","role","x","y","vx","vy","hp","maxhp","radius","speed","range","min_range","damage","cooldown","cooldown_max","target"};
const std::set<std::string> extra={"prep","windup","time_rate","energy","cost","guard_until","busy","lob","splash","last_launch","consumed"};
double n(V v,const char* k){auto q=js::get(v,k);if(q.tag!=V::Number&&q.tag!=V::Boolean)throw std::invalid_argument(std::string("numeric field: ")+k);if(!std::isfinite(q.n))throw std::invalid_argument("nonfinite observation");return q.n;}
void keys(V v,const std::set<std::string>& expected){std::set<std::string> actual;for(auto k:js::keys(v))actual.insert(js::str(k));if(actual!=expected)throw std::invalid_argument("schema allowlist");}
void finiteTree(V v){if(v.tag==V::Number&&!std::isfinite(v.n))throw std::invalid_argument("nonfinite observation");if(v.tag==V::Heap){if(v.p->kind==js::Object::Array)for(auto q:v.p->items)finiteTree(q);else for(auto k:js::keys(v))finiteTree(js::get(v,js::str(k)));}}
V self(V s){for(auto u:js::get(s,"units").p->items)if(n(u,"id")==n(s,"self"))return u;throw std::invalid_argument("self absent");}
std::vector<V> sorted(V s,bool friends){auto me=self(s);std::vector<V> out;for(auto u:js::get(s,"units").p->items)if(n(u,"hp")>0&&n(u,"id")!=n(s,"self")&&((n(u,"team")==n(s,"side"))==friends))out.push_back(u);std::sort(out.begin(),out.end(),[&](V a,V b){auto d=[&](V u){return std::pow(n(u,"x")-n(me,"x"),2)+std::pow(n(u,"y")-n(me,"y"),2);};return d(a)<d(b)||(d(a)==d(b)&&n(a,"id")<n(b,"id"));});return out;}
int kind(V t){const std::string names[]={"shell","shot","field","cast","own_shell"};auto s=js::str(js::get(t,"kind"));for(int i=0;i<5;++i)if(s==names[i])return i;throw std::invalid_argument("threat kind");}
}
void validate(V s){auto integer=[](double x,double lo=0.,double hi=4294967295.){return std::isfinite(x)&&x>=lo&&x<=hi&&x==std::floor(x);};keys(s,{"version","fight","tick","side","self","t","dt","width","height","units","threats"});finiteTree(s);if(js::get(s,"fight").tag!=V::String||n(s,"t")<0||!integer(n(s,"tick"),1.,9007199254740991.)||!integer(n(s,"self"),1.)||js::str(js::get(s,"version"))!="NS1"||n(s,"tick")<1||(n(s,"side")!=0&&n(s,"side")!=1)||n(s,"width")<=0||n(s,"height")<=0||n(s,"dt")<=0||n(s,"dt")>.2)throw std::invalid_argument("schema root");std::set<double> ids;
 for(auto u:js::get(s,"units").p->items){auto expected=common;if(n(u,"team")==n(s,"side"))expected.insert(extra.begin(),extra.end());keys(u,expected);if(!integer(n(u,"id"),1.)||!integer(n(u,"target"))||n(u,"id")<=0||!ids.insert(n(u,"id")).second||(n(u,"team")!=0&&n(u,"team")!=1)||n(u,"role")<0||n(u,"role")>2||n(u,"role")!=std::floor(n(u,"role"))||n(u,"maxhp")<=0||n(u,"radius")<0||n(u,"speed")<0||n(u,"min_range")<0||n(u,"min_range")>n(u,"range"))throw std::invalid_argument("unit dimensions");if(n(u,"team")==n(s,"side")&&(n(u,"time_rate")<=0||n(u,"windup")<=0))throw std::invalid_argument("own cast dimensions");}
 auto me=self(s);if(n(me,"team")!=n(s,"side")||n(me,"role")!=2)throw std::invalid_argument("self own gun");for(auto t:js::get(s,"threats").p->items){keys(t,{"kind","ordinal","x","y","dx","dy","born","at","radius","speed","left","from","until","release_at","landing_at","caster","target","slow","damage"});if(!integer(n(t,"caster"))||!integer(n(t,"target"))||!integer(n(t,"ordinal"),1.))throw std::invalid_argument("threat identity");kind(t);}
}
Encoding encode(V s){validate(s);Encoding out;auto& x=out.x;auto me=self(s);double sign=n(s,"side")?-1:1,t=n(s,"t");auto f=sorted(s,true),e=sorted(s,false);out.friendsOverflow=f.size()>12;out.enemiesOverflow=e.size()>12;if(f.size()>12)f.resize(12);if(e.size()>12)e.resize(12);for(auto u:e)out.enemies.push_back(UnitId(n(u,"id")));
 auto pointer=[&](double id){if(!id)return 0.;auto it=std::find(out.enemies.begin(),out.enemies.end(),id);return it==out.enemies.end()?-1.:double(it-out.enemies.begin()+1)/12;};
 auto row=[&](V u){if(u.tag==V::Undefined){x.insert(x.end(),32,0);return;}x.insert(x.end(),{1.,double(n(u,"role")==0),double(n(u,"role")==1),double(n(u,"role")==2),sign*(n(u,"x")-n(me,"x"))/100,(n(u,"y")-n(me,"y"))/100,sign*n(u,"vx")/200,n(u,"vy")/200,n(u,"hp")/n(u,"maxhp"),n(u,"radius")/100,n(u,"speed")/200,n(u,"range")/1000,n(u,"min_range")/1000,n(u,"damage")/200,n(u,"cooldown")/10,n(u,"cooldown_max")/10,pointer(n(u,"target")),double(n(u,"target")==n(me,"id")),double(n(u,"team")==n(s,"side"))});if(n(u,"team")==n(s,"side")){bool reach=false;for(auto q:js::get(s,"units").p->items)if(n(q,"id")==n(u,"target")&&n(q,"hp")>0&&n(q,"team")!=n(u,"team")){double d=std::hypot(n(q,"x")-n(u,"x"),n(q,"y")-n(u,"y"));reach=d>=n(u,"min_range")&&d<=n(u,"range");}bool body=n(u,"guard_until")<=t&&!n(u,"busy");x.insert(x.end(),{n(u,"prep")/10,n(u,"windup")/10,n(u,"time_rate")/4,n(u,"energy")/1000,n(u,"cost")/1000,std::max(0.,n(u,"guard_until")-t)/10,n(u,"busy"),n(u,"lob")/1000,n(u,"splash")/100,double(body&&reach&&n(u,"prep")<=0&&n(u,"cooldown")<=0&&n(u,"energy")>=n(u,"cost")),double(body&&reach&&n(u,"prep")>0&&n(u,"prep")+n(s,"dt")*n(u,"time_rate")>=n(u,"windup")-1e-9),n(u,"last_launch")<0?-1.:(t-n(u,"last_launch"))/10,n(u,"consumed")});}else x.insert(x.end(),13,0);};row(me);for(auto& group:{f,e})for(unsigned i=0;i<12;++i)row(i<group.size()?group[i]:V{});
 auto urgency=[&](V th){int k=kind(th);double at=(k==0||k==4)?n(th,"at"):k==3?n(th,"landing_at"):k==2?std::max(t,n(th,"from")):t+std::max(0.,(n(me,"x")-n(th,"x"))*n(th,"dx")+(n(me,"y")-n(th,"y"))*n(th,"dy"))/std::max(n(th,"speed"),1e-6);bool inside=std::hypot(n(th,"x")-n(me,"x"),n(th,"y")-n(me,"y"))<=n(th,"radius")+n(me,"radius")+4;return std::make_tuple(!inside,std::max(0.,at-t),k,n(th,"ordinal"));};auto threats=js::get(s,"threats").p->items;std::sort(threats.begin(),threats.end(),[&](V a,V b){return urgency(a)<urgency(b);});out.threatOverflow=threats.size()>8?threats.size()-8:0;
 for(unsigned i=0;i<8;++i){if(i>=threats.size()){x.insert(x.end(),24,0);continue;}auto q=threats[i];int k=kind(q);x.insert(x.end(),{1.,double(k==0),double(k==1),double(k==2),double(k==3),sign*(n(q,"x")-n(me,"x"))/100,(n(q,"y")-n(me,"y"))/100,sign*n(q,"dx"),n(q,"dy"),(t-n(q,"born"))/10,(n(q,"at")-t)/10,n(q,"radius")/100,n(q,"speed")/1000,n(q,"left")/1000,(n(q,"from")-t)/10,(n(q,"until")-t)/10,(n(q,"release_at")-t)/10,(n(q,"landing_at")-t)/10,pointer(n(q,"caster")),double(n(q,"target")==n(me,"id")),double(!std::get<0>(urgency(q))),n(q,"slow"),double(k==4),n(q,"damage")/200});}
 double l=n(me,"x"),r=n(s,"width")-l;if(sign<0)std::swap(l,r);x.insert(x.end(),{t/150,n(s,"dt")*30,l/1000,r/1000,n(me,"y")/1000,(n(s,"height")-n(me,"y"))/1000});for(int team:{int(n(s,"side")),1-int(n(s,"side"))})for(int role=0;role<3;++role){unsigned count=0;for(auto u:js::get(s,"units").p->items)if(n(u,"hp")>0&&n(u,"team")==team&&n(u,"role")==role)++count;x.push_back(count/64.);}for(int team:{int(n(s,"side")),1-int(n(s,"side"))}){double sx=0,sy=0,count=0;for(auto u:js::get(s,"units").p->items)if(n(u,"hp")>0&&n(u,"team")==team){sx+=n(u,"x");sy+=n(u,"y");++count;}x.push_back(count?sign*(sx/count-n(me,"x"))/100:0);x.push_back(count?(sy/count-n(me,"y"))/100:0);}if(x.size()!=width)throw std::logic_error("width");return out;
}
V decode(V s,const std::vector<double>& y){validate(s);if(y.size()!=outputs)throw std::invalid_argument("output width");for(double q:y)if(!std::isfinite(q))throw std::runtime_error("numeric policy failure");auto me=self(s);double sign=n(s,"side")?-1:1;auto enemies=sorted(s,false);if(enemies.size()>12)enemies.resize(12);auto arg=[&](unsigned a,unsigned b){unsigned best=a;for(unsigned i=a+1;i<b;++i)if(y[i]>y[best])best=i;return best;};unsigned mi=arg(0,33),ti=arg(33,34+enemies.size())-33;V target=ti?enemies[ti-1]:V{};Vec2 goal{n(me,"x"),n(me,"y")};if(mi){double f=mi<=16?.6:1,angle=((mi-1)%16)*std::acos(-1)/8;goal=goal+Vec2{sign*std::cos(angle),std::sin(angle)}*(n(me,"speed")*f);goal.x=clamp(goal.x,n(me,"radius"),n(s,"width")-n(me,"radius"));goal.y=clamp(goal.y,n(me,"radius"),n(s,"height")-n(me,"radius"));}int ai=-1;Vec2 aim;for(unsigned i=0;ti&&i<33;++i){Vec2 p{n(target,"x"),n(target,"y")};if(i){double f=i<=16?.5:1,angle=((i-1)%16)*std::acos(-1)/8;p=p+Vec2{sign*std::cos(angle),std::sin(angle)}*(std::min(200.,n(me,"splash"))*f);}double d=std::hypot(p.x-n(me,"x"),p.y-n(me,"y"));if(p.x>=0&&p.x<=n(s,"width")&&p.y>=0&&p.y<=n(s,"height")&&d>=n(me,"min_range")&&d<=n(me,"range")&&(ai<0||y[48+i]>y[48+ai])){ai=i;aim=p;}}
 bool body=n(me,"guard_until")<=n(s,"t")&&!n(me,"busy");double distance=ti?std::hypot(n(target,"x")-n(me,"x"),n(target,"y")-n(me,"y")):INFINITY;bool legal=body&&ti&&ai>=0&&distance>=n(me,"min_range")&&distance<=n(me,"range");bool startOpportunity=legal&&n(me,"prep")<=0&&n(me,"cooldown")<=0&&n(me,"energy")>=n(me,"cost");bool releaseOpportunity=legal&&n(me,"prep")>0&&n(me,"prep")+n(s,"dt")*n(me,"time_rate")>=n(me,"windup")-1e-9;
 return js::obj({{"multiplier",double(mi!=0)},{"stop",0.},{"goal",js::arr({goal.x,goal.y})},{"target",ti?n(target,"id"):0.},{"start",y[46]>=0&&startOpportunity},{"release",y[47]>=0&&releaseOpportunity},{"start_opportunity",startOpportunity},{"release_opportunity",releaseOpportunity},{"aim",ai>=0?js::arr({aim.x,aim.y}):V(nullptr)},{"move_index",double(mi)},{"aim_index",ai<0?V(nullptr):V(double(ai))},{"target_index",double(ti)},{"volley",0.}});
}
V snapshot(const World& w,uint8_t side,UnitId id,uint64_t tick,const std::string& fight,const std::map<UnitId,double>& launched,const std::set<UnitId>& consumed){js::Args units,threats;uint64_t ordinal=0;auto threat=[&](const char* kind,Vec2 p,Vec2 dir,double born,double at,double radius,double speed,double left,double from,double until,double release,double landing,UnitId caster,UnitId target,bool slow,double damage=0){threats.push_back(js::obj({{"kind",kind},{"ordinal",double(++ordinal)},{"x",p.x},{"y",p.y},{"dx",dir.x},{"dy",dir.y},{"born",born},{"at",at},{"radius",radius},{"speed",speed},{"left",left},{"from",from},{"until",until},{"release_at",release},{"landing_at",landing},{"caster",double(caster)},{"target",double(target)},{"slow",slow},{"damage",damage}}));};
 for(auto i:w.active){const auto& u=w.units[i];if(!u.alive)continue;const auto& st=w.state[i];const auto* target=w.resolve(u.target);V row=js::obj({{"id",double(u.id)},{"team",double(u.team)},{"role",double(melee(u.role)?0:u.role==Role::Artillery?2:1)},{"x",u.pos.x},{"y",u.pos.y},{"vx",u.velocity.x},{"vy",u.velocity.y},{"hp",u.hp},{"maxhp",u.maxhp},{"radius",u.radius},{"speed",u.speed},{"range",u.range},{"min_range",st.minRange},{"damage",u.damage},{"cooldown",u.cooldown},{"cooldown_max",st.cooldownMax},{"target",target&&target->alive?double(target->id):0.}});
 if(u.team==side){for(auto kv:std::map<std::string,double>{{"prep",st.prep},{"windup",std::max(1e-9,windup(w,i))},{"time_rate",st.timeRate},{"energy",st.energy},{"cost",st.cost},{"guard_until",st.guardUntil},{"busy",double(busyUnit(w,i))},{"lob",lobSpeed(w,i)},{"splash",blastRadius(w,i)},{"last_launch",launched.count(u.id)?launched.at(u.id):-1},{"consumed",double(consumed.count(u.id)>0)}})js::set(row,kv.first,kv.second);}
 else if(u.role==Role::Artillery&&st.prep>0&&target&&target->alive&&target->team==side){double release=w.time+std::max(0.,windup(w,i)-st.prep)/st.timeRate;double landing=release+std::hypot(target->pos.x-u.pos.x,target->pos.y-u.pos.y)/lobSpeed(w,i);threat("cast",target->pos,{},w.time,landing,blastRadius(w,i),0,0,0,0,release,landing,u.id,target->id,false);}units.push_back(row);}
 for(auto& sh:w.shells){auto* src=w.resolve(sh.source);if(src&&sh.at>w.time&&!sh.done)threat(src->team==side?"own_shell":"shell",sh.pos,{},sh.born,sh.at,sh.splash,0,0,0,0,0,sh.at,src->id,0,sh.slow,sh.damage);}
 for(auto& sh:w.shots){auto* src=w.resolve(sh.source);if(src&&src->team!=side&&sh.aimed)threat("shot",sh.pos,sh.direction,sh.born,0,3,sh.speed,sh.left,0,0,0,0,src->id,0,false);}
 for(auto& f:w.fields)if(f.team!=side)threat("field",f.pos,{},f.from,0,f.radius,0,0,f.from,f.until,0,0,0,0,true);
 return js::obj({{"version","NS1"},{"fight",fight},{"tick",double(tick)},{"side",double(side)},{"self",double(id)},{"t",w.time},{"dt",w.dt},{"width",w.config->width},{"height",w.config->height},{"units",js::arr(std::move(units))},{"threats",js::arr(std::move(threats))}});
}
}
