"""Read the one-shot receipt only. No integration, estimator, or verdict recomputation."""
import gzip,hashlib,json,math
from pathlib import Path
OUT=Path(__file__).resolve().parent
HERE=OUT.parent
r=json.loads((OUT/'RUN_RECEIPT.json').read_text());results=r['results'];t=r['timings']
def write(name,value):
 with (OUT/name).open('x') as f:json.dump(value,f,indent=2,sort_keys=True,allow_nan=False);f.write('\n')
def stripped(x):
 if isinstance(x,dict):return {k:stripped(v) for k,v in x.items() if k not in ('records','stages','phases','paths','episodes','native','reference','identity_snapshot')}
 if isinstance(x,list):return [stripped(v) for v in x]
 return x
summary=stripped(r)
geometry={}
for name,row in results['F1']['configurations'].items():
 runs=row.get('runs',{'default':row})
 for scale,v in runs.items():
  records=v['records'];key=name if scale=='default' else name+'/lambda='+scale
  initial_span={'F1a':0,'F1b':1.112,'F1c':5*.556,'F1d':1.112}[name]
  geometry[key]=dict(first_record_time=records[0]['time'],first_record_positions=records[0]['positions'],last_record_positions=records[-1]['positions'],positions_recorded=True,phase_and_motion_topology_recorded=True)
  if name!='F1d':
   early=records[0];last=records[-1]
   geometry[key].update(initial_literal_span=initial_span,first_record_geometry=early['ordinary_span'],end_geometry=last['ordinary_span'],source_access=sum(v['drive_access'] for v in records)/len(records),source_site_distance_range=[min(v['source_site_distance'] for v in records),max(v['source_site_distance'] for v in records)],minimum_distances={k:min(v['minimum_distances'][k] for v in records if v['minimum_distances'][k] is not None) for k in ('element_element','element_site')},pin_invariant=all(v['pin_invariant'] for v in records),direct_source_output_fraction=sum(str(len(v['positions'])-1) in v['neighbors'].get('0',[]) or len(v['positions'])-1 in v['neighbors'].get('0',[]) for v in records)/len(records),weights_recorded=True)
  else:
   geometry[key].update(effective_root_site0_fraction=sum(bool(v['effective_roots'].get('0',[])) for v in records)/len(records),site0_output_path_fraction=sum(v['paths'][0] for v in records)/len(records),mean_site0_drive_exposure=sum(v['exposure']['0']['drive'] for v in records)/len(records))
summary['geometry']=geometry
n1dist={name:[{k:min(v['minimum_distances'][k] for v in records if v['minimum_distances'][k] is not None) if any(v['minimum_distances'][k] is not None for v in records) else None for k in ('element_element','element_site')} for records in row['records']] for name,row in results['N1']['cases'].items()}
summary['N1_minimum_distances']=n1dist
f1c=results['F1']['configurations']['F1c']['records']
wrap=lambda x:(x+math.pi)%(2*math.pi)-math.pi
summary['F1c_descriptive_after_deadline']=dict(first_entry_anytime=next((v['time'] for v in f1c if v['time']>8 and abs(wrap(v['beta']-math.pi/2))<=.3),None),deadline_error=abs(wrap(f1c[159]['beta']-math.pi/2)),used_in_verdict=False)
write('MEASURED_SUMMARY.json',summary)
rates={n:t[n]['awake_seconds']/1600 for n in ('F1a','F1b','F1c')}
rates['F1d_two_scales']=t['F1d']['awake_seconds']/3200;rates['F2']=t['F2']['awake_seconds']/320
f4_rate=t['F4']['awake_seconds']/10
projection=dict(status='A7_PARTIAL_TOTAL_NOT_QUALIFIED_FROM_MEASURED_FIXTURES',reason='F1c blocks F5-F9: growth, qualification, recovery and grown-population assay rates unmeasured',measured_frozen_seconds_per_world_step=rates,N1_seconds_per_RK4_substep=t['N1']['awake_seconds']/20000,F4_composite_seconds_per_episode=f4_rate,F4_proxy_limitation='Five native and five reference perceive assays on a two-member scaffold, plus setup, stage diagnostics, donor capture, relays, finite serialization and instrumentation. Not a native grown-population rate.',workload=dict(trainings=48,training_world_steps=15360000,growth_checks=76800,qualification_starts=8512,snapshot_assay_episodes_max=327680,total_assay_episodes_max_all_four_tasks=434176,site_body_off_added_episodes=2048,site_body_off_episodes_per_intact_training=128,intact_trainings=16,donor_capture_episodes=8192),unqualified_arithmetic_proxies=dict(frozen_training_hours_by_fixture={n:rate*15360000/3600 for n,rate in rates.items()},assay_hours_using_F4_composite_rate=434176*f4_rate/3600,site_body_off_added_seconds_using_F4_composite_rate=2048*f4_rate),qualified_total_hours=None,lower_or_upper_bound=False,development='BLOCKED_F1c_NOT_RUN',instrumentation='Passive F1a-c line timestamps and per-method wrappers; observed rates include observer overhead. No benchmark, development or panel executed.')
write('A7_DEVELOPMENT_COST_PROJECTION.json',projection)
lines=['FIXTURES_FAIL','', 'Revision 7.3 fixtures executed once at pin `'+r['identity_snapshot']['pin_sha256']+'`. Standing grant: `docs/decisions/0031-owner-run-approval-policy.md`; integration review: `evidence/tactical_composition_demo/growing_shapes_review_claude/REV7_FIXTURE_READINESS.md` (READY_FOR_FIXTURES, Claude). All 68 pinned inputs matched before execution and after completion. The harness ran unchanged under `caffeinate -i`; the wrapper delegates sequencing and verdicts to `Harness.run_all` and only observes timing and saves evidence. No code defect or INVALID was recorded.','', 'Pre-run workload estimate: 5–30 serial minutes, provisional and candidate-dependent, below one hour. Source: integration report and static harness workload; no calibration benchmark or rehearsal was run. The actual stop shortened execution to '+str(round(r['total']['awake_seconds'],6))+' s awake / '+str(r['total']['elapsed_utc_seconds'])+' s elapsed UTC ('+r['total']['start_utc']+' → '+r['total']['end_utc']+').','', 'N1 PASS admits F1. F1a and F1b PASS; F1c FAIL because no entry occurs by t=16 s and the required hold is not established. F1d remains descriptive. F2, F3 and F4 subsequently PASS. The implemented `F1_F4_failed` stop row blocks F5 and development; all dependent later fixtures are NOT_RUN.','', '| Fixture | Verdict | Start UTC | End UTC | Awake s | Elapsed UTC s |','|---|---|---|---|---:|---:|']
for n in ('N1','F1a','F1b','F1c','F1d','F1','F2','F3','F4'):
 v=results['F1']['configurations'][n]['verdict'] if n.startswith('F1') and n!='F1' else results[n]['verdict']
 c=t[n];lines.append(f"| {n} | {v} | {c['start_utc']} | {c['end_utc']} | {c['awake_seconds']:.6f} | {c['elapsed_utc_seconds']:.6f} |")
lines += ['', 'F1 aggregate includes F1a–d; do not add it again to those sub-fixture costs. F1a–c timestamps cover construction, integration and measurement up to final close. Fixture method costs exclude writing their compressed raw traces; total cost includes gate and receipt work through harness completion. Awake uses mach_absolute_time (excludes sleep); continuous uses mach_continuous_time; elapsed uses UTC timestamps. All per-fixture timing records are retained.','', 'N1 criterion (9.2 + 10.3): matched h=.02 and .005 endpoints, maximum wrapped and unwrapped carrier-relative phase differences ≤.01 rad, free-position error ≤.01 m.u., both topology agreements ≥.99, pins invariant, applicable entry differences ≤.1 s (both missing passes this numerical metric).','', '| Case | Wrapped rad | Unwrapped rad | Position m.u. | Entry times, coarse/fine s | Nθ | Nx | Pins |','|---|---:|---:|---:|---|---:|---:|---|']
for name,c in results['N1']['cases'].items():lines.append(f"| {name} | {c['maximum_wrapped_phase']:.9g} | {c['maximum_unwrapped_phase']:.9g} | {c['maximum_free_position']:.9g} | {c['entry_times'] if c['entry_applicable'] else 'N/A'} | {c['Ntheta_agreement']} | {c['Nx_agreement']} | {c['pins_invariant']} |")
lines+=['','All five N1 cases PASS; both integrations record 160 endpoints per case. N1a records one individual fast-transient frame in each integration; the others record zero. Minimum distances (element-element / element-site; None means no pair) in coarse/fine integrations:']
for n,d in n1dist.items():lines.append(f'- {n}: '+json.dumps(d,separators=(',',':')))
lines+=['', 'F1a/b criterion: after the step at t=8 s, first entry into the ≤.3 rad tolerance by t=16 s, held at every endpoint to t=16 s, and effective-root path exposure ≥.8 over 1,600 world steps. F1c adds hold through t=24 s, source access ≥.8, and response persistence ≥.8 over [16,160] inclusive.','', '| Case | Entry s | Delay s | Required hold | Path fraction | Access fraction | Response persistence |','|---|---:|---:|---|---:|---:|---:|']
for n in ('F1a','F1b','F1c'):
 c=results['F1']['configurations'][n];lines.append(f"| {n} | {c['first_entry_time']} | {c['delay']} | {c.get('continuous_to_24',c.get('continuous_from_first_entry'))} | {c['path_exposure']} | {geometry[n]['source_access']} | {c.get('response_persistence','N/A')} |")
lines+=['', 'F1c descriptive timing after the failed deadline: '+json.dumps(summary['F1c_descriptive_after_deadline'])+'. This does not change its recorded FAIL.','', 'Compaction geometry is measured on ordinary members, excluding O. The first-record values below are at t=.1 s, not t=0. All pins remain invariant. Full positions, phase/motion neighbour lists, distances, shortcuts and link weights remain in F1 raw evidence.','', '| Case | Literal initial span | t=.1 span | t=160 span | t=.1 radius | t=160 radius | Source/site distance range | Min element/element | Min element/site |','|---|---:|---:|---:|---:|---:|---|---:|---:|']
for n in ('F1a','F1b','F1c'):
 g=geometry[n];a=g['first_record_geometry'];b=g['end_geometry'];d=g['minimum_distances'];lines.append(f"| {n} | {g['initial_literal_span']:.9g} | {a['span']:.9g} | {b['span']:.9g} | {a['radius']:.9g} | {b['radius']:.9g} | {g['source_site_distance_range']} | {d['element_element']:.9g} | {d['element_site']:.9g} |")
lines+=['', 'F1d compares the F1b scaffold at λ=1 versus 8 descriptively; no gate cut is applied. Carrier π, motion and clock are unchanged.','', '| λ | Entry s | Delay s | Hold to 16 | Error at 16 rad | Effective-root fraction site0 | Output-path fraction site0 | Mean site0 exposure |','|---|---:|---:|---|---:|---:|---:|---:|']
for scale,c in results['F1']['configurations']['F1d']['runs'].items():
 g=geometry['F1d/lambda='+scale];lines.append(f"| {scale} | {c['first_entry_time']} | {c['delay']} | {c['continuous_from_first_entry']} | {c['deadline_error']:.9g} | {g['effective_root_site0_fraction']} | {g['site0_output_path_fraction']} | {g['mean_site0_drive_exposure']:.9g} |")
lines+=['', 'F2 exactness criterion: empty default is exactly angle=0, magnitude=0 with no path; disconnected output phase streams must be bitwise identical with/without the input step and have no path over 16 s. Measured: empty_default=True; bitwise_identical=True; 160 phases per stream, zero path steps in both. PASS.','', 'F3 exactness criterion: drive contribution at O is +0.0 exactly at every RK4 stage. Measured: five diagnostic substeps × four stages, all 20 output drive terms have the identical float.hex of +0.0. PASS.','', 'F4 exactness criterion: output-channel lesion leaves zero internal phase coupling at all 20 stages; site0/oracle relay angles equal the wrapped selected drive exactly; all five native/reference assays match at 160 decisions each (angle tolerance 1e-12, magnitude/choice/path/output exact). Measured: all lesion output internal terms equal 0; site0='+str(results['F4']['site0'])+', oracle='+str(results['F4']['oracle'])+'. PASS.','', '| Assay | Decisions | Maximum angle error rad | Status |','|---|---:|---:|---|']
for n,c in results['F4']['assay_parity'].items():lines.append(f"| {n} | {c['decisions']} | {c['maximum_wrapped_angle_error']:.9g} | {c['status']} |")
lines+=['', '| Fixture | Criterion | Measured values / cost | Stop outcome |','|---|---|---|---|', '| F5(i), F5(ii) | Both starts: required birth (B-out i / B-path ii), max E≥.5, A≥.3, B≥.3; checkpoints 40/45/50 | NOT_RUN: A, B, E, birth events and not-qualified fraction are null/unmeasured; no timestamps or cost | Blocked by F1c; both starts retained as NOT_RUN |', '| F6 | Descriptive memory correlation and encoding/retention; 120 checkpoint copies plus 20 baseline copies | NOT_RUN; no measured correlation or cost | F5 prerequisite blocked |', '| F7 | All requested control-M B1 births matched; unmatched count=0 | NOT_RUN; requested/matched/fraction null; no cost | F5 prerequisite blocked; no matching claim |', '| F8 | Descriptive continued-live reward/growth, 20 move then 20 remember_static episodes | NOT_RUN; no eligibility/reward/demand measurements or cost | F5/F7 prerequisites blocked |', '| F9 | Four descriptive synthetic decoder observations | NOT_RUN; no actions or cost | Earlier sequence stopped |','', 'F5 not-qualified-window summary is NOT_RUN, never zero: no starts or valid-window denominator exists for either start. Its intended descriptive output (used_in_verdict=False) covers (0,640], (640,720], (720,800] s by qualification-check endpoint, retains small-cohort starts in the denominator, reports null without windows, and counts each fast-transient world frame once. No recovery exclusions or fraction can be inferred from N1.','', 'Stop rows: only `F1_F4_failed=YES` fired (implementer: Block F5 and development; report). Integration/readiness mismatch, source/config/inventory mismatch, N1 failure/invalid, fixture invalid and post-result protocol change are NO. F5 failure and F7 unmatched are NOT_EVALUATED, because neither ran. All development-only rows are NOT_EVALUATED. The unchanged implemented stop output is retained in RUN_RECEIPT. Development is blocked, and no next run is started.','', 'A7 development-run projection: partial, total NOT_QUALIFIED. The 48-training workload has 15,360,000 training world steps, 76,800 growth checks, 8,512 qualification starts, up to 327,680 snapshot assays, and up to 434,176 total assay episodes if all four tasks are usable. This includes 2,048 site-body-off episodes (128 × 16 intact trainings); donor captures add 8,192 episodes. These are workload counts, not authorization.','', '| Measured fixed-scaffold rate source | Awake seconds / world step | Arithmetic for 15,360,000 steps, hours |','|---|---:|---:|']
for n,rate in rates.items():lines.append(f"| {n} | {rate:.9g} | {rate*15360000/3600:.6f} |")
lines+=['', f"F4 composite rate is {f4_rate:.9g} s/assay episode (five native plus five reference assays, setup/diagnostics/relays/donor capture and measurement overhead included). Applying it mechanically to 434,176 episodes gives {434176*f4_rate/3600:.6f} hours; the 2,048 site-body-off addition alone gives {2048*f4_rate:.6f} seconds. These are explicitly unqualified arithmetic proxies, not native evaluation rates, estimates of grown-population work, or bounds.", '', 'No qualified total is possible: live growth, B-path search, qualification, recovery/admissibility and native assays at grown populations were blocked and are unmeasured. Observer overhead is included in the rates and is not subtracted. No additional run was used to price missing stages. A7_DEVELOPMENT_COST_PROJECTION.json records the formulas and null qualified_total_hours.','', 'Evidence: `rev7_fixture_run_20261006/RUN_RECEIPT.json` preserves the full original result and verdict (over 50 MB; excluded from delivery and indexed by SHA256); per-fixture gzip traces and MEASURED_SUMMARY.json provide small transferable evidence. PREFLIGHT_IDENTITY, START_IDENTITY, PRE_EXECUTION_SEED_INVENTORY, all timing files, EXECUTION_LOG and PRESERVATION bind the run. Outside-scope tracked bytes (6,631 files), staged diff, execution inputs and docs/PLAN_CURRENT.md remain unchanged. No training, development, evaluation panel, judging entropy, registration, code edit, fixture replay or rerun occurred.']
(HERE/'REV7_FIXTURE_REPORT.md').write_text('\n'.join(lines)+'\n')
print(json.dumps({'report':str(HERE/'REV7_FIXTURE_REPORT.md'),'projection':projection['status'],'F1c_late_entry':summary['F1c_descriptive_after_deadline']}))
