"""Semantic mutants for the full R4 field apparatus; only pipeline execution."""
MUTANTS={
 'cached_drive_clock_ignored':('native/c6_r4/field.cpp','it->start==start','true'),
 'cached_drive_phases_ignored':('native/c6_r4/field.cpp','std::equal(it->psi.begin(),it->psi.end(),psi)','true'),
 'cached_drive_amplitude_ignored':('native/c6_r4/field.cpp','it->amplitude==amplitude','true'),
 'overflow_difference_ignored':('geomind/c6_r4_field_assay.py',"if not np.isfinite(delta).all():raise NumericalFailure('nonfinite full-scope difference')",'pass'),
 'nonfinite_scale_ignored':('geomind/c6_r4_field_assay.py','not np.isfinite(L) or L<=0','L<=0'),
 'outgoing_cache_sigma_ignored':('geomind/c6_r4_field.py',"'sigma':owner.model['sigma'],","'sigma':0.,"),
 'streaming_samples_pin_full_blocks':('geomind/c6_r4_field_assay.py','collected[k].extend(flow[stride::stride].copy())','collected[k].extend(flow[stride::stride])'),
 'nonzero_sham':('native/c6_r4/field.cpp','std::max(0.,masks[c*n+i])','std::abs(masks[c*n+i])'),
 'masked_denominator':('native/c6_r4/field.cpp','p[3]/selected*ow','p[3]/n*ow'),
 'no_r_J_leak':('native/c6_r4/field.cpp','(mode==1||mode==3)?0.:p[7]','mode==3?0.:p[7]'),
 'no_r_K_leak':('native/c6_r4/field.cpp','K=mode==1?0.:p[8]','K=p[8]'),
 'gm_incoming_weight_leak':('native/c6_r4/field.cpp','mode==2?origins+2*n*c:x','x'),
 'phase_sign':('native/c6_r4/field.cpp','std::sin(phase)/(n-1)','std::sin(-phase)/(n-1)'),
 'carrier_contamination':('native/c6_r4/field.cpp','const double* z=v+3*n','const double* z=y'),
 'continuation_in_measurement':('geomind/c6_r4_field_analysis.py',"return sum(bool(e['qualification']['qualified']) for e in episodes if e['episode'] in (1,2,3,4))/4","return sum(bool(e['qualification']['qualified']) for e in episodes if e['episode'] in (0,1,2,3))/4"),
 'small_positive_margin_pass':('geomind/c6_r4_field_analysis.py',"if ci[0]>margin or ci[1]<-margin:","if ci[0]>0 or ci[1]<0:"),
 'negative_change_ignored':('geomind/c6_r4_field_analysis.py',"if ci[0]>margin or ci[1]<-margin:","if ci[0]>margin:"),
 'quorum_ignored':('geomind/c6_r4_field_analysis.py',"if ci is None or n<minimum:","if ci is None:"),
 'witness_shortfall_ignored':('geomind/c6_r4_field_analysis.py',"if witnesses<10 or any(v!='SUPPORTED_WITHIN_SCOPE' for v in required):","if any(v!='SUPPORTED_WITHIN_SCOPE' for v in required):"),
 'engineering_gate_ignored':('geomind/c6_r4_field_analysis.py',"if not valid or n<10:","if n<10:"),
 'false_enablement_allowed':('geomind/c6_r4_field_analysis.py',"if row['enabled_witness'] and (not row['chain_complete'] or any(c.get('witness_tuple')!=[True,False,False] for c in row['turns'])):","if False:"),
 'enabled_subset_cherry_pick':('geomind/c6_r4_field_analysis.py',"chain=[r['world'] for r in rows if r['chain_complete']]","chain=[r['world'] for r in rows if r['enabled_witness']]"),
 'restaged_next_source':('geomind/c6_r4_field_analysis.py',"if i==0 and link['next_operation_ids']!=row['turns'][1]['before_ids']:","if False:"),
 'sham_check_omitted':('geomind/c6_r4_field_analysis.py',"if intact['source_trace_hash_by_dt']!=sham['source_trace_hash_by_dt'] or any(sham['output_max_by_dt']):","if False:"),
 'field_numerics_ignored':('geomind/c6_r4_field_assay.py',"passed=all(maxima[k]<=limits[k] for k in maxima)","passed=True"),
 'causal_ablation_ignored':('geomind/c6_r4_field_assay.py',"if max(ablated)>max(iv['vanish_absolute'],iv['vanish_fraction']*smallest):","if False:"),
 'causal_spread_ignored':('geomind/c6_r4_field_assay.py',"if all(decisions) and max(intact)-smallest>iv['relative_spread']*smallest:","if False:"),
 'rolling_clock_duplicate':('geomind/c6_r4_field_protocol.py',"xs=np.concatenate((px[-window-1:-1],ox));ths=np.concatenate((pt[-window-1:-1],ot));rows=[]","xs=np.concatenate((px[-window:],ox));ths=np.concatenate((pt[-window:],ot));rows=[]"),
 'publication_link_ignored':('geomind/c6_r4_field_analysis.py',"p.get('candidate')==q['selected_identity']","True"),
 'publication_S_ignored':('geomind/c6_r4_field_analysis.py',"p.get('S')==matches[0]['stats']","True"),
 'loaded_native_hash_ignored':('geomind/c6_r4_field.py',"if record['source_sha256']!=source or hashlib.sha256(build.LIBRARY.read_bytes()).hexdigest()!=record['binary_sha256']:","if False:"),
 'complex_imaginary_hash_omitted':('geomind/c6_r4_field.py',"arrays.extend((r,im));names.extend", "arrays.extend((r,r));names.extend"),
 'selection_storage_order':('geomind/c6_r4_field_assay.py',"tuple(sorted(tokens[i] for i in r['members']))", "tuple(sorted(r['members']))"),
 'endpoint_omission':('geomind/c6_r4_field_analysis.py',"+GLOBAL+ARM_A", "+GLOBAL+ARM_A[:-1]"),
 'primary_endpoint_omission':('geomind/c6_r4_field_analysis.py','ENDPOINTS=PRIMARY+', 'ENDPOINTS=PRIMARY[1:]+'),
 'diagnostic_endpoint_omission':('geomind/c6_r4_field_analysis.py','for name in TURN_DIAGNOSTICS)+GLOBAL','for name in TURN_DIAGNOSTICS[1:])+GLOBAL'),
 'early_emission':('geomind/c6_r4_field_protocol.py',"flow=grid.run(grid.s['formation'],scope+'/prefix')", "for o in grid.owners:o.cohorts[-1].selected=tuple(range(len(o.cohorts[-1].theta)));o.cohorts[-1].output=1.\n    flow=grid.run(grid.s['formation'],scope+'/prefix')"),
 'unmatched_episode_inputs':('geomind/c6_r4_field_analysis.py',"if a['inputs']!=b['inputs'] or a['perturbations']!=b['perturbations']:","if False:"),
 'episode_continuation_cherry_pick':('geomind/c6_r4_field_protocol.py',"if condition=='intact' and episode==0 and q['qualified']:","if condition=='intact' and q['qualified']:"),
 'physical_loss_misclassified':('geomind/c6_r4_field_protocol.py',"if not eligible:return cell,None", "if not eligible:raise ValueError('physical loss is engineering failure')"),
 'spatial_kicks_untransformed':('geomind/c6_r4_field_protocol.py',"pert['position']=pert['position']@rotation.T", "pert['position']=pert['position']"),
 'probe_phase_untransformed':('geomind/c6_r4_field_assay.py','impulse=.05*np.exp(1j*(alpha+o.phase_origin+quadrature*np.pi/2))','impulse=.05*np.exp(1j*(alpha+quadrature*np.pi/2))'),
 'environment_reset_ignored':('geomind/c6_r4_field_analysis.py',"after['fields_real_imag']!=introduced['fields_real_imag']",'False'),
 'clock_reset_ignored':('geomind/c6_r4_field_analysis.py',"or abs(link['clock']-(300+200*i))>1e-7",''),
 'chain_scope_mismatch':('geomind/c6_r4_field_analysis.py',"if prefix and r['world'] not in chain:continue","if False:continue"),
 'duplicate_ids_allowed':('geomind/c6_r4_field.py',"if len(set(all_ids))!=len(all_ids):","if False:"),
 'uncorrected_ci':('experiments/c6_r4_protocol.json','"ci_level": 0.996875','"ci_level": 0.95'),
 'refined_inputs_redrawn':('geomind/c6_r4_field_protocol.py','rng(entropy,world,10,generation,episode),o,generation,episode','rng(entropy,world,10,generation,episode+k),o,generation,episode'),
 'false_witness_tuple':('geomind/c6_r4_field_analysis.py',"if cell['witness_tuple']!=[cell['episodes'][c][0]['qualification']['qualified'] for c in P.CONDITIONS]:","if False:"),
 'late_error_dropped_from_chain':('geomind/c6_r4_field_analysis.py','any(invalid_turn.values()) if prefix else invalid_turn[turn]','invalid_turn[turn]'),
 'before_publication_unchecked':('geomind/c6_r4_field_analysis.py',"if not publication_valid(episode['qualification'],episode['qualified_ids'][0]):raise ValueError('invalid before episode publication')","if False:raise ValueError('invalid before episode publication')"),
 'final_entropy_reuse_allowed':('geomind/run_c6_r4.py','if entropy in reserved.values():','if False:'),
 'raw_descriptor_duplicated':('geomind/c6_r4_field_analysis.py','source_inputs_summary(r)',"r.get('initial_source')"),
}
KNOWN_BACKSTOPS=set()
EXPECTED_TIMEOUTS=set()
