"""Describe saved evidence only; no integrations, verdict recomputation or replay."""
import dis,gzip,hashlib,inspect,json,math,subprocess
from datetime import datetime,timezone
from pathlib import Path
OUT=Path(__file__).resolve().parent;HERE=OUT.parent;ROOT=HERE.parents[3]
PIN='7a63d15064df745bfa63071473e02ffcb327901d6210c8310f5b5f8c3a330bce'
PROVENANCE='Assisted-by: Codex:GPT-6'
def digest(p):
 h=hashlib.sha256()
 with p.open('rb') as f:
  while b:=f.read(1048576):h.update(b)
 return h.hexdigest()
def write(n,v):
 with (OUT/n).open('x') as f:json.dump(v,f,sort_keys=True,indent=2,allow_nan=False);f.write('\n')
def load(n):return json.loads((OUT/n).read_text())
def slim(v):
 if isinstance(v,dict):return {k:slim(x) for k,x in v.items() if k not in ('records','episodes','events','native','reference')}
 if isinstance(v,list):return [slim(x) for x in v]
 return v
from evidence.tactical_composition_demo.growing_shapes.runner.rev7_identity import assert_inputs
from evidence.tactical_composition_demo.growing_shapes.runner.rev7_fixtures import Harness
from evidence.tactical_composition_demo.growing_shapes.runner.rev7_protocol import STOP_ROWS
identity=assert_inputs();assert identity['pin_sha256']==PIN
results={n:json.load(gzip.open(OUT/(n+'.json.gz'),'rt')) for n in ('N1','F1','F2','F3','F4')}
assert all(r['verdict']=='PASS' for r in results.values())
timings={p.name.removesuffix('_TIMING.json'):json.loads(p.read_text()) for p in OUT.glob('*_TIMING.json')}
assert not (OUT/'RUN_RECEIPT.json').exists()
lines,start=inspect.getsourcelines(Harness.F5);target=start+next(i for i,s in enumerate(lines) if s.strip()=='finally:')
executable={n for _,n in dis.findlinestarts(Harness.F5.__code__)};assert target not in executable
assert not (OUT/'F5i_TIMING.json').exists() and not (OUT/'F5ii_TIMING.json').exists()
defect={'status':'CONFIRMED','component':'new measurement wrapper, execute_once.py::growth_trace','target':f'rev7_fixtures.py:{target}','target_has_executable_bytecode':False,'cause':'Observer selected a structural finally line; Python 3.9 emits no line event there. It was copied from the historical wrapper, whose F5 observer had never been exercised because 7.4 stopped at N1.','missing':['F5i_TIMING.json','F5ii_TIMING.json','F5i_COMPONENT_COSTS.json','F5ii_COMPONENT_COSTS.json'],'action':'Stopped process 89340 with SIGINT after static confirmation; exit 130. No code patched and no fixture rerun.','scientific_engine_defect_established':False,'scientific_sources_changed':False,'wrapper_sha256':digest(OUT/'execute_once.py'),'evidence':'F5(ii) START without an F5(i) END; target absent from dis.findlinestarts; missing timing/component files.'}
write('WRAPPER_MEASUREMENT_DEFECT.json',defect)
# These are transition bounds, not complete per-start timing measurements.
log=(OUT/'EXECUTION_LOG.txt').read_text();boundaries={}
for line in log.splitlines():
 if ' START F5(' in line:
  utc,_,label=line.split();boundaries[label]=utc
first=boundaries['F5(i)'];second=boundaries['F5(ii)'];end=timings['F5']['end_utc']
f5={'verdict':'INVALID','reason':'Measurement-wrapper defect; operator interrupted the second start. No complete F5 result was persisted.','starts':{'i':{'execution':'reached next-start boundary; first start calculations completed in memory','scientific_verdict':None,'A':None,'B':None,'E':None,'B_out':None,'B_path':None,'events':None,'qualification_validity':None,'awake_seconds':None,'elapsed_utc_seconds':None,'start_utc':first,'next_start_boundary_utc':second,'boundary_elapsed_utc_seconds':(datetime.fromisoformat(second)-datetime.fromisoformat(first)).total_seconds(),'boundary_is_exact_fixture_cost':False},'ii':{'execution':'interrupted during growth','scientific_verdict':None,'A':None,'B':None,'E':None,'B_out':None,'B_path':None,'events':None,'qualification_validity':None,'awake_seconds':None,'elapsed_utc_seconds':None,'start_utc':second,'aggregate_F5_end_utc':end,'start_to_aggregate_end_utc_seconds':(datetime.fromisoformat(end)-datetime.fromisoformat(second)).total_seconds(),'boundary_is_exact_fixture_cost':False}}}
summary={n:slim(v) for n,v in results.items()};summary['F5']=f5
# Record endpoint geometry, without presenting the t=.1 endpoint as t=0.
for n,v in results['F1']['configurations'].items():
 if n=='F1d':continue
 rows=v['records'];out_id=max(map(int,rows[0]['positions']))
 geom={'first_record_time':rows[0]['time'],'last_record_time':rows[-1]['time'],'ordinary_span_first_endpoint':rows[0]['ordinary_span']['span'],'ordinary_span_final':rows[-1]['ordinary_span']['span'],'ordinary_radius_first_endpoint':rows[0]['ordinary_span']['radius'],'ordinary_radius_final':rows[-1]['ordinary_span']['radius'],'output_radius_first_endpoint':math.hypot(*rows[0]['positions'][str(out_id)]),'output_radius_final':math.hypot(*rows[-1]['positions'][str(out_id)]),'source_site_distance_first_endpoint':rows[0]['source_site_distance'],'source_site_distance_final':rows[-1]['source_site_distance'],'source_access_fraction':sum(r['drive_access'] for r in rows)/len(rows),'minimum_distances':{k:min(vals) if (vals:=[r['minimum_distances'][k] for r in rows if r['minimum_distances'][k] is not None]) else None for k in ('element_element','element_site')},'source_direct_drive_fraction':sum(r['exposure']['0']['drive'] for r in rows)/len(rows),'output_direct_drive_fraction':sum(r['exposure'][str(out_id)]['drive'] for r in rows)/len(rows),'unique_Ntheta_lists':len({json.dumps(r['neighbors'],sort_keys=True) for r in rows}),'shortcut_directed_edges_first_final':[sum(abs(int(i)-int(j))>1 for i,js in row['neighbors'].items() for j in js) for row in (rows[0],rows[-1])],'initial_declared_ordinary_span':0. if n=='F1a' else 1.112 if n=='F1b' else 2.78}
 summary['F1']['configurations'][n]['geometry']=geom
for scale,v in results['F1']['configurations']['F1d']['runs'].items():
 rows=v['records'];source=rows[0]['exposure']['0']
 summary['F1']['configurations']['F1d']['runs'][scale]['exposure_summary']={'source_sensor_access_fraction':sum(r['exposure']['0']['sensor_access'] for r in rows)/len(rows),'source_direct_drive_fraction':sum(r['exposure']['0']['drive'] for r in rows)/len(rows),'output_path_fraction':sum(any(r['paths']) for r in rows)/len(rows),'unique_Ntheta_lists':len({json.dumps(r['phase_topology'],sort_keys=True) for r in rows}),'positions_first_endpoint':rows[0]['positions'],'positions_final':rows[-1]['positions']}
holds=results['N1']['cases']['N1f']['entry_hold_through_24'];agreement=holds[0]==holds[1]
summary['F1c_numerical_hold']={'coarse_fine':holds,'agree':agreement,'reported_F1c_verdict':results['F1']['configurations']['F1c']['verdict'] if agreement else 'NUMERICALLY_UNRESOLVED','harness_verdict_preserved':results['F1']['configurations']['F1c']['verdict']}
summary['N1_minimum_distances']={n:[{k:min(vals) if (vals:=[r['minimum_distances'][k] for r in rows if r['minimum_distances'][k] is not None]) else None for k in ('element_element','element_site')} for rows in c['records']] for n,c in results['N1']['cases'].items()}
summary['F2'].update(empty_angle_exact_zero=results['F2']['empty_default'],empty_magnitude_exact_zero=results['F2']['empty_default'],path_present_any_stream=any(any(p) for p in results['F2']['paths']))
write('MEASURED_SUMMARY.json',{'verdict':'INVALID','revision':'7.5','results':summary,'timings':timings})
stop_rows=[]
fixture_evaluated={'N1_failed_or_invalid','F1_F4_failed','fixture_invalid'}
preflight={'integration_not_tested_reviewed','source_unit_endpoint_mismatch','protocol_changed_after_results','engines_not_ready_reviewed'}
for q,a,role in STOP_ROWS:
 outcome='YES' if q=='fixture_invalid' else 'NO' if q in fixture_evaluated|preflight else 'NOT_EVALUATED'
 stop_rows.append(dict(question=q,outcome=outcome,action=a,role=role))
write('STOP_ROW_OUTCOMES.json',stop_rows)
work={'trainings':48,'training_world_frames':15360000,'growth_checks':76800,'qualification_starts':8512,'snapshot_assay_episodes_max':327680,'total_assay_episodes_max_all_four_tasks':434176,'site_body_off_added_episodes':2048,'site_body_off_episodes_per_intact_training':128,'intact_trainings':16,'donor_capture_episodes':8192}
nrate=timings['N1']['awake_seconds']/120000;frate=timings['F1']['awake_seconds']/192000;assay=timings['F4']['awake_seconds']/10
projection={'status':'A7_PARTIAL_TOTAL_NOT_QUALIFIED','workload':work,'N1_composite_awake_seconds_per_substep':nrate,'F1_composite_awake_seconds_per_substep':frate,'F4_mixed_native_reference_awake_seconds_per_assay_episode':assay,'unqualified_arithmetic_training_hours_N1_proxy':work['training_world_frames']*20*nrate/3600,'unqualified_arithmetic_training_hours_F1_proxy':work['training_world_frames']*20*frate/3600,'unqualified_arithmetic_all_assay_hours_F4_proxy':work['total_assay_episodes_max_all_four_tasks']*assay/3600,'unqualified_arithmetic_site_body_off_added_hours_F4_proxy':2048*assay/3600,'qualified_total_hours':None,'grown_population_training_rate':None,'grown_population_assay_rate':None,'qualification_rate':None,'recovery_rate':None,'B_path_rate':None,'donor_capture_rate':None,'F5_partial_aggregate_awake_seconds':timings['F5']['awake_seconds'],'development':'NOT_RUN_BLOCKED_INVALID_FIXTURES','lower_or_upper_bound':False,'limitation':'Small frozen-scaffold composites include construction, endpoint diagnostics, observer dispatch and measurement. F4 mixes native/reference and five interventions on a two-member scaffold. Neither prices grown live media. F5 first-start scientific values and component clocks were lost on interrupt; aggregate partial duration has no persisted workload denominator. Arithmetic scenarios are not a qualified total or independent component rates; no pricing run occurred.'}
write('A7_DEVELOPMENT_COST_PROJECTION.json',projection)
before=load('OUTSIDE_SCOPE_BASELINE.json');changed=[n for n,h in before.items() if not (ROOT/n).is_file() or digest(ROOT/n)!=h]
staged=subprocess.check_output(['git','diff','--cached','--binary'],cwd=ROOT)
preservation={'status':'PASS' if not changed and not staged else 'FAIL','tracked_files_checked':len(before),'tracked_changes':changed,'execution_pin_sha256':identity['pin_sha256'],'scientific_inputs_checked':len(identity['sha256']),'plan_unchanged':digest(ROOT/'docs/PLAN_CURRENT.md')==before['docs/PLAN_CURRENT.md'],'staged_diff_empty_at_start_and_end':not staged,'staged_diff_sha256':hashlib.sha256(staged).hexdigest(),'historical_evidence_unchanged':not any(n.startswith('evidence/tactical_composition_demo/growing_shapes/') for n in changed)}
write('FINAL_PRESERVATION.json',preservation)
a=timings['N1']['start_clock'];b=timings['F5']['end_clock'];envelope={'start_utc':a['utc'],'end_utc':b['utc'],'awake_seconds':b['awake']-a['awake'],'elapsed_utc_seconds':(datetime.fromisoformat(b['utc'])-datetime.fromisoformat(a['utc'])).total_seconds(),'scope':'Observed N1-method start through interrupted F5-method finally; excludes initial gate/setup and subsequent harness close/process exit/reporting. Full harness total clock not persisted.'}
receipt={'kind':'OPERATOR_INTERRUPTION_RECEIPT_NOT_HARNESS_RECEIPT','created_utc':datetime.now(timezone.utc).isoformat(),'revision':'7.5','verdict':'INVALID','execution_once':True,'process_exit_code':130,'stop_action':'SIGINT after confirmed wrapper measurement defect','identity_snapshot':load('START_IDENTITY.json'),'completed_results':{n:{'verdict':r['verdict'],'path':str((OUT/(n+'.json.gz')).relative_to(ROOT)),'sha256':digest(OUT/(n+'.json.gz'))} for n,r in results.items()},'interrupted_fixture':'F5','not_run':['F6','F7','F8','F9'],'F5_result_persisted':False,'original_Harness_run_all_receipt':'NOT_RETURNED_ON_KEYBOARD_INTERRUPT','stop_rows':stop_rows,'observed_fixture_envelope':envelope,'provenance':PROVENANCE}
write('OPERATOR_INTERRUPTION_RECEIPT.json',receipt)
report=['INVALID','',f'Revision 7.5 fixtures started ONCE at execution pin `{PIN}`; all 69 scientific inputs matched before execution and after the stop. Grant: `docs/decisions/0031-owner-run-approval-policy.md`; integration_review: `evidence/tactical_composition_demo/growing_shapes_review_claude/REV75_FIXTURE_READINESS_CONFIRMED.md` (READY_FOR_FIXTURES, Claude). New output: `rev75_fixture_run_20261006/`. Historical 7.3/7.4 reports and receipts are unchanged.','', 'N1 and F1–F4 PASS. F5 is INVALID because the new measurement wrapper missed per-start cost records; it watched a non-executable structural `finally:` line. This observer was copied from the historical 7.4 wrapper, whose F5 path had not run. Static bytecode inspection confirmed the defect after F5 advanced to start ii. The implementer immediately stopped with SIGINT (exit 130), as instructed. No scientific engine defect is established. No code changed during execution, and no patch or rerun occurred.','', 'F5(i) finished its calculations in memory and reached the next-start boundary, but its A/B/E, events, qualification summaries and component costs were not persisted. F5(ii) was interrupted during growth. The F5 method therefore never returned a result, and KeyboardInterrupt prevented the outer wrapper from writing its final harness receipt. OPERATOR_INTERRUPTION_RECEIPT.json explicitly describes this interrupted run; it is not a substitute passing harness receipt. F6–F9 are NOT_RUN.','', 'Static full-harness estimate before execution: 2305.295380 s (38.421590 min), scheduling allowance 2458.981739 s (40.983029 min), below one hour. Counts include 120,000 N1 substeps (N1g included), 192,000 F1 substeps, both F5 starts, F6–F9 and qualification/recovery sensitivity. Rates reuse historical evidence with assumed multipliers/contingency; this is not a measured total or bound. DURATION_ESTIMATE.json retains all assumptions and source hashes. No rehearsal or benchmark was run.','', '| Fixture | Verdict/status | Start UTC | End UTC | Awake s | Elapsed UTC s |','|---|---|---|---|---:|---:|']
for n in ('N1','F1','F1a','F1b','F1c','F1d','F2','F3','F4','F5'):
 t=timings[n];v='INVALID / interrupted aggregate' if n=='F5' else 'DESCRIPTIVE' if n=='F1d' else 'PASS'
 report.append(f"| {n} | {v} | {t['start_utc']} | {t['end_utc']} | {t['awake_seconds']:.6f} | {t['elapsed_utc_seconds']:.6f} |")
for n in ('F5(i)','F5(ii)'):report.append(f'| {n} | measurement missing | {boundaries[n]} | null | null | null |')
for n in ('F6','F7','F8','F9'):report.append(f'| {n} | NOT_RUN | null | null | null | null |')
report+=['',f"Observed fixture envelope: {envelope['awake_seconds']:.6f} s awake / {envelope['elapsed_utc_seconds']:.6f} s elapsed UTC ({envelope['elapsed_utc_seconds']/60:.6f} min), {envelope['start_utc']} → {envelope['end_utc']}. {envelope['scope']} Awake uses mach_absolute_time (excludes sleep); continuous uses mach_continuous_time; elapsed is the UTC difference. Raw clock endpoints are retained. Method costs exclude subsequent compressed trace writing; F1 includes nested F1d (do not sum them). F1a–c costs include integration/measurement but exclude final close.",'',f"F5(i) start-to-next-start boundary: {f5['starts']['i']['boundary_elapsed_utc_seconds']:.6f} elapsed UTC s; F5(ii) start-to-aggregate-end boundary: {f5['starts']['ii']['start_to_aggregate_end_utc_seconds']:.6f} s. These include transition/cleanup and are not complete measured per-start fixture costs. No per-start awake clock or component clock was saved; the missing values stay null.",'', 'N1 criterion: production h=0.005 versus refinement h=0.00125, λ=32; wrapped and unwrapped carrier-relative phase differences each ≤0.01 rad, free-position difference ≤0.01 m.u., Nθ and Nx identical in ≥0.99 endpoints, pins invariant; applicable entry times agree within 0.1 s or both absent. N1a–e run 16 s; N1f runs 24 s. N1g runs 16 s descriptively, outside accuracy cuts; missing/nonfinite measurements would still be INVALID.','', '| Case | Verdict | Wrapped rad | Unwrapped rad | Position m.u. | Entry coarse/fine s | Nθ | Nx | Pins |','|---|---|---:|---:|---:|---|---:|---:|---|']
for n,c in results['N1']['cases'].items():report.append(f"| {n} | {c['verdict']} | {c['maximum_wrapped_phase']:.12g} | {c['maximum_unwrapped_phase']:.12g} | {c['maximum_free_position']:.12g} | {c['entry_times'] if c['entry_applicable'] else 'N/A'} | {c['Ntheta_agreement']} | {c['Nx_agreement']} | {c['pins_invariant']} |")
report+=['',f'N1f coarse/fine holds through t=24: {holds}; agreement={agreement}. F1c reported verdict: {summary["F1c_numerical_hold"]["reported_F1c_verdict"]}. The current N1f hold agrees; no numerical-unresolved flag applies. The independent 160 s F1c gate also passed.','', 'N1g slip is an endpoint escape diagnostic, not a completed winding or an accuracy verdict. The first departure ≥0.5 rad from member 0’s initial unwrapped carrier-relative π has opposite signs in the two integrations. Both first crossings occur at 0.6 s, bracketed by [0.5,0.6] s. h=0.005: direction −1, departure −1.18789486378 rad, final phase approximately 0, final displacement −π. h=0.00125: direction +1, departure +2.91994890256 rad, final phase approximately 2π, final displacement +π. DESCRIPTIVE / SENSITIVITY_NOT_ACCURACY / used_in_verdict=False.','', 'N1 validity (coarse/fine; individual and used-pair masks are descriptive):','', '| Case | Individual invalid frames/observations | Pair invalid frames/observations | Individual disagreement frames/observations | Pair disagreement frames/observations | Minimum distances coarse / fine, m.u. |','|---|---|---|---|---|---|']
for n,c in results['N1']['cases'].items():
 v=c['validity'];report.append(f"| {n} | {v['individual_invalid_frames']} / {v['individual_invalid_observations']} | {v['used_pair_invalid_frames']} / {v['used_pair_invalid_observations']} | {v['individual_disagreement_frames']} / {v['individual_disagreement_observations']} | {v['used_pair_disagreement_frames']} / {v['used_pair_disagreement_observations']} | {summary['N1_minimum_distances'][n]} |")
report+=['', 'F1a/b require entry ≤0.3 rad by t=16 after the t=8 step, hold at every endpoint through 16, and path fraction ≥0.8 over 160 s. F1c requires entry by 16, hold through 24, path and source access ≥0.8 over 160 s, and response persistence ≥0.8 over [16,160]. Output pin invariance is an implementation check. Sustained delay, error at 12 and four-second margin are descriptive.','', '| Case | Entry s / delay s | Hold | Path fraction | Access fraction | Persistence [16,160] | Ordinary span initial / first endpoint / final | Ordinary radius first / final |','|---|---|---|---:|---:|---|---|---|']
for n in ('F1a','F1b','F1c'):
 c=summary['F1']['configurations'][n];g=c['geometry'];hold=c.get('continuous_to_24',c.get('continuous_from_first_entry'))
 report.append(f"| {n} | {c['first_entry_time']:.6f} / {c['delay']:.6f} | {hold} | {c['path_exposure']} | {g['source_access_fraction']} | {c.get('response_persistence','not gated')} | {g['initial_declared_ordinary_span']:.6f} / {g['ordinary_span_first_endpoint']:.9g} / {g['ordinary_span_final']:.9g} | {g['ordinary_radius_first_endpoint']:.9g} / {g['ordinary_radius_final']:.9g} |")
c=summary['F1']['configurations']['F1c'];report+=['',f"F1c sustained-entry delay {c['sustained_entry_delay']:.6f} s; error at t=12 {c['error_at_12']:.12g} rad; four-second margin={c['four_second_margin_met']} (descriptive). Ordinary-member compaction coexists with preserved pin/path/access; this is not a claim of no compaction or serial chain bandwidth. Geometry/exposure details (first endpoint is t=.1, final t=160):",'']
for n in ('F1a','F1b','F1c'):report.append(f"{n}: `{json.dumps(summary['F1']['configurations'][n]['geometry'],sort_keys=True)}`\n")
report+=['F1d is descriptive: same F1b start and input at λ=1, 8 and 32, all h=.005.','', '| λ | Entry / delay s | Hold through 16 | Deadline error rad | Output path fraction | Source access / direct drive | Unique Nθ lists |','|---|---|---|---:|---:|---|---:|']
for scale,c in summary['F1']['configurations']['F1d']['runs'].items():
 e=c['exposure_summary'];report.append(f"| {scale} | {c['first_entry_time']} / {c['delay']} | {c['continuous_from_first_entry']} | {c['deadline_error']:.12g} | {e['output_path_fraction']} | {e['source_sensor_access_fraction']} / {e['source_direct_drive_fraction']} | {e['unique_Ntheta_lists']} |")
report+=['', 'F1d geometry endpoints and effective-root/topology histories are retained in F1d.json.gz; endpoints and exposure summaries are also in MEASURED_SUMMARY.json. A missing λ=1 entry is deadline-censored, not a measured delay.','', f"F2 PASS: empty default angle=0 and magnitude=0 exactly, no path; disconnected stepped/unstepped 160-phase streams bitwise_identical={results['F2']['bitwise_identical']}, any path={summary['F2']['path_present_any_stream']}. F3 PASS: output drive exactly +0.0 at all 80 RK4 stages (20 substeps×4). F4 PASS: internal output-channel phase coupling exactly zero at all 80 stages; site0={results['F4']['site0']:.12g} and oracle={results['F4']['oracle']:.12g} angles exactly match wrapped .4 and 1.1. Native/reference magnitude, choice, path and output-presence checks are exact; wrapped-angle tolerance is 1e-12.",'', '| F4 parity mode | Status | Decisions | Maximum wrapped angle difference rad |','|---|---|---:|---:|']
for n,c in results['F4']['assay_parity'].items():report.append(f"| {n} | {c['status']} | {c['decisions']} | {c['maximum_wrapped_angle_error']:.12g} |")
report+=['', 'F5 criterion, both starts: pooled paired frozen assays at checkpoints 40/45/50 require max(E)≥0.5, A≥0.3, B≥0.3; start i additionally requires a B-out birth, start ii a B-path birth. Measured A/B/E, B-out/B-path events, refusal counts and times are unavailable for both starts. Start i reached the next-start boundary but its values were not saved; start ii was interrupted. No zero, PASS or FAIL is inferred.','', 'F5 descriptive not-qualified-window summary: UNAVAILABLE for i and ii (null qualification-window counts, invalid-pair counts/fractions, frame counts). Intended intervals by check endpoint are (0,640], (640,720], (720,800] and whole (0,800] s; small-cohort starts remain in denominators, an empty denominator gives null, fast-transient frames count once, recovery skips are excluded, used_in_verdict=False. The missing summary is part of the INVALID measurement; N1 mask counts do not substitute for it.','', '| Later fixture | Criterion and measurements | Status / stop |','|---|---|---|','| F6 | Descriptive encoding/retention/circular correlation; ≥5 defined pairs; unique-recipient baseline denominator | NOT_RUN; blocked by INVALID F5 |','| F7 | Match every requested control-M B1 birth; unmatched=0; fraction null if zero requests. Requested/matched/unmatched/fraction all null | NOT_RUN; blocked by INVALID F5 |','| F8 | Descriptive move then memory reward/eligibility/B1 demand on live F5(i) state; all quantities null | NOT_RUN; blocked by INVALID F5 |','| F9 | Four literal descriptive decoder observations; actions/demands null | NOT_RUN; blocked by INVALID F5 |','', 'Order and stops: N1 ran first and passed; F1a–c then descriptive F1d passed/gave measurements; F2–F4 all ran and passed. The F1-F4 FAIL stop was NO. F5 started i then ii, but fixture_invalid fires YES on the measurement-wrapper defect; implementer stops and blocks the next stage. This is an operator stop under §9.7, not a returned harness stop list. All other future/development rows remain NOT_EVALUATED.','', '| Stop question | Outcome | Action | Role |','|---|---|---|---|']
for row in stop_rows:report.append(f"| {row['question']} | {row['outcome']} | {row['action']} | {row['role']} |")
report+=['',f"A7 development projection is PARTIAL / TOTAL_NOT_QUALIFIED. Measured N1 composite: {nrate:.12g} awake s/substep; F1 composite: {frate:.12g} s/substep; F4 mixed native/reference composite: {assay:.12g} s/assay episode. At 20 production substeps/frame, arithmetic-only training proxies are {projection['unqualified_arithmetic_training_hours_N1_proxy']:.6f} h (N1) or {projection['unqualified_arithmetic_training_hours_F1_proxy']:.6f} h (F1). Applying F4's small mixed-scaffold composite to all assays gives {projection['unqualified_arithmetic_all_assay_hours_F4_proxy']:.6f} h, including an arithmetic {projection['unqualified_arithmetic_site_body_off_added_hours_F4_proxy']:.6f} h for 2,048 site-body-off episodes. These are explicitly unqualified scenarios, not isolated RHS rates, native-grown-media estimates, total hours or bounds; do not sum alternative training proxies or add site-body-off twice.",'',f"Inherited workload counts: `{json.dumps(work,sort_keys=True)}`. Grown-population training/assay, B-path, qualification, recovery and donor-capture rates remain null. Partial F5 cost is {timings['F5']['awake_seconds']:.6f} awake s with no persisted workload/component denominator; it cannot price those components. Qualified total=null. No training/development, development evaluation panel, judging entropy or registration occurred; only fixture-specific growth and frozen assays executed.",'',f"Preservation: {preservation['status']}; {preservation['tracked_files_checked']} tracked files checked, pin unchanged, docs/PLAN_CURRENT.md unchanged={preservation['plan_unchanged']}, historical evidence unchanged={preservation['historical_evidence_unchanged']}, staged diff empty at both observations={preservation['staged_diff_empty_at_start_and_end']}. RRG source inventory was also read-only verified during the run: 23 manifest entries, 24 checksum entries and all 12 owner hashes match. All task-created artifacts stay in growing_shapes/.",'', 'Mandatory owner recheck and disposition are recorded beside this run, under the owner’s explicit restriction against editing docs/PLAN_CURRENT.md. The report/evidence delivery is distinct from scientific acceptance or development readiness.','', PROVENANCE]
with (HERE/'REV75_FIXTURE_REPORT.md').open('x') as f:f.write('\n'.join(report)+'\n')
print(json.dumps({'report':str(HERE/'REV75_FIXTURE_REPORT.md'),'verdict':'INVALID','completed':{n:r['verdict'] for n,r in results.items()},'envelope':envelope,'preservation':preservation}))
